package elaborate

// Cross-repository drift guard for the CPU-level metrics elaboration top.
//
// THE PROBLEM THIS EXISTS FOR. The gf180 synth-metrics flow publishes a
// `j4_core` area series. Its elaboration top is named in
// targets/asic/gf180_j4mmu/metrics/macros.list, and it used to be the BARE
// configuration `cpu_synth_j4`, whose priv_arch generic defaults to false --
// so the published "J4 + MMU core" number was a core with no TLB and no
// privileged datapath. Measured 2026-08-09 on GF180 9T/3.3V: 440,746 um2
// with the MMU off versus 1,029,476 um2 with it on. The dashboard was
// understating the shipped core by more than 2x, and nothing caught it
// because a configuration that binds no generics is perfectly valid VHDL.
//
// macros.list now names `cpu_synth_j4_priv` (top `cpu_j4_priv_top`), the
// wrapper the CPU submodule already provides -- the yosys ghdl plugin cannot
// take `ghdl -g`, so a generic override has to come from a configuration
// binding, which needs a component-instantiation context.
//
// THE DRIFT RISK THAT REPLACES IT. That wrapper's generic map is hand-written
// in components/cpu (jcore-cpu), while the SoC's own binding is generated by
// emit.CPUsConfig from components/cpu/variants.toml (read at runtime, so the
// SoC side cannot drift). Those are two independently-editable declarations
// of the same intent, in two repositories, and they have already disagreed
// once: MMU_ARCH was removed from one and not the other. A future variant
// generic -- a hypervisor knob, say -- reopens exactly the same gap, and the
// failure is silent: the metric would quietly measure a differently-
// configured core again.
//
// So: assert the wrapper's generic map is exactly variants.toml's [j4]
// generics. If jcore-cpu adds, removes or retypes a j4 generic without
// updating cpu_synth_j4_priv, this fails at the submodule bump instead of
// months later in a published area number.

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// metricsTopConfig is the configuration macros.list elaborates for j4_core,
// and the file in the CPU submodule that declares it.
const (
	metricsTopConfigName = "cpu_synth_j4_priv"
	metricsTopEntity     = "cpu_j4_priv_top"
	metricsTopFile       = "components/cpu/synth/cpu_synth_j4_config.vhd"
	metricsTopModel      = "j4"
)

var (
	// `configuration <name> ... end configuration` -- VHDL is case-insensitive.
	reConfigBlock = regexp.MustCompile(`(?is)configuration\s+` + metricsTopConfigName +
		`\s+of\s+(\w+)\s+is(.*?)end\s+configuration`)
	// `generic map ( a => b, c => d )`
	reGenericMap = regexp.MustCompile(`(?is)generic\s+map\s*\((.*?)\)\s*;`)
	reAssoc      = regexp.MustCompile(`(?is)(\w+)\s*=>\s*([^,)]+)`)
)

// parseMetricsTopGenerics returns the entity the configuration is OF, and the
// generic map it binds, normalised to upper-case names / lower-case values.
func parseMetricsTopGenerics(t *testing.T, src string) (string, map[string]string) {
	t.Helper()
	block := reConfigBlock.FindStringSubmatch(src)
	if block == nil {
		t.Fatalf("%s: no `configuration %s of <entity> ... end configuration` found.\n"+
			"macros.list elaborates that configuration for the j4_core metric; if it was "+
			"renamed or removed, update macros.list and this guard together.",
			metricsTopFile, metricsTopConfigName)
	}
	ofEntity := strings.ToLower(block[1])

	gm := reGenericMap.FindStringSubmatch(block[2])
	if gm == nil {
		// A configuration with NO generic map is the exact regression this
		// guard exists for: valid VHDL, silently binds the defaults.
		return ofEntity, map[string]string{}
	}
	got := map[string]string{}
	for _, m := range reAssoc.FindAllStringSubmatch(gm[1], -1) {
		got[strings.ToUpper(strings.TrimSpace(m[1]))] = strings.ToLower(strings.TrimSpace(m[2]))
	}
	return ofEntity, got
}

func TestMetricsTopGenericsMatchVariantsToml(t *testing.T) {
	v, err := variantFor(metricsTopModel)
	if err != nil {
		t.Fatalf("variantFor(%q): %v", metricsTopModel, err)
	}

	path := filepath.Join(defaultRoot(), metricsTopFile)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (is the components/cpu submodule initialised?)", path, err)
	}
	ofEntity, got := parseMetricsTopGenerics(t, string(raw))

	if ofEntity != metricsTopEntity {
		t.Errorf("%s is a configuration of %q, but macros.list elaborates top %q",
			metricsTopConfigName, ofEntity, metricsTopEntity)
	}

	want := map[string]string{}
	for k, val := range v.Generics {
		want[strings.ToUpper(k)] = strings.ToLower(val)
	}

	for k, wv := range want {
		gv, ok := got[k]
		if !ok {
			t.Errorf("variants.toml [%s] sets generic %s=%s, but %s's generic map does not bind it.\n"+
				"  -> the j4_core metric would measure a core WITHOUT it "+
				"(this is how the published number lost the MMU: 440,746 vs 1,029,476 um2).\n"+
				"  -> fix %s in the components/cpu submodule to match.",
				metricsTopModel, k, wv, metricsTopConfigName, metricsTopFile)
			continue
		}
		if gv != wv {
			t.Errorf("generic %s: variants.toml says %s, %s binds %s", k, wv, metricsTopConfigName, gv)
		}
	}
	for k, gv := range got {
		if _, ok := want[k]; !ok {
			t.Errorf("%s binds generic %s=%s that variants.toml [%s] does not define.\n"+
				"  -> the j4_core metric would measure a core the SoC does not ship "+
				"(emit.CPUsConfig binds only variants.toml's generics).",
				metricsTopConfigName, k, gv, metricsTopModel)
		}
	}
}

// TestMetricsTopMatchesSoCBinding closes the loop: the generics the metric
// elaborates must be the generics the SoC actually ships. Both come from
// CPUSynthConfig, so this fails if the two ever diverge.
func TestMetricsTopMatchesSoCBinding(t *testing.T) {
	_, socGenerics, _, err := CPUSynthConfig(metricsTopModel, "direct", "")
	if err != nil {
		t.Fatalf("CPUSynthConfig: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(defaultRoot(), metricsTopFile))
	if err != nil {
		t.Fatalf("read %s: %v", metricsTopFile, err)
	}
	_, metricGenerics := parseMetricsTopGenerics(t, string(raw))

	if len(socGenerics) != len(metricGenerics) {
		t.Fatalf("SoC binds %d generic(s) %v, metrics top binds %d %v",
			len(socGenerics), socGenerics, len(metricGenerics), metricGenerics)
	}
	for k, sv := range socGenerics {
		mv, ok := metricGenerics[strings.ToUpper(k)]
		if !ok || mv != strings.ToLower(sv) {
			t.Errorf("generic %s: SoC (cpus_config.vhd) binds %s, j4_core metric binds %q",
				k, sv, mv)
		}
	}
}
