library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.flash_image_pkg.all;

-- Task 8b: full end-to-end GHDL cosim of the iCESugar CoreMark runner.
--
-- Proves the whole chain in one run: config-flash Fast-Read boot ->
-- flash_boot_reader streams the payload into SPRAM -> cpus_coremark
-- releases core0 from reset once the stream completes -> the CPU executes
-- cosim_main.c's main() (start_time/busy-wait/stop_time/portme_finish) out
-- of SPRAM -> uart_report.c's report_result() prints the CMK result record
-- over uart0, which this tb deserializes and checks.
--
-- Instantiates entity work.soc(impl) directly (NOT pad_ring): soc(impl)'s
-- fl_miso/eth_miso ports have correct (in) direction; pad_ring's
-- soc_gen-generated pin_spi_miso_pin/pin_w5500_miso passthrough for the
-- config-flash pins is mis-directioned as `out` (a soc_gen bug -- see
-- task-8b-report.md), which would make it impossible for a tb to drive flash
-- data back into the design through pad_ring's boundary. soc(impl) avoids
-- that entirely and is otherwise the same instance pad_ring wraps.
--
-- The flash-slave behavioral model (Fast-Read 0x0B: cmd+3-byte addr+8 dummy
-- clocks, then auto-incrementing MSB-first streaming while CS stays low) is
-- copied from targets/boards/icesugar/tb/cpus_coremark_boot_tb.vhd's
-- flash_slave procedure, adapted to stream real payload bytes (from
-- flash_image_pkg, generated by tools/genflashpkg from cosim.bin) instead of
-- that tb's synthetic 0xA0000000+i pattern.
entity coremark_cosim_tb is end entity;

architecture sim of coremark_cosim_tb is
  constant CLK_PER    : time := 1 sec / 12_000_000;  -- 12 MHz oscillator
  constant FLASH_BASE : std_logic_vector(23 downto 0) := x"100000";
  constant BIT_PER    : time := 1 sec / 115200;   -- 8N1 @115200 from 12 MHz clk
  constant CR         : character := character'val(13);

  signal clk   : std_logic := '0';
  signal reset : std_logic := '1';
  signal done  : boolean := false;

  signal fl_cs_n, fl_sck, fl_mosi : std_logic;
  signal fl_miso : std_logic := '0';

  signal gpio_do  : std_logic_vector(2 downto 0);
  signal uart0_tx : std_logic;
  signal uart0_rx : std_logic := '1';
  signal ready_seen : boolean := false;

  -- shared Fast-Read (0x0B) SPI-flash slave model, adapted from
  -- cpus_coremark_boot_tb.vhd's flash_slave to stream flash_image_pkg bytes.
  procedure flash_slave(
    signal cs_n  : in  std_logic;
    signal sck   : in  std_logic;
    signal mosi  : in  std_logic;
    signal miso  : out std_logic) is
    variable cmd_addr   : std_logic_vector(31 downto 0);
    variable addr       : natural;
    variable byte_val    : std_logic_vector(7 downto 0);
  begin
    wait until cs_n = '0';

    cmd_addr := (others => '0');
    for k in 0 to 31 loop
      wait until rising_edge(sck);
      cmd_addr := cmd_addr(30 downto 0) & mosi;
    end loop;

    for k in 0 to 7 loop
      wait until rising_edge(sck);
    end loop;

    addr := to_integer(unsigned(cmd_addr(23 downto 0))) - to_integer(unsigned(FLASH_BASE));

    for i in addr to FLASH_IMAGE_BYTES - 1 loop
      byte_val := FLASH_IMAGE(i);
      for k in 7 downto 0 loop
        wait until falling_edge(sck);
        miso <= byte_val(k);
      end loop;
      exit when cs_n = '1';
    end loop;
  end procedure;

  -- true when needle appears in haystack(1 to n)
  function contains(haystack : string; n : integer; needle : string)
    return boolean is
  begin
    if n < needle'length then return false; end if;
    for i in 1 to n - needle'length + 1 loop
      if haystack(i to i + needle'length - 1) = needle then
        return true;
      end if;
    end loop;
    return false;
  end function;

begin
  uut : entity work.soc(impl)
    port map (
      clk_sys  => clk,
      fl_cs_n  => fl_cs_n,
      fl_miso  => fl_miso,
      fl_mosi  => fl_mosi,
      fl_sck   => fl_sck,
      gpio_do  => gpio_do,
      reset    => reset,
      uart0_rx => uart0_rx,
      uart0_tx => uart0_tx
    );

  clk <= not clk after CLK_PER/2 when not done else '0';

  flash_model : process
  begin
    flash_slave(fl_cs_n, fl_sck, fl_mosi, fl_miso);
    wait;
  end process;

  stim : process begin
    reset <= '1';
    wait for CLK_PER * 4;
    wait until rising_edge(clk);
    reset <= '0';
    wait;
  end process;

  -- UART receiver: decode uart0_tx into a string, sampling at the bit centre,
  -- LSB first, 8N1. Raises ready_seen for the stimulus process and checks the
  -- result record once "CMK DONE" terminates it.
  rx_mon : process
    variable buf : string(1 to 2048) := (others => ' ');
    variable n   : integer := 0;
    variable b   : std_logic_vector(7 downto 0);
  begin
    loop
      wait until uart0_tx = '0';        -- start bit
      wait for BIT_PER/2;
      for k in 0 to 7 loop
        wait for BIT_PER;
        b(k) := uart0_tx;               -- LSB first
      end loop;
      wait for BIT_PER;                 -- stop bit
      if n < buf'length then
        n := n + 1;
        buf(n) := character'val(to_integer(unsigned(b)));
      end if;

      if contains(buf, n, "CMK READY") and not ready_seen then
        report "diag: CMK READY seen at " & time'image(now) severity note;
        ready_seen <= true;
      end if;

      if contains(buf, n, "CMK DONE") then
        report "coremark_cosim_tb: received text:" severity note;
        report buf(1 to n) severity note;

        assert contains(buf, n, "CMK MAGIC=0x4b4d434a")
          report "Test Failed: magic line missing/incorrect" severity error;
        -- 0xd340 is CoreMark's crcfinal -- NOT crclist (0xe714).
        assert contains(buf, n, "CMK CRC=0x0000d340")
          report "Test Failed: crc line missing/incorrect" severity error;
        assert contains(buf, n, "CMK ITERATIONS=1000")
          report "Test Failed: iterations line missing/incorrect" severity error;
        assert contains(buf, n, "CMK CLKHZ=12000000")
          report "Test Failed: clk_hz line missing/incorrect" severity error;
        assert not contains(buf, n, "CMK CYCLES=0" & CR)
          report "Test Failed: cycles field is zero (cycle counter not working)"
          severity error;

        report "Test Passed" severity note;
        done <= true;
        wait;
      end if;
    end loop;
  end process;

  -- Stimulus: once the board announces readiness, shift the 'g' trigger byte
  -- out on uart0_rx (8N1, LSB first) to start the run.
  tx_stim : process
    constant GO : std_logic_vector(7 downto 0) := x"67";  -- 'g'
  begin
    if not ready_seen then
      wait until ready_seen;
    end if;
    wait for BIT_PER;
    uart0_rx <= '0';                    -- start bit
    wait for BIT_PER;
    for k in 0 to 7 loop
      uart0_rx <= GO(k);                -- LSB first
      wait for BIT_PER;
    end loop;
    uart0_rx <= '1';                    -- stop bit
    report "diag: sent 'g' trigger at " & time'image(now) severity note;
    wait;
  end process;

  -- Diagnostics: observe flash-boot completion (fl_cs_n rising after the
  -- streaming burst) and count UART tx start-bits so a timeout report can
  -- distinguish "CPU never booted" from "CPU booted but never emitted UART".
  diag_boot : process begin
    wait until fl_cs_n = '1' and now > 1 us;
    report "diag: flash-boot burst complete (fl_cs_n rose) at " & time'image(now) severity note;
    wait;
  end process;

  diag_uart : process
    variable chars : natural := 0;
  begin
    loop
      wait until uart0_tx = '0';
      chars := chars + 1;
      if chars <= 6 or (chars mod 40) = 0 then
        report "diag: uart tx char #" & integer'image(chars) & " at " & time'image(now) severity note;
      end if;
      wait for BIT_PER * 9;
    end loop;
  end process;

  -- Watchdog is deliberately strictly below sim.sh's --stop-time=200ms (150ms
  -- here) so the watchdog assertion always fires before GHDL's stop-time ends
  -- the run cleanly. A watchdog >= stop-time makes the gate vacuous (GHDL
  -- exits 0 before the assertion can ever trigger) -- that exact defect hid a
  -- broken testbench on this board for months.
  watchdog : process begin
    wait for 150 ms;
    assert done report "Test Failed: TIMEOUT waiting for CMK DONE" severity failure;
    wait;
  end process;

end architecture;
