library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.flash_image_pkg.all;

-- Task 8b: full end-to-end GHDL cosim of the iCESugar CoreMark runner.
--
-- Proves the whole chain in one run: config-flash Fast-Read boot ->
-- flash_boot_reader streams the payload into SPRAM -> cpus_coremark
-- releases core0 from reset once the stream completes -> the CPU executes
-- cosim_main.c's main() (start_time/busy-wait/stop_time/portme_finish) out
-- of SPRAM -> eth_report.c's report_result() drives the spi2 'eth' master
-- to program a W5500-model socket 0 and SEND a 24-byte result struct.
--
-- Instantiates entity work.soc(impl) directly (NOT pad_ring): soc(impl)'s
-- fl_miso/eth_miso ports have correct (in) direction; pad_ring's
-- soc_gen-generated pin_spi_miso_pin/pin_w5500_miso passthrough for the
-- config-flash pins is mis-directioned as `out` (a soc_gen bug -- see
-- task-8b-report.md), which would make it impossible for a tb to drive flash
-- data back into the design through pad_ring's boundary. soc(impl) avoids
-- that entirely and is otherwise the same instance pad_ring wraps.
--
-- The flash-slave behavioral model (Fast-Read 0x0B: cmd+3-byte addr+8 dummy
-- clocks, then auto-incrementing MSB-first streaming while CS stays low) is
-- copied from targets/boards/icesugar/tb/cpus_coremark_boot_tb.vhd's
-- flash_slave procedure, adapted to stream real payload bytes (from
-- flash_image_pkg, generated by tools/genflashpkg from cosim.bin) instead of
-- that tb's synthetic 0xA0000000+i pattern.
entity coremark_cosim_tb is end entity;

architecture sim of coremark_cosim_tb is
  constant CLK_PER    : time := 1 sec / 12_000_000;  -- 12 MHz oscillator
  constant FLASH_BASE : std_logic_vector(23 downto 0) := x"100000";

  signal clk   : std_logic := '0';
  signal reset : std_logic := '1';
  signal done  : boolean := false;

  signal fl_cs_n, fl_sck, fl_mosi : std_logic;
  signal fl_miso : std_logic := '0';

  signal eth_clk  : std_logic;
  signal eth_cs   : std_logic_vector(1 downto 0);
  signal eth_mosi : std_logic;
  signal eth_miso : std_logic := '0';

  signal gpio_do  : std_logic_vector(2 downto 0);
  signal uart0_tx : std_logic;

  signal shar_out : std_logic_vector(47 downto 0);
  signal sipr_out : std_logic_vector(31 downto 0);
  signal sock0_tx_bytes : std_logic_vector(191 downto 0);
  signal sent : std_logic;

  -- Expected wire-format 24-byte result struct (coremark_result.h /
  -- eth_report.c's send_once, little-endian per field):
  --   magic=CMK_MAGIC (0x4B4D434A), git_rev=build's GIT_REV (verified
  --   separately, not byte-compared -- it's the git short hash, not a fixed
  --   constant), crc=0xABCD, _pad=0, iterations=1000, cycles=(observed, not
  --   fixed -- cyccnt delta of the busy-wait loop), clk_hz=CMK_CLK_HZ
  --   (12000000 = 0x00B71B00).
  constant EXP_MAGIC : std_logic_vector(31 downto 0) := x"4A434D4B"; -- LE(0x4B4D434A)
  constant EXP_CRC   : std_logic_vector(15 downto 0) := x"CDAB";     -- LE(0xABCD)
  constant EXP_PAD   : std_logic_vector(15 downto 0) := x"0000";
  constant EXP_ITER  : std_logic_vector(31 downto 0) := x"E8030000"; -- LE(1000)
  -- clk_hz field bytes in send order are LE(12000000) = 00,1B,B7,00; read as
  -- the sock0_tx_bytes(31 downto 0) slice (byte20 in the MSB position) that is
  -- 0x001BB700.
  constant EXP_CLKHZ : std_logic_vector(31 downto 0) := x"001BB700";

  -- byte k of sock0_tx_bytes (0 = first byte sent) is bits (191-8k downto 184-8k)
  function byte_at(v : std_logic_vector(191 downto 0); k : integer) return std_logic_vector is
  begin
    return v(191 - k*8 downto 184 - k*8);
  end function;

  -- shared Fast-Read (0x0B) SPI-flash slave model, adapted from
  -- cpus_coremark_boot_tb.vhd's flash_slave to stream flash_image_pkg bytes.
  procedure flash_slave(
    signal cs_n  : in  std_logic;
    signal sck   : in  std_logic;
    signal mosi  : in  std_logic;
    signal miso  : out std_logic) is
    variable cmd_addr   : std_logic_vector(31 downto 0);
    variable addr       : natural;
    variable byte_val    : std_logic_vector(7 downto 0);
  begin
    wait until cs_n = '0';

    cmd_addr := (others => '0');
    for k in 0 to 31 loop
      wait until rising_edge(sck);
      cmd_addr := cmd_addr(30 downto 0) & mosi;
    end loop;

    for k in 0 to 7 loop
      wait until rising_edge(sck);
    end loop;

    addr := to_integer(unsigned(cmd_addr(23 downto 0))) - to_integer(unsigned(FLASH_BASE));

    for i in addr to FLASH_IMAGE_BYTES - 1 loop
      byte_val := FLASH_IMAGE(i);
      for k in 7 downto 0 loop
        wait until falling_edge(sck);
        miso <= byte_val(k);
      end loop;
      exit when cs_n = '1';
    end loop;
  end procedure;

begin
  uut : entity work.soc(impl)
    port map (
      clk_sys  => clk,
      eth_clk  => eth_clk,
      eth_cs   => eth_cs,
      eth_miso => eth_miso,
      eth_mosi => eth_mosi,
      fl_cs_n  => fl_cs_n,
      fl_miso  => fl_miso,
      fl_mosi  => fl_mosi,
      fl_sck   => fl_sck,
      gpio_do  => gpio_do,
      reset    => reset,
      uart0_rx => '1',
      uart0_tx => uart0_tx
    );

  clk <= not clk after CLK_PER/2 when not done else '0';

  flash_model : process
  begin
    flash_slave(fl_cs_n, fl_sck, fl_mosi, fl_miso);
    wait;
  end process;

  w5500 : entity work.w5500_model(sim)
    port map (
      clk            => clk,
      spi_sclk       => eth_clk,
      spi_mosi       => eth_mosi,
      spi_miso       => eth_miso,
      spi_cs         => eth_cs(0),
      shar_out       => shar_out,
      sipr_out       => sipr_out,
      sock0_tx_bytes => sock0_tx_bytes,
      sent           => sent
    );

  stim : process begin
    reset <= '1';
    wait for CLK_PER * 4;
    wait until rising_edge(clk);
    reset <= '0';
    wait;
  end process;

  -- Wait for the W5500 model's SEND pulse, then check the captured 24 bytes
  -- against the fields we can predict at build time (magic/crc/_pad/
  -- iterations/clk_hz). git_rev and cycles are runtime-dependent (git_rev is
  -- the build's short hash baked in by the Makefile; cycles is the observed
  -- cyccnt delta of the busy-wait loop) so those are reported, not
  -- byte-compared against a fixed constant.
  check : process
    variable ok : boolean := true;
  begin
    wait until sent = '1';

    report "coremark_cosim_tb: captured bytes 0..23:" severity note;
    for k in 0 to 23 loop
      report "  byte(" & integer'image(k) & ") = " &
             integer'image(to_integer(unsigned(byte_at(sock0_tx_bytes, k))))
        severity note;
    end loop;

    if sock0_tx_bytes(191 downto 160) /= EXP_MAGIC then
      ok := false;
      report "Test Failed: magic mismatch" severity error;
    end if;
    if sock0_tx_bytes(127 downto 112) /= EXP_CRC then
      ok := false;
      report "Test Failed: crc mismatch" severity error;
    end if;
    if sock0_tx_bytes(111 downto 96) /= EXP_PAD then
      ok := false;
      report "Test Failed: _pad mismatch" severity error;
    end if;
    if sock0_tx_bytes(95 downto 64) /= EXP_ITER then
      ok := false;
      report "Test Failed: iterations mismatch" severity error;
    end if;
    if sock0_tx_bytes(31 downto 0) /= EXP_CLKHZ then
      ok := false;
      report "Test Failed: clk_hz mismatch" severity error;
    end if;
    if unsigned(sock0_tx_bytes(63 downto 32)) = 0 then
      ok := false;
      report "Test Failed: cycles field is zero (cycle counter not working)" severity error;
    end if;

    if ok then
      report "Test Passed" severity note;
    else
      assert false report "Test Failed" severity failure;
    end if;
    done <= true;
    wait;
  end process;

  -- Diagnostics: observe flash-boot completion (fl_cs_n rising after the
  -- streaming burst) and count W5500 SPI chip-selects so a timeout report can
  -- distinguish "CPU never booted" from "CPU booted but never drove the eth".
  diag_boot : process begin
    wait until fl_cs_n = '1' and now > 1 us;
    report "diag: flash-boot burst complete (fl_cs_n rose) at " & time'image(now) severity note;
    wait;
  end process;

  diag_eth : process
    variable eth_frames : natural := 0;
  begin
    loop
      wait until falling_edge(eth_cs(0));
      eth_frames := eth_frames + 1;
      if eth_frames <= 6 or (eth_frames mod 20) = 0 then
        report "diag: eth SPI frame #" & integer'image(eth_frames) & " at " & time'image(now) severity note;
      end if;
    end loop;
  end process;

  watchdog : process begin
    wait for 100 ms;
    assert done report "Test Failed: TIMEOUT waiting for W5500 SEND" severity failure;
    wait;
  end process;

end architecture;
