package emit

// fileBanner is the generated-file header prepended to every emitted VHDL file,
// byte-identical to the Clojure soc_gen hdr-comment block. `library` follows it
// directly (no blank line), matching the golden.
const fileBanner = "" +
	"-- ******************************************************************\n" +
	"-- ******************************************************************\n" +
	"-- ******************************************************************\n" +
	"-- This file is generated by soc_gen and will be overwritten next time\n" +
	"-- the tool is run. See soc_top/README for information on running soc_gen.\n" +
	"-- ******************************************************************\n" +
	"-- ******************************************************************\n" +
	"-- ******************************************************************\n"

// withBanner prepends the generated-file banner to a printed VHDL string.
func withBanner(s string) string { return fileBanner + s }
