// This file is generated by soc_gen and will be overwritten next time
// the tool is run. See soc_top/README for information on running soc_gen.

#ifndef BOARD_H
#define BOARD_H
#include <inttypes.h>

#define DRAM_BASE 0x10000000

// Memory mapped peripherals
#define DEVICE_CYCCNT_ADDR 0xabcd0200
#define DEVICE_ETH_ADDR    0xabcd1000
#define DEVICE_GPIO0_ADDR  0xabcd0000
#define DEVICE_UART0_ADDR  0xabcd0100

struct cycle_counter_regs {
  uint32_t count; // read-only only byte 0
};
#define DEVICE_CYCCNT ((volatile struct cycle_counter_regs *) DEVICE_CYCCNT_ADDR)

struct aic_regs {
  uint32_t ctrl0;
  uint32_t brkadd;
  uint32_t ilevels;
  uint32_t ctrl1;
  uint32_t pit_throttle;
  uint32_t pit_counter;
  uint32_t clock_period; // read-only
  uint32_t ignore0;
  uint32_t rtc_sec_hi;
  uint32_t rtc_sec_lo;
  uint32_t rtc_nsec;
};
#define DEVICE_AIC0 ((volatile struct aic_regs *) DEVICE_AIC0_ADDR)

struct gpio2_regs {
  uint32_t value;
  uint32_t in_out;
  uint32_t toggle;
};
#define DEVICE_GPIO0 ((volatile struct gpio2_regs *) DEVICE_GPIO0_ADDR)
#define DEVICE_I2C ((volatile struct gpio2_regs *) DEVICE_I2C_ADDR)

struct spi_regs {
  uint32_t ctrl; // only byte 3
  uint32_t data; // only byte 3
};
#define DEVICE_ETH ((volatile struct spi_regs *) DEVICE_ETH_ADDR)

struct uartlite_regs {
  uint32_t rx; // only byte 3
  uint32_t tx; // only byte 3
  uint32_t status; // only byte 3
  uint32_t ctrl; // only byte 3
};
#define DEVICE_UART0 ((volatile struct uartlite_regs *) DEVICE_UART0_ADDR)


#endif
