// This file is generated by soc_gen and will be overwritten next time
// the tool is run. See soc_top/README for information on running soc_gen.

#ifndef BOARD_H
#define BOARD_H
#include <inttypes.h>

#define DRAM_BASE 0x10000000

// Memory mapped peripherals
#define DEVICE_ETH0_ADDR  0xabcd1000
#define DEVICE_GPIO0_ADDR 0xabcd0000
#define DEVICE_UART0_ADDR 0xabcd0100

struct eth_tx_regs {
  uint32_t ignore0[512];
  uint32_t tx_data;
  uint32_t tx_rstptr;
  uint32_t tx_len;
  uint32_t tx_go;
  uint32_t tx_status; // read-only
};
#define DEVICE_ETH0 ((volatile struct eth_tx_regs *) DEVICE_ETH0_ADDR)

struct gpio2_regs {
  uint32_t value;
  uint32_t in_out;
  uint32_t toggle;
};
#define DEVICE_GPIO0 ((volatile struct gpio2_regs *) DEVICE_GPIO0_ADDR)

struct uartlite_regs {
  uint32_t rx; // only byte 3
  uint32_t tx; // only byte 3
  uint32_t status; // only byte 3
  uint32_t ctrl; // only byte 3
};
#define DEVICE_UART0 ((volatile struct uartlite_regs *) DEVICE_UART0_ADDR)


#endif
