-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
use work.data_bus_pack.all;
entity devices is
    port (
        clk_sys : in std_logic;
        cpu0_periph_dbus_i : out cpu_data_i_t;
        cpu0_periph_dbus_o : in cpu_data_o_t;
        cpu1_periph_dbus_i : out cpu_data_i_t;
        cpu1_periph_dbus_o : in cpu_data_o_t;
        gpio_do : out std_logic_vector(31 downto 0);
        reset : in std_logic;
        uart0_rx : in std_logic;
        uart0_tx : out std_logic
    );
end;
architecture impl of devices is
    signal gpio_di : std_logic_vector(31 downto 0);
    signal cpu01_periph_dbus_i : cpu_data_i_t;
    signal cpu01_periph_dbus_o : cpu_data_o_t;
    type device_t is (NONE, DEV_GPIO0, DEV_UART0);
    signal active_dev : device_t;
    type data_bus_i_t is array (device_t'left to device_t'right) of cpu_data_i_t;
    type data_bus_o_t is array (device_t'left to device_t'right) of cpu_data_o_t;
    signal devs_bus_i : data_bus_i_t;
    signal devs_bus_o : data_bus_o_t;
    function decode_address (addr : std_logic_vector(31 downto 0)) return device_t is
    begin
        -- Assumes addr(31 downto 28) = x"a".
        -- Address decoding closer to CPU checks those bits.
        if addr(27 downto 9) = "1011110011010000000" then
            if addr(8 downto 4) = "00000" then
                -- ABCD0000-ABCD000F
                return DEV_GPIO0;
            elsif addr(8 downto 4) = "10000" then
                -- ABCD0100-ABCD010F
                return DEV_UART0;
            end if;
        end if;
        return NONE;
    end;
begin
    cpus_mux : entity work.multi_master_bus_mux
        port map (
            clk => clk_sys,
            rst => reset,
            m1_i => cpu0_periph_dbus_i,
            m1_o => cpu0_periph_dbus_o,
            m2_i => cpu1_periph_dbus_i,
            m2_o => cpu1_periph_dbus_o,
            slave_i => cpu01_periph_dbus_i,
            slave_o => cpu01_periph_dbus_o
        );
    -- multiplex data bus to and from devices
    active_dev <= decode_address(cpu01_periph_dbus_o.a);
    cpu01_periph_dbus_i <= devs_bus_i(active_dev);
    bus_split : for dev in device_t'left to device_t'right generate
        devs_bus_o(dev) <= mask_data_o(cpu01_periph_dbus_o, to_bit(dev = active_dev));
    end generate;
    devs_bus_i(NONE) <= loopback_bus(devs_bus_o(NONE));
    -- Instantiate devices
    gpio0 : entity work.gpio2(arch)
        port map (
            clk => clk_sys,
            d_i => gpio_di,
            d_o => gpio_do,
            d_t => open,
            db_i => devs_bus_o(DEV_GPIO0),
            db_o => devs_bus_i(DEV_GPIO0),
            irq => open,
            rst => reset
        );
    uart0 : entity work.uartlitedb(arch)
        generic map (
            fclk => CFG_CLK_CPU_FREQ_HZ,
            rx_fifo_len => 2,
            tx_fifo_len => 2
        )
        port map (
            clk => clk_sys,
            db_i => devs_bus_o(DEV_UART0),
            db_o => devs_bus_i(DEV_UART0),
            int => open,
            rst => reset,
            rx => uart0_rx,
            tx => uart0_tx
        );
end;
