-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
use work.data_bus_pack.all;
entity devices is
    port (
        clk_sys : in std_logic;
        cpu0_data_master_ack : in std_logic;
        cpu0_data_master_en : in std_logic;
        cpu0_event_i : out cpu_event_i_t;
        cpu0_event_o : in cpu_event_o_t;
        cpu0_periph_dbus_i : out cpu_data_i_t;
        cpu0_periph_dbus_o : in cpu_data_o_t;
        cpu1_periph_dbus_i : out cpu_data_i_t;
        cpu1_periph_dbus_o : in cpu_data_o_t;
        eth_clk : out std_logic;
        eth_cs : out std_logic_vector(1 downto 0);
        eth_irq_vec : in std_logic_vector(7 downto 0);
        eth_miso : in std_logic;
        eth_mosi : out std_logic;
        gpio_do : out std_logic_vector(2 downto 0);
        i2c_di : in std_logic_vector(1 downto 0);
        i2c_do : out std_logic_vector(1 downto 0);
        i2c_dt : out std_logic_vector(1 downto 0);
        reset : in std_logic;
        uart0_rx : in std_logic;
        uart0_tx : out std_logic
    );
end;
architecture impl of devices is
    signal gpio_di : std_logic_vector(2 downto 0);
    type device_t is (NONE, DEV_CYCCNT, DEV_ETH, DEV_GPIO0, DEV_UART0);
    signal active_dev : device_t;
    type data_bus_i_t is array (device_t'left to device_t'right) of cpu_data_i_t;
    type data_bus_o_t is array (device_t'left to device_t'right) of cpu_data_o_t;
    signal devs_bus_i : data_bus_i_t;
    signal devs_bus_o : data_bus_o_t;
    function decode_address (addr : std_logic_vector(31 downto 0)) return device_t is
    begin
        -- Assumes addr(31 downto 28) = x"a".
        -- Address decoding closer to CPU checks those bits.
        if addr(27 downto 13) = "101111001101000" then
            if addr(12 downto 10) = "000" then
                if addr(9) = '0' then
                    if addr(8 downto 4) = "00000" then
                        -- ABCD0000-ABCD000F
                        return DEV_GPIO0;
                    elsif addr(8 downto 4) = "10000" then
                        -- ABCD0100-ABCD010F
                        return DEV_UART0;
                    end if;
                elsif addr(9 downto 3) = "1000000" then
                    -- ABCD0200-ABCD0207
                    return DEV_CYCCNT;
                end if;
            elsif addr(12 downto 3) = "1000000000" then
                -- ABCD1000-ABCD1007
                return DEV_ETH;
            end if;
        end if;
        return NONE;
    end;
    signal irqs0 : std_logic_vector(7 downto 0) := (others => '0');
begin
    -- Disconnected peripheral buses
    cpu1_periph_dbus_i <= loopback_bus(cpu1_periph_dbus_o);
    -- multiplex data bus to and from devices
    active_dev <= decode_address(cpu0_periph_dbus_o.a);
    cpu0_periph_dbus_i <= devs_bus_i(active_dev);
    bus_split : for dev in device_t'left to device_t'right generate
        devs_bus_o(dev) <= mask_data_o(cpu0_periph_dbus_o, to_bit(dev = active_dev));
    end generate;
    devs_bus_i(NONE) <= loopback_bus(devs_bus_o(NONE));
    -- Instantiate devices
    cyccnt : entity work.cycle_counter(rtl)
        port map (
            clk => clk_sys,
            db_i => devs_bus_o(DEV_CYCCNT),
            db_o => devs_bus_i(DEV_CYCCNT),
            rst => reset
        );
    eth : entity work.spi2(arch)
        generic map (
            clk_freq => CFG_CLK_CPU_FREQ_HZ,
            num_cs => 2
        )
        port map (
            busy => open,
            clk => clk_sys,
            cpha => '0',
            cpol => '0',
            cs => eth_cs,
            db_i => devs_bus_o(DEV_ETH),
            db_o => devs_bus_i(DEV_ETH),
            miso => eth_miso,
            mosi => eth_mosi,
            rst => reset,
            spi_clk => eth_clk
        );
    gpio0 : entity work.gpio2(arch)
        generic map (
            width => 3
        )
        port map (
            clk => clk_sys,
            d_i => gpio_di,
            d_o => gpio_do,
            d_t => open,
            db_i => devs_bus_o(DEV_GPIO0),
            db_o => devs_bus_i(DEV_GPIO0),
            irq => open,
            rst => reset
        );
    i2c : entity work.gpio2(arch)
        generic map (
            width => 2
        )
        port map (
            clk => clk_sys,
            d_i => i2c_di,
            d_o => i2c_do,
            d_t => i2c_dt,
            db_i => devs_bus_o(DEV_I2C),
            db_o => devs_bus_i(DEV_I2C),
            irq => open,
            rst => reset
        );
    uart0 : entity work.uartlitedb(arch)
        generic map (
            fclk => CFG_CLK_CPU_FREQ_HZ,
            rx_enable => FALSE,
            rx_fifo_len => 1,
            tx_fifo_len => 1
        )
        port map (
            clk => clk_sys,
            db_i => devs_bus_o(DEV_UART0),
            db_o => devs_bus_i(DEV_UART0),
            int => open,
            rst => reset,
            rx => uart0_rx,
            tx => uart0_tx
        );
end;
