-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
entity pad_ring is
    port (
        pin_clk : in std_logic;
        pin_ledb_n : out std_logic;
        pin_ledg_n : out std_logic;
        pin_ledr_n : out std_logic;
        pin_ser_rx : in std_logic;
        pin_ser_tx : out std_logic;
        pin_w5500_cs : out std_logic;
        pin_w5500_miso : in std_logic;
        pin_w5500_mosi : out std_logic;
        pin_w5500_sclk : out std_logic
    );
end;
architecture impl of pad_ring is
    signal clk : std_logic;
    signal clk_sys : std_logic;
    signal eth_clk : std_logic;
    signal eth_cs : std_logic_vector(1 downto 0);
    signal eth_miso : std_logic;
    signal eth_mosi : std_logic;
    signal gpio_do : std_logic_vector(2 downto 0);
    signal reset : std_logic;
    signal uart0_rx : std_logic;
    signal uart0_tx : std_logic;
begin
    soc : entity work.soc(impl)
        port map (
            clk_sys => clk_sys,
            eth_clk => eth_clk,
            eth_cs => eth_cs,
            eth_miso => eth_miso,
            eth_mosi => eth_mosi,
            gpio_do => gpio_do,
            reset => reset,
            uart0_rx => uart0_rx,
            uart0_tx => uart0_tx
        );
    clkgen : entity work.ice_clkgen(rtl)
        port map (
            clk_eth => open,
            clk_in => clk,
            clk_out => clk_sys,
            rst_out => reset
        );
    clk <= pin_clk;
    pin_ledb_n <= not gpio_do(2);
    pin_ledg_n <= not gpio_do(1);
    pin_ledr_n <= not gpio_do(0);
    uart0_rx <= pin_ser_rx;
    pin_ser_tx <= uart0_tx;
    pin_w5500_cs <= eth_cs(0);
    eth_miso <= pin_w5500_miso;
    pin_w5500_mosi <= eth_mosi;
    pin_w5500_sclk <= eth_clk;
end;
