-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
entity soc is
    port (
        clk_sys : in std_logic;
        gpio_do : out std_logic_vector(31 downto 0);
        reset : in std_logic;
        uart0_rx : in std_logic;
        uart0_tx : out std_logic
    );
end;
architecture impl of soc is
    signal cpu0_ddr_dbus_i : cpu_data_i_t;
    signal cpu0_ddr_ibus_i : cpu_instruction_i_t;
    signal cpu0_event_i : cpu_event_i_t;
    signal cpu0_periph_dbus_i : cpu_data_i_t;
    signal cpu0_periph_dbus_o : cpu_data_o_t;
    signal cpu1_ddr_dbus_i : cpu_data_i_t;
    signal cpu1_ddr_ibus_i : cpu_instruction_i_t;
    signal cpu1_event_i : cpu_event_i_t;
    signal cpu1_periph_dbus_i : cpu_data_i_t;
    signal cpu1_periph_dbus_o : cpu_data_o_t;
    signal debug_i : cpu_debug_i_t;
begin
    cpus : configuration work.soc_cpus_config
        generic map (
            insert_inst_delay_boot_mem => FALSE,
            insert_read_delay_boot_mem => FALSE,
            insert_write_delay_boot_mem => FALSE
        )
        port map (
            clk => clk_sys,
            cpu0_copro_i => NULL_COPR_I,
            cpu0_copro_o => open,
            cpu0_data_master_ack => open,
            cpu0_data_master_en => open,
            cpu0_ddr_dbus_i => cpu0_ddr_dbus_i,
            cpu0_ddr_dbus_o => open,
            cpu0_ddr_ibus_i => cpu0_ddr_ibus_i,
            cpu0_ddr_ibus_o => open,
            cpu0_event_i => cpu0_event_i,
            cpu0_event_o => open,
            cpu0_mem_lock => open,
            cpu0_periph_dbus_i => cpu0_periph_dbus_i,
            cpu0_periph_dbus_o => cpu0_periph_dbus_o,
            cpu1_copro_i => NULL_COPR_I,
            cpu1_copro_o => open,
            cpu1_data_master_ack => open,
            cpu1_data_master_en => open,
            cpu1_ddr_dbus_i => cpu1_ddr_dbus_i,
            cpu1_ddr_dbus_o => open,
            cpu1_ddr_ibus_i => cpu1_ddr_ibus_i,
            cpu1_ddr_ibus_o => open,
            cpu1_event_i => cpu1_event_i,
            cpu1_event_o => open,
            cpu1_mem_lock => open,
            cpu1_periph_dbus_i => cpu1_periph_dbus_i,
            cpu1_periph_dbus_o => cpu1_periph_dbus_o,
            cpu1eni => '0',
            debug_i => debug_i,
            debug_o => open,
            rst => reset
        );
    devices : entity work.devices(impl)
        port map (
            clk_sys => clk_sys,
            cpu0_periph_dbus_i => cpu0_periph_dbus_i,
            cpu0_periph_dbus_o => cpu0_periph_dbus_o,
            cpu1_periph_dbus_i => cpu1_periph_dbus_i,
            cpu1_periph_dbus_o => cpu1_periph_dbus_o,
            gpio_do => gpio_do,
            reset => reset,
            uart0_rx => uart0_rx,
            uart0_tx => uart0_tx
        );
end;
