-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
entity soc is
    port (
        clk_sys : in std_logic;
        eth_clk : out std_logic;
        eth_cs : out std_logic_vector(1 downto 0);
        eth_irq_vec : in std_logic_vector(7 downto 0);
        eth_miso : in std_logic;
        eth_mosi : out std_logic;
        fl_cs_n : out std_logic;
        fl_miso : in std_logic;
        fl_mosi : out std_logic;
        fl_sck : out std_logic;
        gpio_do : out std_logic_vector(2 downto 0);
        i2c_di : in std_logic_vector(1 downto 0);
        i2c_do : out std_logic_vector(1 downto 0);
        i2c_dt : out std_logic_vector(1 downto 0);
        reset : in std_logic;
        uart0_rx : in std_logic;
        uart0_tx : out std_logic
    );
end;
architecture impl of soc is
    signal cpu0_data_master_ack : std_logic;
    signal cpu0_data_master_en : std_logic;
    signal cpu0_ddr_dbus_i : cpu_data_i_t;
    signal cpu0_ddr_ibus_i : cpu_instruction_i_t;
    signal cpu0_event_i : cpu_event_i_t;
    signal cpu0_event_o : cpu_event_o_t;
    signal cpu0_periph_dbus_i : cpu_data_i_t;
    signal cpu0_periph_dbus_o : cpu_data_o_t;
    signal cpu1_ddr_dbus_i : cpu_data_i_t;
    signal cpu1_ddr_ibus_i : cpu_instruction_i_t;
    signal cpu1_event_i : cpu_event_i_t;
    signal cpu1_periph_dbus_i : cpu_data_i_t;
    signal cpu1_periph_dbus_o : cpu_data_o_t;
    signal debug_i : cpu_debug_i_t;
begin
    cpus : configuration work.soc_cpus_config
        generic map (
            insert_inst_delay_boot_mem => FALSE,
            insert_read_delay_boot_mem => FALSE,
            insert_write_delay_boot_mem => FALSE
        )
        port map (
            clk => clk_sys,
            cpu0_copro_i => NULL_COPR_I,
            cpu0_copro_o => open,
            cpu0_data_master_ack => cpu0_data_master_ack,
            cpu0_data_master_en => cpu0_data_master_en,
            cpu0_ddr_dbus_i => cpu0_ddr_dbus_i,
            cpu0_ddr_dbus_o => open,
            cpu0_ddr_ibus_i => cpu0_ddr_ibus_i,
            cpu0_ddr_ibus_o => open,
            cpu0_event_i => cpu0_event_i,
            cpu0_event_o => cpu0_event_o,
            cpu0_mem_lock => open,
            cpu0_periph_dbus_i => cpu0_periph_dbus_i,
            cpu0_periph_dbus_o => cpu0_periph_dbus_o,
            cpu1_copro_i => NULL_COPR_I,
            cpu1_copro_o => open,
            cpu1_data_master_ack => open,
            cpu1_data_master_en => open,
            cpu1_ddr_dbus_i => cpu1_ddr_dbus_i,
            cpu1_ddr_dbus_o => open,
            cpu1_ddr_ibus_i => cpu1_ddr_ibus_i,
            cpu1_ddr_ibus_o => open,
            cpu1_event_i => cpu1_event_i,
            cpu1_event_o => open,
            cpu1_mem_lock => open,
            cpu1_periph_dbus_i => cpu1_periph_dbus_i,
            cpu1_periph_dbus_o => cpu1_periph_dbus_o,
            cpu1eni => '0',
            debug_i => debug_i,
            debug_o => open,
            fl_cs_n => fl_cs_n,
            fl_miso => fl_miso,
            fl_mosi => fl_mosi,
            fl_sck => fl_sck,
            rst => reset
        );
    devices : entity work.devices(impl)
        port map (
            clk_sys => clk_sys,
            cpu0_data_master_ack => cpu0_data_master_ack,
            cpu0_data_master_en => cpu0_data_master_en,
            cpu0_event_i => cpu0_event_i,
            cpu0_event_o => cpu0_event_o,
            cpu0_periph_dbus_i => cpu0_periph_dbus_i,
            cpu0_periph_dbus_o => cpu0_periph_dbus_o,
            cpu1_periph_dbus_i => cpu1_periph_dbus_i,
            cpu1_periph_dbus_o => cpu1_periph_dbus_o,
            eth_clk => eth_clk,
            eth_cs => eth_cs,
            eth_irq_vec => eth_irq_vec,
            eth_miso => eth_miso,
            eth_mosi => eth_mosi,
            gpio_do => gpio_do,
            i2c_di => i2c_di,
            i2c_do => i2c_do,
            i2c_dt => i2c_dt,
            reset => reset,
            uart0_rx => uart0_rx,
            uart0_tx => uart0_tx
        );
    -- Zero out unused signals
    cpu1_event_i <= (en => '0', cmd => INTERRUPT, vec => (others => '0'), msk => '0', lvl => (others => '0'));
end;
