package generate

import "strings"

// buildMK renders build.mk: a fixed two-line header followed by one
// `$(VHDLS) += <name>` line per InBuildMK file, in slice order. Byte-exact with
// the Clojure soc_gen build.mk.
func buildMK(files []File) string {
	var b strings.Builder
	b.WriteString("# This file is generated by soc_gen and will be overwritten next time\n")
	b.WriteString("# the tool is run. See soc_top/README for information on running soc_gen.\n")
	for _, f := range files {
		if f.InBuildMK {
			b.WriteString("$(VHDLS) += " + f.Name + "\n")
		}
	}
	return b.String()
}
