package generate

import "strings"

// buildMK renders build.mk: a fixed two-line header, one `$(VHDLS) += <name>`
// line per InBuildMK file (in slice order), and finally a `CPU_VARIANT :=`
// line carrying the board's architectural CPU variant (j1/j2/j4) from
// design.yaml's `model:` key. cpuVariant is empty for boards with no `cpu:`
// block (legacy/unmigrated boards); in that case the line is omitted entirely
// rather than emitted as `CPU_VARIANT := ` — an empty value could be
// misread by a later consumer as "cpu variant is the empty string" rather than
// "not applicable". The line comes after the $(VHDLS) lines: it is metadata
// about the board, not a generated file entry, so it reads as a trailer
// rather than being interleaved with the file list. Byte-exact with the
// Clojure soc_gen build.mk except for this addition.
func buildMK(files []File, cpuVariant string) string {
	var b strings.Builder
	b.WriteString("# This file is generated by soc_gen and will be overwritten next time\n")
	b.WriteString("# the tool is run. See soc_top/README for information on running soc_gen.\n")
	for _, f := range files {
		if f.InBuildMK {
			b.WriteString("$(VHDLS) += " + f.Name + "\n")
		}
	}
	if cpuVariant != "" {
		// The top-level Makefile reads this to pick the variant's file list
		// (components/cpu/Makefile.inc). design.yaml stays the single source
		// of truth; Make never parses YAML.
		b.WriteString("CPU_VARIANT := " + cpuVariant + "\n")
	}
	return b.String()
}
