package generate

import "testing"

func TestBuildMK(t *testing.T) {
	files := []File{
		{Name: "devices.vhd", Content: "x", InBuildMK: true},
		{Name: "soc.vhd", Content: "x", InBuildMK: true},
		{Name: "pad_ring.vhd", Content: "x", InBuildMK: true},
		{Name: "board.dts", Content: "x", InBuildMK: false},
		{Name: "board.h", Content: "x", InBuildMK: false},
	}
	want := "# This file is generated by soc_gen and will be overwritten next time\n" +
		"# the tool is run. See soc_top/README for information on running soc_gen.\n" +
		"$(VHDLS) += devices.vhd\n" +
		"$(VHDLS) += soc.vhd\n" +
		"$(VHDLS) += pad_ring.vhd\n"
	if got := buildMK(files); got != want {
		t.Errorf("buildMK mismatch:\n got %q\nwant %q", got, want)
	}
}
