package generate

import (
	"strings"
	"testing"
)

func TestBuildMK(t *testing.T) {
	files := []File{
		{Name: "devices.vhd", Content: "x", InBuildMK: true},
		{Name: "soc.vhd", Content: "x", InBuildMK: true},
		{Name: "pad_ring.vhd", Content: "x", InBuildMK: true},
		{Name: "board.dts", Content: "x", InBuildMK: false},
		{Name: "board.h", Content: "x", InBuildMK: false},
	}
	want := "# This file is generated by soc_gen and will be overwritten next time\n" +
		"# the tool is run. See soc_top/README for information on running soc_gen.\n" +
		"$(VHDLS) += devices.vhd\n" +
		"$(VHDLS) += soc.vhd\n" +
		"$(VHDLS) += pad_ring.vhd\n"
	if got := buildMK(files, ""); got != want {
		t.Errorf("buildMK mismatch:\n got %q\nwant %q", got, want)
	}
}

// TestBuildMKCPUVariant asserts CPU_VARIANT is appended after the $(VHDLS)
// lines when a variant is given, and omitted entirely (not emitted empty)
// when it is not.
func TestBuildMKCPUVariant(t *testing.T) {
	files := []File{
		{Name: "devices.vhd", Content: "x", InBuildMK: true},
	}
	want := "# This file is generated by soc_gen and will be overwritten next time\n" +
		"# the tool is run. See soc_top/README for information on running soc_gen.\n" +
		"$(VHDLS) += devices.vhd\n" +
		"CPU_VARIANT := j4\n"
	if got := buildMK(files, "j4"); got != want {
		t.Errorf("buildMK with variant mismatch:\n got %q\nwant %q", got, want)
	}

	noVariant := buildMK(files, "")
	if strings.Contains(noVariant, "CPU_VARIANT") {
		t.Errorf("buildMK with empty variant should omit CPU_VARIANT line, got:\n%s", noVariant)
	}
}
