package generate

import (
	"errors"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/j-core/jcore-soc/tools/socgen/board"
	"github.com/j-core/jcore-soc/tools/socgen/cheader"
	"github.com/j-core/jcore-soc/tools/socgen/design"
	"github.com/j-core/jcore-soc/tools/socgen/devicetree"
	"github.com/j-core/jcore-soc/tools/socgen/elaborate"
	"github.com/j-core/jcore-soc/tools/socgen/emit"
	"github.com/j-core/jcore-soc/tools/socgen/iface"
	"github.com/j-core/jcore-soc/tools/socgen/vhdl"
)

// minimalRes is a Resolution rich enough that the emitters return without
// panicking (empty device/signal sets -> minimal but valid VHDL).
func minimalRes() *elaborate.Resolution {
	return &elaborate.Resolution{}
}

// minimalLib returns an iface.Library with a cfg_clk_cpu_period_ns constant
// (20 ns -> 50 MHz). Required because devicetree.BoardDTS calls cpuFreq(b.Library)
// which returns an error when the constant is absent, causing Build to fail even
// in the best-effort path.
func minimalLib() *iface.Library {
	return &iface.Library{
		Entities: map[string]*iface.Entity{},
		Packages: map[string]*iface.Package{
			"cfg": {
				Name: "cfg",
				Constants: []*iface.Constant{
					{
						Name:  "CFG_CLK_CPU_PERIOD_NS",
						Value: &vhdl.BasicLit{Kind: vhdl.INT, Value: "20"},
					},
				},
			},
		},
		Architectures:  map[string][]*iface.Architecture{},
		Configurations: map[string]*iface.Configuration{},
	}
}

func boardWith(plugins []string) *board.Board {
	return &board.Board{
		Name:    "synthetic",
		Design:  &design.Design{Plugins: plugins},
		Library: minimalLib(),
	}
}

func names(files []File) map[string]bool {
	m := make(map[string]bool, len(files))
	for _, f := range files {
		m[f.Name] = true
	}
	return m
}

func TestBuildSelectsBoardHOnly(t *testing.T) {
	files, err := Build(boardWith([]string{"board.h"}), minimalRes())
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	n := names(files)
	if !n["board.h"] {
		t.Errorf("expected board.h in file set: %v", n)
	}
	if n["board.dts"] {
		t.Errorf("did not expect board.dts when device_tree absent: %v", n)
	}
	for _, core := range []string{"devices.vhd", "soc.vhd", "pad_ring.vhd", "build.mk"} {
		if !n[core] {
			t.Errorf("missing core file %q: %v", core, n)
		}
	}
}

func TestBuildSelectsDeviceTreeOnly(t *testing.T) {
	files, err := Build(boardWith([]string{"device_tree"}), minimalRes())
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	n := names(files)
	if !n["board.dts"] {
		t.Errorf("expected board.dts: %v", n)
	}
	if n["board.h"] {
		t.Errorf("did not expect board.h when board.h plugin absent: %v", n)
	}
}

func TestBuildDuplicatePlugin(t *testing.T) {
	_, err := Build(boardWith([]string{"board.h", "board.h"}), minimalRes())
	if !errors.Is(err, ErrDuplicatePlugin) {
		t.Errorf("expected ErrDuplicatePlugin, got %v", err)
	}
}

func TestBuildUnknownPlugin(t *testing.T) {
	_, err := Build(boardWith([]string{"bogus"}), minimalRes())
	if !errors.Is(err, ErrUnknownPlugin) {
		t.Errorf("expected ErrUnknownPlugin, got %v", err)
	}
}

func TestBuildMKListsOnlyVHDL(t *testing.T) {
	files, err := Build(boardWith([]string{"device_tree", "board.h"}), minimalRes())
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	var mk string
	for _, f := range files {
		if f.Name == "build.mk" {
			mk = f.Content
		}
	}
	want := "# This file is generated by soc_gen and will be overwritten next time\n" +
		"# the tool is run. See soc_top/README for information on running soc_gen.\n" +
		"$(VHDLS) += devices.vhd\n$(VHDLS) += soc.vhd\n$(VHDLS) += pad_ring.vhd\n"
	if mk != want {
		t.Errorf("build.mk content:\n got %q\nwant %q", mk, want)
	}
	if last := files[len(files)-1].Name; last != "build.mk" {
		t.Errorf("build.mk should be appended last, got last file %q", last)
	}
}

func TestBuildMimasV2(t *testing.T) {
	root := os.Getenv("JCORE_SOC_ROOT")
	if root == "" {
		t.Skip("JCORE_SOC_ROOT not set")
	}
	b, lerr := board.Load(root, "mimas_v2")
	if b == nil || b.Design == nil {
		t.Fatalf("board.Load: %v", lerr)
	}
	res, rerr := elaborate.Elaborate(b)
	if rerr != nil {
		t.Logf("elaborate notes: %v", rerr)
	}
	files, err := Build(b, res)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	// 1. file set matches the golden set exactly.
	got := make([]string, 0, len(files))
	byName := map[string]string{}
	for _, f := range files {
		got = append(got, f.Name)
		byName[f.Name] = f.Content
	}
	sort.Strings(got)
	want := []string{"board.dts", "board.h", "build.mk", "devices.vhd", "pad_ring.vhd", "soc.vhd"}
	if len(got) != len(want) {
		t.Fatalf("file set = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("file set[%d] = %q, want %q (full: %v)", i, got[i], want[i], got)
		}
	}

	// 2. build.mk byte-exact vs golden.
	golden, gerr := os.ReadFile(filepath.Join(root, "targets/boards/mimas_v2/build.mk"))
	if gerr != nil {
		t.Fatalf("read golden build.mk: %v", gerr)
	}
	if byName["build.mk"] != string(golden) {
		t.Errorf("build.mk not byte-exact:\n got %q\nwant %q", byName["build.mk"], string(golden))
	}

	// 3. each file equals its direct emitter call (Build = selection + assembly).
	devVHD, _ := emit.Devices(res)
	socVHD, _ := emit.SoC(res)
	padVHD, _ := emit.PadRing(res)
	dts, _ := devicetree.BoardDTS(b, res)
	boardH, _ := cheader.BoardH(res)
	for _, c := range []struct{ name, want string }{
		{"devices.vhd", devVHD}, {"soc.vhd", socVHD}, {"pad_ring.vhd", padVHD},
		{"board.dts", dts}, {"board.h", boardH},
	} {
		if byName[c.name] != c.want {
			t.Errorf("%s content differs from its direct emitter call", c.name)
		}
	}

	// 4. board.h byte-exact vs golden (cheap extra assurance).
	bh, bherr := os.ReadFile(filepath.Join(root, "targets/boards/mimas_v2/board.h"))
	if bherr != nil {
		t.Fatalf("read golden board.h: %v", bherr)
	}
	if byName["board.h"] != string(bh) {
		t.Errorf("board.h not byte-exact vs golden")
	}
}

// TestBuildTurtle locks the turtle file set (which includes the phase-2
// word_ack_gen.vhd) and asserts build.mk stays byte-exact to the golden — i.e.
// word_ack_gen.vhd is emitted but deliberately NOT listed in build.mk (T3).
func TestBuildTurtle(t *testing.T) {
	root := os.Getenv("JCORE_SOC_ROOT")
	if root == "" {
		t.Skip("JCORE_SOC_ROOT not set")
	}
	b, lerr := board.Load(root, "turtle_1v0")
	if b == nil || b.Design == nil {
		t.Fatalf("board.Load: %v", lerr)
	}
	res, rerr := elaborate.Elaborate(b)
	if rerr != nil {
		t.Logf("elaborate notes: %v", rerr)
	}
	files, err := Build(b, res)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	got := make([]string, 0, len(files))
	byName := map[string]string{}
	for _, f := range files {
		got = append(got, f.Name)
		byName[f.Name] = f.Content
	}
	sort.Strings(got)
	// word_ack_gen.vhd is in the file set (it gets written), unlike mimas.
	want := []string{"board.dts", "board.h", "build.mk", "devices.vhd", "pad_ring.vhd", "soc.vhd", "word_ack_gen.vhd"}
	if len(got) != len(want) {
		t.Fatalf("file set = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("file set[%d] = %q, want %q (full: %v)", i, got[i], want[i], got)
		}
	}
	// build.mk byte-exact vs golden — must NOT list word_ack_gen.vhd.
	golden, gerr := os.ReadFile(filepath.Join(root, "targets/boards/turtle_1v0/build.mk"))
	if gerr != nil {
		t.Fatalf("read golden build.mk: %v", gerr)
	}
	if byName["build.mk"] != string(golden) {
		t.Errorf("build.mk not byte-exact:\n got %q\nwant %q", byName["build.mk"], string(golden))
	}
	if strings.Contains(byName["build.mk"], "word_ack_gen") {
		t.Errorf("build.mk must not list word_ack_gen.vhd")
	}
}

// TestBoardDTSTurtleSMP verifies the SMP device-tree structure is emitted for
// turtle (the second CPU + ipi node), gated by the peripheral-buses cpu1 marker
// (T4a). Full byte-parity is asserted by TestBoardDTSTurtleComplete.
func TestBoardDTSTurtleSMP(t *testing.T) {
	root := os.Getenv("JCORE_SOC_ROOT")
	if root == "" {
		t.Skip("JCORE_SOC_ROOT not set")
	}
	b, lerr := board.Load(root, "turtle_1v0")
	if b == nil || b.Design == nil {
		t.Fatalf("board.Load: %v", lerr)
	}
	res, _ := elaborate.Elaborate(b)
	dts, err := devicetree.BoardDTS(b, res)
	if err != nil {
		t.Fatalf("BoardDTS: %v", err)
	}
	for _, frag := range []string{"cpu@1 {", `enable-method = "jcore,spin-table";`, "ipi {"} {
		if !strings.Contains(dts, frag) {
			t.Errorf("turtle board.dts missing SMP fragment %q", frag)
		}
	}
}

// TestBoardDTSTurtleAicReg verifies the timer (pit) and aic nodes carry BOTH
// AIC register windows in SMP (T4a): timer <0x200 0x30 0x500 0x30>, aic
// <0x200 0x40 0x500 0x40>.
func TestBoardDTSTurtleAicReg(t *testing.T) {
	root := os.Getenv("JCORE_SOC_ROOT")
	if root == "" {
		t.Skip("JCORE_SOC_ROOT not set")
	}
	b, _ := board.Load(root, "turtle_1v0")
	res, _ := elaborate.Elaborate(b)
	dts, err := devicetree.BoardDTS(b, res)
	if err != nil {
		t.Fatalf("BoardDTS: %v", err)
	}
	for _, frag := range []string{
		"reg = <0x200 0x30 0x500 0x30>;",
		"reg = <0x200 0x40 0x500 0x40>; // ABCD0200-ABCD023F, ABCD0500-ABCD053F",
	} {
		if !strings.Contains(dts, frag) {
			t.Errorf("turtle board.dts missing dual-AIC reg %q", frag)
		}
	}
}

// TestBoardDTSTurtleIPIVector verifies the ipi node's interrupt is the AIC
// vector (0x11+irq = 0x14), not the raw irq (0x3) (T4a).
func TestBoardDTSTurtleIPIVector(t *testing.T) {
	root := os.Getenv("JCORE_SOC_ROOT")
	if root == "" {
		t.Skip("JCORE_SOC_ROOT not set")
	}
	b, _ := board.Load(root, "turtle_1v0")
	res, _ := elaborate.Elaborate(b)
	dts, err := devicetree.BoardDTS(b, res)
	if err != nil {
		t.Fatalf("BoardDTS: %v", err)
	}
	if !strings.Contains(dts, "interrupts = <0x14>;") {
		t.Errorf("turtle ipi interrupt not vector 0x14:\n%s", dts)
	}
}
