package generate

import (
	"errors"
	"testing"

	"github.com/j-core/jcore-soc/tools/socgen/board"
	"github.com/j-core/jcore-soc/tools/socgen/design"
	"github.com/j-core/jcore-soc/tools/socgen/elaborate"
	"github.com/j-core/jcore-soc/tools/socgen/iface"
	"github.com/j-core/jcore-soc/tools/socgen/vhdl"
)

// minimalRes is a Resolution rich enough that the emitters return without
// panicking (empty device/signal sets -> minimal but valid VHDL).
func minimalRes() *elaborate.Resolution {
	return &elaborate.Resolution{}
}

// minimalLib returns an iface.Library with a cfg_clk_cpu_period_ns constant
// (20 ns -> 50 MHz). Required because devicetree.BoardDTS calls cpuFreq(b.Library)
// which returns an error when the constant is absent, causing Build to fail even
// in the best-effort path.
func minimalLib() *iface.Library {
	return &iface.Library{
		Entities: map[string]*iface.Entity{},
		Packages: map[string]*iface.Package{
			"cfg": {
				Name: "cfg",
				Constants: []*iface.Constant{
					{
						Name:  "CFG_CLK_CPU_PERIOD_NS",
						Value: &vhdl.BasicLit{Kind: vhdl.INT, Value: "20"},
					},
				},
			},
		},
		Architectures:  map[string][]*iface.Architecture{},
		Configurations: map[string]*iface.Configuration{},
	}
}

func boardWith(plugins []string) *board.Board {
	return &board.Board{
		Name:    "synthetic",
		Design:  &design.Design{Plugins: plugins},
		Library: minimalLib(),
	}
}

func names(files []File) map[string]bool {
	m := make(map[string]bool, len(files))
	for _, f := range files {
		m[f.Name] = true
	}
	return m
}

func TestBuildSelectsBoardHOnly(t *testing.T) {
	files, err := Build(boardWith([]string{"board.h"}), minimalRes())
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	n := names(files)
	if !n["board.h"] {
		t.Errorf("expected board.h in file set: %v", n)
	}
	if n["board.dts"] {
		t.Errorf("did not expect board.dts when device_tree absent: %v", n)
	}
	for _, core := range []string{"devices.vhd", "soc.vhd", "pad_ring.vhd", "build.mk"} {
		if !n[core] {
			t.Errorf("missing core file %q: %v", core, n)
		}
	}
}

func TestBuildSelectsDeviceTreeOnly(t *testing.T) {
	files, err := Build(boardWith([]string{"device_tree"}), minimalRes())
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	n := names(files)
	if !n["board.dts"] {
		t.Errorf("expected board.dts: %v", n)
	}
	if n["board.h"] {
		t.Errorf("did not expect board.h when board.h plugin absent: %v", n)
	}
}

func TestBuildDuplicatePlugin(t *testing.T) {
	_, err := Build(boardWith([]string{"board.h", "board.h"}), minimalRes())
	if !errors.Is(err, ErrDuplicatePlugin) {
		t.Errorf("expected ErrDuplicatePlugin, got %v", err)
	}
}

func TestBuildUnknownPlugin(t *testing.T) {
	_, err := Build(boardWith([]string{"bogus"}), minimalRes())
	if !errors.Is(err, ErrUnknownPlugin) {
		t.Errorf("expected ErrUnknownPlugin, got %v", err)
	}
}

func TestBuildMKListsOnlyVHDL(t *testing.T) {
	files, err := Build(boardWith([]string{"device_tree", "board.h"}), minimalRes())
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	var mk string
	for _, f := range files {
		if f.Name == "build.mk" {
			mk = f.Content
		}
	}
	want := "# This file is generated by soc_gen and will be overwritten next time\n" +
		"# the tool is run. See soc_top/README for information on running soc_gen.\n" +
		"$(VHDLS) += devices.vhd\n$(VHDLS) += soc.vhd\n$(VHDLS) += pad_ring.vhd\n"
	if mk != want {
		t.Errorf("build.mk content:\n got %q\nwant %q", mk, want)
	}
	if last := files[len(files)-1].Name; last != "build.mk" {
		t.Errorf("build.mk should be appended last, got last file %q", last)
	}
}
