-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
use work.data_bus_pack.all;
use work.dma_pack.all;
use work.sdram_pkg.all;
entity pad_ring is
    port (
        pin_btn0 : in std_logic;
        pin_btn1 : in std_logic;
        pin_btn2 : in std_logic;
        pin_btn3 : in std_logic;
        pin_btn4 : in std_logic;
        pin_btn5 : in std_logic;
        pin_btn6 : in std_logic;
        pin_clk_25mhz : in std_logic;
        pin_ftdi_rxd : in std_logic;
        pin_ftdi_txd : out std_logic;
        pin_led0 : out std_logic;
        pin_led1 : out std_logic;
        pin_led2 : out std_logic;
        pin_led3 : out std_logic;
        pin_led4 : out std_logic;
        pin_led5 : out std_logic;
        pin_led6 : out std_logic;
        pin_led7 : out std_logic;
        pin_sdram_a0 : out std_logic;
        pin_sdram_a1 : out std_logic;
        pin_sdram_a2 : out std_logic;
        pin_sdram_a3 : out std_logic;
        pin_sdram_a4 : out std_logic;
        pin_sdram_a5 : out std_logic;
        pin_sdram_a6 : out std_logic;
        pin_sdram_a7 : out std_logic;
        pin_sdram_a8 : out std_logic;
        pin_sdram_a9 : out std_logic;
        pin_sdram_a10 : out std_logic;
        pin_sdram_a11 : out std_logic;
        pin_sdram_a12 : out std_logic;
        pin_sdram_ba0 : out std_logic;
        pin_sdram_ba1 : out std_logic;
        pin_sdram_casn : out std_logic;
        pin_sdram_cke : out std_logic;
        pin_sdram_clk : out std_logic;
        pin_sdram_csn : out std_logic;
        pin_sdram_d0 : inout std_logic;
        pin_sdram_d1 : inout std_logic;
        pin_sdram_d2 : inout std_logic;
        pin_sdram_d3 : inout std_logic;
        pin_sdram_d4 : inout std_logic;
        pin_sdram_d5 : inout std_logic;
        pin_sdram_d6 : inout std_logic;
        pin_sdram_d7 : inout std_logic;
        pin_sdram_d8 : inout std_logic;
        pin_sdram_d9 : inout std_logic;
        pin_sdram_d10 : inout std_logic;
        pin_sdram_d11 : inout std_logic;
        pin_sdram_d12 : inout std_logic;
        pin_sdram_d13 : inout std_logic;
        pin_sdram_d14 : inout std_logic;
        pin_sdram_d15 : inout std_logic;
        pin_sdram_dqm0 : out std_logic;
        pin_sdram_dqm1 : out std_logic;
        pin_sdram_rasn : out std_logic;
        pin_sdram_wen : out std_logic
    );
end;
architecture impl of pad_ring is
    signal clk_25mhz : std_logic;
    signal clk_sys : std_logic;
    signal ext_rst : std_logic;
    signal pi : std_logic_vector(31 downto 0);
    signal pll_locked : std_logic;
    signal po : std_logic_vector(31 downto 0);
    signal reset : std_logic;
    signal sd_cmd : sdram_cmd_t;
    signal sd_dq_i : std_logic_vector(15 downto 0);
    signal sd_dq_o : std_logic_vector(15 downto 0);
    signal sd_dq_oe : std_logic;
    signal uart0_rx : std_logic;
    signal uart0_tx : std_logic;
begin
    soc : entity work.soc(impl)
        port map (
            clk_sys => clk_sys,
            pi => pi,
            po => po,
            reset => reset,
            sd_cmd => sd_cmd,
            sd_dq_i => sd_dq_i,
            sd_dq_o => sd_dq_o,
            sd_dq_oe => sd_dq_oe,
            uart0_rx => uart0_rx,
            uart0_tx => uart0_tx
        );
    clkgen : entity work.clkgen(sim)
        port map (
            clk => clk_sys,
            clk_in => clk_25mhz,
            locked => pll_locked,
            rst_in => ext_rst
        );
    reset_sync : entity work.reset_sync(rtl)
        port map (
            clk => clk_sys,
            locked => pll_locked,
            rst => reset
        );
    sdram_iocells : entity work.sdram_iocells(rtl)
        port map (
            dq(0) => pin_sdram_d0,
            dq(1) => pin_sdram_d1,
            dq(10) => pin_sdram_d10,
            dq(11) => pin_sdram_d11,
            dq(12) => pin_sdram_d12,
            dq(13) => pin_sdram_d13,
            dq(14) => pin_sdram_d14,
            dq(15) => pin_sdram_d15,
            dq(2) => pin_sdram_d2,
            dq(3) => pin_sdram_d3,
            dq(4) => pin_sdram_d4,
            dq(5) => pin_sdram_d5,
            dq(6) => pin_sdram_d6,
            dq(7) => pin_sdram_d7,
            dq(8) => pin_sdram_d8,
            dq(9) => pin_sdram_d9,
            dq_i => sd_dq_i,
            dq_o => sd_dq_o,
            dq_oe => sd_dq_oe
        );
    -- led
    pi(0) <= po(0);
    -- led
    pi(1) <= po(1);
    -- led
    pi(2) <= po(2);
    -- led
    pi(3) <= po(3);
    -- led
    pi(4) <= po(4);
    -- led
    pi(5) <= po(5);
    -- led
    pi(6) <= po(6);
    -- led
    pi(7) <= po(7);
    pi(8) <= '0';
    pi(9) <= '0';
    pi(10) <= '0';
    pi(11) <= '0';
    pi(12) <= '0';
    pi(13) <= '0';
    pi(14) <= '0';
    pi(15) <= '0';
    pi(16) <= '0';
    pi(17) <= '0';
    pi(18) <= '0';
    pi(19) <= '0';
    pi(20) <= '0';
    pi(21) <= '0';
    pi(22) <= '0';
    pi(23) <= '0';
    pi(24) <= '0';
    pi(25) <= '0';
    pi(26) <= '0';
    pi(27) <= '0';
    pi(28) <= '0';
    pi(29) <= '0';
    pi(30) <= '0';
    pi(31) <= '0';
    pi(0) <= pin_btn0;
    pi(1) <= pin_btn1;
    pi(2) <= pin_btn2;
    pi(3) <= pin_btn3;
    pi(4) <= pin_btn4;
    pi(5) <= pin_btn5;
    pi(6) <= pin_btn6;
    clk_25mhz <= pin_clk_25mhz;
    uart0_rx <= pin_ftdi_rxd;
    pin_ftdi_txd <= uart0_tx;
    pin_led0 <= po(0);
    pin_led1 <= po(1);
    pin_led2 <= po(2);
    pin_led3 <= po(3);
    pin_led4 <= po(4);
    pin_led5 <= po(5);
    pin_led6 <= po(6);
    pin_led7 <= po(7);
    pin_sdram_a0 <= sd_cmd.a(0);
    pin_sdram_a1 <= sd_cmd.a(1);
    pin_sdram_a2 <= sd_cmd.a(2);
    pin_sdram_a3 <= sd_cmd.a(3);
    pin_sdram_a4 <= sd_cmd.a(4);
    pin_sdram_a5 <= sd_cmd.a(5);
    pin_sdram_a6 <= sd_cmd.a(6);
    pin_sdram_a7 <= sd_cmd.a(7);
    pin_sdram_a8 <= sd_cmd.a(8);
    pin_sdram_a9 <= sd_cmd.a(9);
    pin_sdram_a10 <= sd_cmd.a(10);
    pin_sdram_a11 <= sd_cmd.a(11);
    pin_sdram_a12 <= sd_cmd.a(12);
    pin_sdram_ba0 <= sd_cmd.ba(0);
    pin_sdram_ba1 <= sd_cmd.ba(1);
    pin_sdram_casn <= sd_cmd.cas_n;
    pin_sdram_cke <= sd_cmd.cke;
    pin_sdram_clk <= clk_sys;
    pin_sdram_csn <= sd_cmd.cs_n;
    pin_sdram_dqm0 <= sd_cmd.dqm(0);
    pin_sdram_dqm1 <= sd_cmd.dqm(1);
    pin_sdram_rasn <= sd_cmd.ras_n;
    pin_sdram_wen <= sd_cmd.we_n;
end;
