-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
use work.data_bus_pack.all;
use work.dma_pack.all;
use work.sdram_pkg.all;
entity soc is
    port (
        clk_sys : in std_logic;
        gpio_di : in std_logic_vector(31 downto 0);
        gpio_do : out std_logic_vector(31 downto 0);
        reset : in std_logic;
        sd_cmd : out sdram_cmd_t;
        sd_dq_i : in std_logic_vector(15 downto 0);
        sd_dq_o : out std_logic_vector(15 downto 0);
        sd_dq_oe : out std_logic;
        uart0_rx : in std_logic;
        uart0_tx : out std_logic
    );
end;
architecture impl of soc is
    signal aic_irq : std_logic_vector(7 downto 0);
    signal cache01sel_ctrl_temp : std_logic;
    signal cpu0_ddr_dbus_i : cpu_data_i_t;
    signal cpu0_ddr_dbus_o : cpu_data_o_t;
    signal cpu0_ddr_ibus_i : cpu_instruction_i_t;
    signal cpu0_ddr_ibus_o : cpu_instruction_o_t;
    signal cpu0_event_i : cpu_event_i_t;
    signal cpu0_event_o : cpu_event_o_t;
    signal cpu0_mem_lock : std_logic;
    signal cpu0_periph_dbus_i : cpu_data_i_t;
    signal cpu0_periph_dbus_o : cpu_data_o_t;
    signal cpu1_ddr_dbus_i : cpu_data_i_t;
    signal cpu1_ddr_dbus_o : cpu_data_o_t;
    signal cpu1_ddr_ibus_i : cpu_instruction_i_t;
    signal cpu1_ddr_ibus_o : cpu_instruction_o_t;
    signal cpu1_event_i : cpu_event_i_t;
    signal cpu1_mem_lock : std_logic;
    signal cpu1_periph_dbus_i : cpu_data_i_t;
    signal cpu1_periph_dbus_o : cpu_data_o_t;
    signal dcache0_ctrl : cache_ctrl_t;
    signal dcache1_ctrl : cache_ctrl_t;
    signal ddr_burst : std_logic;
    signal ddr_bus_ack_r : std_logic;
    signal ddr_bus_i : cpu_data_i_t;
    signal ddr_bus_o : cpu_data_o_t;
    signal debug_i : cpu_debug_i_t;
    signal dma_dbus_o : bus_ddr_o_t;
    signal icache1_ctrl : cache_ctrl_t;
begin
    aic_irq_gen : entity work.aic_irq_gen(rtl)
        port map (
            clk => clk_sys,
            irq => aic_irq,
            pi_in => gpio_di
        );
    cpus : configuration work.one_cpu_m0_direct_fpga
        generic map (
            insert_inst_delay_boot_mem => FALSE,
            insert_read_delay_boot_mem => FALSE,
            insert_write_delay_boot_mem => FALSE
        )
        port map (
            clk => clk_sys,
            cpu0_copro_i => NULL_COPR_I,
            cpu0_copro_o => open,
            cpu0_data_master_ack => open,
            cpu0_data_master_en => open,
            cpu0_ddr_dbus_i => cpu0_ddr_dbus_i,
            cpu0_ddr_dbus_o => cpu0_ddr_dbus_o,
            cpu0_ddr_ibus_i => cpu0_ddr_ibus_i,
            cpu0_ddr_ibus_o => cpu0_ddr_ibus_o,
            cpu0_event_i => cpu0_event_i,
            cpu0_event_o => cpu0_event_o,
            cpu0_mem_lock => cpu0_mem_lock,
            cpu0_periph_dbus_i => cpu0_periph_dbus_i,
            cpu0_periph_dbus_o => cpu0_periph_dbus_o,
            cpu1_copro_i => NULL_COPR_I,
            cpu1_copro_o => open,
            cpu1_data_master_ack => open,
            cpu1_data_master_en => open,
            cpu1_ddr_dbus_i => cpu1_ddr_dbus_i,
            cpu1_ddr_dbus_o => cpu1_ddr_dbus_o,
            cpu1_ddr_ibus_i => cpu1_ddr_ibus_i,
            cpu1_ddr_ibus_o => cpu1_ddr_ibus_o,
            cpu1_event_i => cpu1_event_i,
            cpu1_event_o => open,
            cpu1_mem_lock => cpu1_mem_lock,
            cpu1_periph_dbus_i => cpu1_periph_dbus_i,
            cpu1_periph_dbus_o => cpu1_periph_dbus_o,
            cpu1eni => '0',
            debug_i => debug_i,
            debug_o => open,
            rst => reset
        );
    ddr_ram_mux : configuration work.ddr_ram_mux_one_cpu_idcache_fpga
        port map (
            cache01sel_ctrl_temp => cache01sel_ctrl_temp,
            clk => clk_sys,
            clk_ddr => clk_sys,
            cpu0_dbus_i => cpu0_ddr_dbus_i,
            cpu0_dbus_o => cpu0_ddr_dbus_o,
            cpu0_ibus_i => cpu0_ddr_ibus_i,
            cpu0_ibus_o => cpu0_ddr_ibus_o,
            cpu0_mem_lock => cpu0_mem_lock,
            cpu1_dbus_i => cpu1_ddr_dbus_i,
            cpu1_dbus_o => cpu1_ddr_dbus_o,
            cpu1_ibus_i => cpu1_ddr_ibus_i,
            cpu1_ibus_o => cpu1_ddr_ibus_o,
            cpu1_mem_lock => cpu1_mem_lock,
            dcache0_ctrl => dcache0_ctrl,
            dcache1_ctrl => dcache1_ctrl,
            ddr_burst => ddr_burst,
            ddr_bus_ack_r => ddr_bus_ack_r,
            ddr_bus_i => ddr_bus_i,
            ddr_bus_o => ddr_bus_o,
            dma_dbus_i => open,
            dma_dbus_o => dma_dbus_o,
            icache0_ctrl => CACHE_CTRL_ON,
            icache1_ctrl => icache1_ctrl,
            rst => reset
        );
    sdram_ctrl : entity work.sdram_ctrl(rtl)
        port map (
            ack_r => ddr_bus_ack_r,
            bst => ddr_burst,
            clk => clk_sys,
            cmd => sd_cmd,
            dq_i => sd_dq_i,
            dq_o => sd_dq_o,
            dq_oe => sd_dq_oe,
            req => ddr_bus_o,
            resp => ddr_bus_i,
            rst => reset
        );
    devices : entity work.devices(impl)
        port map (
            aic_irq => aic_irq,
            clk_sys => clk_sys,
            cpu0_event_i => cpu0_event_i,
            cpu0_event_o => cpu0_event_o,
            cpu0_periph_dbus_i => cpu0_periph_dbus_i,
            cpu0_periph_dbus_o => cpu0_periph_dbus_o,
            cpu1_periph_dbus_i => cpu1_periph_dbus_i,
            cpu1_periph_dbus_o => cpu1_periph_dbus_o,
            gpio_di => gpio_di,
            gpio_do => gpio_do,
            reset => reset,
            uart0_rx => uart0_rx,
            uart0_tx => uart0_tx
        );
    -- Zero out unused signals
    cache01sel_ctrl_temp <= '0';
    cpu1_event_i <= (en => '0', cmd => INTERRUPT, vec => (others => '0'), msk => '0', lvl => (others => '0'));
    dcache0_ctrl <= (en => '0', inv => '0');
    dcache1_ctrl <= (en => '0', inv => '0');
    debug_i <= (en => '0', cmd => BREAK, ir => (others => '0'), d => (others => '0'), d_en => '0');
    dma_dbus_o <= (en => '0', a => (others => '0'), d => (others => '0'), wr => '0', we => (others => '0'), burst32 => '0', burst16 => '0', bgrp => '0');
    icache1_ctrl <= (en => '0', inv => '0');
end;
