/* Minimal freestanding <inttypes.h> shim: board.h (generated by soc_gen)
   #includes <inttypes.h> for the fixed-width types, but this standalone
   ROM has no libc (see rom/Makefile) and does not depend on the boot/
   submodule's headers. Mirrors boot/include/inttypes.h. */
#ifndef INTTYPES_H
#define INTTYPES_H

typedef unsigned int uint32_t;
typedef int int32_t;

typedef unsigned short uint16_t;
typedef short int16_t;

typedef unsigned char uint8_t;
typedef char int8_t;

#endif
