-- Task 6 PHASE A rebind: gf180_j4mmu-only ddr_ram_mux configuration,
-- mirroring targets/ddr_ram_mux/one_cpu_idcache_fpga.vhd's
-- ddr_ram_mux_one_cpu_idcache_fpga (same `one_cpu_idcache` architecture,
-- same icache_adapter/dcache_adapter component instances u_icache/u_dcache)
-- except it selects the REAL vendor-SRAM cache configurations
-- (icache_adapter_gf180/dcache_adapter_gf180, from
-- lib/memory_tech_lib/tech/gf180/cache_gf180_config.vhd -- the tag RAM on
-- gf180mcu_fd_ip_sram__sram256x8m8wm1, the data RAM on
-- gf180mcu_fd_ip_sram__sram512x8m8wm1) instead of _fpga's tech/inferred
-- (flip-flop) RAM path.
--
-- Selection mechanism: the flash-variant soc.vhd generated by
-- `make gf180_j4mmu TARGET=soc_gen VARIANT=flash` emits a bare
-- `ddr_ram_mux : entity work.ddr_ram_mux` (socgen's cpumap.go only knows the
-- "_fpga" configuration names -- see tools/socgen/elaborate/cpumap.go --
-- so it cannot itself emit a reference to this gf180-only configuration).
-- targets/asic/gf180_j4mmu/sim/xip_sim.sh normalizes that bare entity
-- instantiation to `configuration work.ddr_ram_mux_one_cpu_idcache_gf180`
-- via `sed`, the same technique already used there for the `cpus`
-- instantiation. The base variant (which explicitly emits
-- `configuration work.ddr_ram_mux_one_cpu_idcache_fpga` via socgen, driven
-- by cpumap.go's static table) is UNCHANGED -- this configuration is
-- flash-variant-only, selected only by that sed normalization.
configuration ddr_ram_mux_one_cpu_idcache_gf180 of ddr_ram_mux is
  for one_cpu_idcache
    for all : icache_adapter
      use configuration work.icache_adapter_gf180;
    end for;
    for all : dcache_adapter
      use configuration work.dcache_adapter_gf180;
    end for;
  end for;
end configuration;
