-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
use work.data_bus_pack.all;
entity devices is
    port (
        aic_irq : in std_logic_vector(7 downto 0);
        clk_sys : in std_logic;
        cpu0_event_i : out cpu_event_i_t;
        cpu0_event_o : in cpu_event_o_t;
        cpu0_periph_dbus_i : out cpu_data_i_t;
        cpu0_periph_dbus_o : in cpu_data_o_t;
        cpu1_periph_dbus_i : out cpu_data_i_t;
        cpu1_periph_dbus_o : in cpu_data_o_t;
        gpio_di : in std_logic_vector(31 downto 0);
        gpio_do : out std_logic_vector(31 downto 0);
        qfl_cs_n : out std_logic;
        qfl_io_i : in std_logic_vector(3 downto 0);
        qfl_io_o : out std_logic_vector(3 downto 0);
        qfl_io_oe : out std_logic_vector(3 downto 0);
        qfl_sck : out std_logic;
        reset : in std_logic;
        spi2_clk : out std_logic;
        spi2_cs : out std_logic_vector(1 downto 0);
        spi2_miso : in std_logic;
        spi2_mosi : out std_logic;
        uart0_rx : in std_logic;
        uart0_tx : out std_logic
    );
end;
architecture impl of devices is
    type device_t is (NONE, DEV_AIC0, DEV_GPIO0, DEV_QSPI_FLASH0, DEV_SPI2, DEV_UART0);
    signal active_dev : device_t;
    type data_bus_i_t is array (device_t'left to device_t'right) of cpu_data_i_t;
    type data_bus_o_t is array (device_t'left to device_t'right) of cpu_data_o_t;
    signal devs_bus_i : data_bus_i_t;
    signal devs_bus_o : data_bus_o_t;
    function decode_address (addr : std_logic_vector(31 downto 0)) return device_t is
    begin
        -- Assumes addr(31 downto 28) = x"a".
        -- Address decoding closer to CPU checks those bits.
        if addr(27 downto 24) = "0001" then
            -- A1000000-A1FFFFFF
            return DEV_QSPI_FLASH0;
        elsif addr(27 downto 10) = "101111001101000000" then
            if addr(9) = '0' then
                if addr(8 downto 7) = "00" then
                    if addr(6 downto 4) = "000" then
                        -- ABCD0000-ABCD000F
                        return DEV_GPIO0;
                    elsif addr(6) = '1' then
                        -- ABCD0040-ABCD007F
                        return DEV_AIC0;
                    end if;
                elsif addr(8 downto 4) = "10000" then
                    -- ABCD0100-ABCD010F
                    return DEV_UART0;
                end if;
            elsif addr(9 downto 3) = "1000000" then
                -- ABCD0200-ABCD0207
                return DEV_SPI2;
            end if;
        end if;
        return NONE;
    end;
    signal irqs0 : std_logic_vector(7 downto 0) := (others => '0');
begin
    -- Disconnected peripheral buses
    cpu1_periph_dbus_i <= loopback_bus(cpu1_periph_dbus_o);
    -- multiplex data bus to and from devices
    active_dev <= decode_address(cpu0_periph_dbus_o.a);
    cpu0_periph_dbus_i <= devs_bus_i(active_dev);
    bus_split : for dev in device_t'left to device_t'right generate
        devs_bus_o(dev) <= mask_data_o(cpu0_periph_dbus_o, to_bit(dev = active_dev));
    end generate;
    devs_bus_i(NONE) <= loopback_bus(devs_bus_o(NONE));
    -- Instantiate devices
    aic0 : entity work.aic(behav)
        generic map (
            c_busperiod => CFG_CLK_CPU_PERIOD_NS,
            vector_numbers => (x"11", x"12", x"13", x"14", x"15", x"16", x"17", x"18")
        )
        port map (
            back_i => '0',
            bstb_i => '0',
            clk_bus => clk_sys,
            db_i => devs_bus_o(DEV_AIC0),
            db_o => devs_bus_i(DEV_AIC0),
            enmi_i => '1',
            event_i => cpu0_event_o,
            event_o => cpu0_event_i,
            irq_i => aic_irq,
            reboot => open,
            rst_i => reset,
            rtc_nsec => open,
            rtc_sec => open
        );
    gpio0 : entity work.gpio2(arch)
        port map (
            clk => clk_sys,
            d_i => gpio_di,
            d_o => gpio_do,
            d_t => open,
            db_i => devs_bus_o(DEV_GPIO0),
            db_o => devs_bus_i(DEV_GPIO0),
            irq => open,
            rst => reset
        );
    qspi_flash0 : entity work.qspi_flash_ctrl(rtl)
        generic map (
            dummy_cycles => 6,
            flash_base => x"A1000000",
            lanes => 4
        )
        port map (
            clk => clk_sys,
            db_i => devs_bus_o(DEV_QSPI_FLASH0),
            db_o => devs_bus_i(DEV_QSPI_FLASH0),
            fl_cs_n => qfl_cs_n,
            fl_io_i => qfl_io_i,
            fl_io_o => qfl_io_o,
            fl_io_oe => qfl_io_oe,
            fl_sck => qfl_sck,
            rst => reset
        );
    spi2 : entity work.spi2(arch)
        generic map (
            clk_freq => CFG_CLK_CPU_FREQ_HZ
        )
        port map (
            busy => open,
            clk => clk_sys,
            cpha => '0',
            cpol => '0',
            cs => spi2_cs,
            db_i => devs_bus_o(DEV_SPI2),
            db_o => devs_bus_i(DEV_SPI2),
            miso => spi2_miso,
            mosi => spi2_mosi,
            rst => reset,
            spi_clk => spi2_clk
        );
    uart0 : entity work.uartlitedb(arch)
        generic map (
            bps => 115200.0,
            fclk => CFG_CLK_CPU_FREQ_HZ,
            intcfg => 1
        )
        port map (
            clk => clk_sys,
            db_i => devs_bus_o(DEV_UART0),
            db_o => devs_bus_i(DEV_UART0),
            int => open,
            rst => reset,
            rx => uart0_rx,
            tx => uart0_tx
        );
end;
