# Canonical ghdl analyze order for the gf180_j4mmu logical SoC (single J4
# core, direct decode, id-cache -- see design.yaml). Adapted from
# targets/boards/ulx3s/filelist.sh: drops the ECP5-only entries
# (pad_ring.vhd, ulx3s_clkgen*.vhd, reset_sync.vhd) and the dual-core-only
# entries (multi_master_bus_mux, icache_modereg IPI, the soc_port_*-attribute-
# stripped $GEN copies -- those only matter for `ghdl --synth`, not the plain
# `ghdl -a`/`ghdl -e` analyze+elaborate this target uses). This target has no
# pad_ring: soc.vhd (entity `soc`) is the GHDL elaboration top.
#
# Sourced after cd to repo root, with work/config.vhd and targets/clk_config.vhd
# (soc_gen-generated + hand-written packages) already analyzed -- see
# targets/asic/gf180_j4mmu/README.md for the exact ghdl invocation.
CPU=components/cpu
FILES=(
  $CPU/cpu2j0_pkg.vhd
  $CPU/core/components_pkg.vhd
  # tlb: cpu.vhd directly instantiates work.tlb (entity inst. in the MMU_ARCH
  # generate), so ghdl needs it analyzed before cpu.vhd for ALL variants.
  $CPU/core/tlb.vhd
  $CPU/core/mult_pkg.vhd
  $CPU/core/divider_pkg.vhd
  $CPU/decode/decode_pkg.vhd
  $CPU/core/datapath_pkg.vhd
  $CPU/core/cpu.vhd
  $CPU/core/mult.vhd
  $CPU/core/divider.vhd
  $CPU/core/datapath.vhd
  $CPU/core/shifter.vhd
  $CPU/core/register_file.vhd
  $CPU/core/register_file_flops.vhd
  $CPU/core/register_file_two_bank.vhd
  $CPU/decode/decode.vhd
  $CPU/decode/decode_body.vhd
  $CPU/decode/decode_table.vhd
  $CPU/decode/decode_core.vhd
  # j4 direct-decode variant decode table + cpu_synth config (from
  # design.yaml's model:j4 decode:direct -- see cpu_synth_files.list,
  # regenerated by soc_gen). ASIC-designed combinational decoder, drops the
  # microcode ROM.
  $CPU/decode/decode_table_direct.vhd
  $CPU/decode/decode_table_direct_config.vhd
  $CPU/synth/cpu_synth_j4_config.vhd
  lib/hwutils/attr_pkg.vhd
  components/misc/misc_pkg.vhd
  targets/data_bus_pkg.vhd
  # cache + ddr_ram_mux + dma (depend on cpu2j0_pack + data_bus_pack)
  components/ddr2/ddrc_cnt_pkg.vhd
  components/cpu/cache/cache_clkmode_sc.vhd  # CACHE_SAME_CLOCK=true -> posedge _sc CDC
  components/cpu/cache/cache_pkg.vhd
  lib/reg_file_struct/bist_pkg.vhd
  components/dma/dma_pkg.vhd
  lib/memory_tech_lib/memory_pkg.vhd
  lib/memory_tech_lib/ram_1rw.vhd
  lib/memory_tech_lib/ram_2rw.vhd
  lib/memory_tech_lib/tech/inferred/ram_1rw_infer.vhd
  lib/memory_tech_lib/tech/inferred/ram_2rw_infer.vhd
  components/misc/bus_mux_pkg.vhd
  components/misc/bus_mux_ff_pkg.vhd
  components/misc/bus_mux_lock_pkg.vhd
  components/misc/bus_mux_typec_pkg.vhd
  components/cpu/cache/dcache_adapter.vhd
  components/cpu/cache/icache_adapter.vhd
  components/cpu/cache/dcache_ram.vhd
  components/cpu/cache/icache_ram.vhd
  components/cpu/cache/dcache_ccl.vhd
  components/cpu/cache/dcache_mcl.vhd
  components/cpu/cache/icache_ccl.vhd
  components/cpu/cache/icache_mcl.vhd
  # icache_modereg: single-core (cores=1) never instantiates it (that's
  # dual-only IPI wiring), but analyzing it unconditionally is harmless and
  # matches ulx3s's filelist ordering. Raw (unstripped) copy: no
  # `ghdl --synth` in this target's flow, so the soc_port_* attributes are inert.
  components/cpu/cache/icache_modereg.vhd
  components/cpu/cache/dcache.vhd  # posedge _sc CDC (cache_clkmode_sc)
  components/cpu/cache/icache.vhd
  components/cpu/cache/cache_config_fpga.vhd
  components/misc/bus_mux_typecsub.vhd
  components/misc/bus_mux_typec.vhd
  targets/ddr_ram_mux/ddr_ram_mux.vhd
  targets/ddr_ram_mux/one_cpu_idcache.vhd
  targets/ddr_ram_mux/one_cpu_idcache_fpga.vhd
  # NOTE: targets/asic/gf180_j4mmu/ddr_ram_mux_one_cpu_idcache_gf180.vhd
  # (Task 6 PHASE A's gf180-vendor-SRAM ddr_ram_mux configuration) is
  # deliberately NOT listed here -- it depends on
  # lib/memory_tech_lib/tech/gf180/cache_gf180_config.vhd's
  # icache_adapter_gf180/dcache_adapter_gf180 configurations, which are only
  # analyzed by sim/xip_sim.sh's own gf180-cache splice (mirroring
  # metrics/gen_synth_sources.sh's GHDL_BASE_GF180_CACHE), not by this
  # shared filelist (used unmodified by the base variant and every
  # standalone per-macro metrics/LibreLane flow). sim/xip_sim.sh inserts
  # both files into its own analyze order.
  targets/cpu_core_pkg.vhd
  targets/cpu_core.vhd
  targets/cpus.vhd
  lib/hwutils/data_bus_delay.vhd
  lib/hwutils/instr_bus_delay.vhd
  components/uartlite/uart_pkg.vhd
  components/uartlite/uart.vhd
  components/uartlite/uartlitedb.vhd
  # AIC v1 (interrupt controller + RTC + PIT) + peripheral bus mux
  components/misc/aic2_pkg.vhd
  components/misc/aic_edgedet.vhd
  components/misc/aic.vhd
  components/misc/gpio2.vhd
  components/misc/spi2.vhd
  components/sdram/sdram_pkg.vhd
  components/sdram/sdram_ctrl.vhd
  targets/cpumreg.vhd
  targets/asic/gf180_j4mmu/boot_image_pkg.vhd
  components/memory/bootram_infer.vhd
  # BM Task 1: boot_mem architecture (constant-ROM lane + writable stack
  # SRAM lane), c_addr_width=>12 -- FLASH VARIANT ONLY (see BM Task 2 note
  # below). Analyzed unconditionally (harmless for the base variant, which
  # never selects this architecture -- see cpus_one_m0_gf180_arch.vhd below).
  components/memory/boot_mem.vhd
  # BASE variant cpus architecture (one_cpu_m0, bootram_infer(inferred),
  # c_addr_width=>14, 16 KiB): the shared file also used by
  # ulx3s/icesugar -- UNCHANGED. sim/rtl.sh's self-test bootloader (a real
  # ~7 KB RAM-resident program) only fits this 16 KiB region, so the base
  # (no-flash) variant must keep it.
  targets/boards/ulx3s/cpus_one_m0_arch.vhd
  # BM Task 2: gf180_j4mmu-only cpus architecture -- FLASH VARIANT ONLY.
  # Binds bootram_infer(boot_mem)/c_addr_width=>12 (4 KiB: 2 KiB read-only
  # ROM vector lane + 2 KiB writable stack SRAM lane) instead of
  # bootram_infer(inferred)/c_addr_width=>14. boot_mem's premise is
  # booting from flash XIP (PC=0x14000000, see boot_image_pkg.vhd) -- the
  # base variant has no qspi_flash_ctrl and keeps one_cpu_m0/inferred
  # above.
  #
  # Selection mechanism: cpus_config.vhd (the explicit VHDL `configuration`
  # soc_gen emits from design.yaml's cpu.architecture) is a BASE-variant-
  # only artifact -- VARIANT=flash's soc_gen run does not rewrite it, and
  # (independently) the flash variant's own generated soc.vhd binds `cpus`
  # via a bare `entity work.cpus` with NO explicit architecture/config at
  # all, because socgen's elaborate step reports the `cpus` entity's
  # architecture as ambiguous whenever more than one architecture of it
  # exists anywhere in the tree (which is unavoidable once this file adds a
  # second one) and falls back to leaving the binding to GHDL. So the flash
  # variant's actual binding is decided purely by GHDL's own default-
  # binding rule: the LAST-analyzed architecture of `cpus` in the analyzed
  # library wins. This file is listed last (after
  # targets/boards/ulx3s/cpus_one_m0_arch.vhd above) specifically so that
  # rule lands on `one_cpu_m0_gf180` for the flash build, while the base
  # build's explicit `configuration soc_cpus_config` (driven by design.yaml)
  # independently and unambiguously selects `one_cpu_m0` regardless of
  # analysis order. Confirmed via `ghdl -e soc` for both variants (base:
  # bootram_infer(inferred)/14; flash: bootram_infer(boot_mem)/12).
  targets/asic/gf180_j4mmu/cpus_one_m0_gf180_arch.vhd
  targets/boards/ulx3s/aic_irq_gen.vhd
  # QSPI flash controller (flash variant only -- NOT a peripheral device;
  # a ddr_bus mem-region_mux target, base/decode address 0x04000000
  # (the ddr_bus/mem_region_mux-side address post-icache, see
  # components/cpu/cache/icache_adapter.vhd's top-nibble-forced-to-0x0
  # a-bus mapping) / CPU-side address 0x14000000 (design.flash.yaml's
  # flash_base, the pre-icache address the CPU actually fetches from --
  # see boot_image_pkg.vhd and xip_payload/payload.S). Analyzed
  # unconditionally: harmless for the
  # base variant (devices.vhd/soc.vhd there simply never instantiate it).
  # Needs cpu2j0_pkg + data_bus_pkg (already analyzed above); must precede
  # devices.vhd/soc.vhd which instantiate it in the flash variant.
  components/misc/qspi_flash_ctrl.vhd
  # Region mux between ddr_ram_mux's ddr_bus and {sdram_ctrl,
  # qspi_flash_ctrl} (flash variant only -- Task 2 of the QSPI XIP
  # sub-project, see design.flash.yaml). Analyzed unconditionally: harmless
  # for the base variant (soc.vhd there never instantiates it).
  components/misc/mem_region_mux.vhd
  # the soc_gen-generated pair (leaf-first: devices <- soc). No pad_ring for
  # this target -- soc.vhd's `soc` entity is the elaboration top.
  targets/asic/gf180_j4mmu/devices.vhd
  targets/asic/gf180_j4mmu/cpus_config.vhd
  targets/asic/gf180_j4mmu/soc.vhd
)
printf '%s\n' "${FILES[@]}"
