-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.config.all;
use work.clk_config.all;
use work.cpu2j0_pack.all;
use work.data_bus_pack.all;
use work.dma_pack.all;
use work.sdram_pkg.all;
library unisim;
use unisim.vcomponents.all;
entity pad_ring is
    port (
        pin_clk_sys : in std_logic;
        pin_gpio_di : in std_logic;
        pin_gpio_do : out std_logic;
        pin_qfl_cs_n : out std_logic;
        pin_qfl_io_i : in std_logic;
        pin_qfl_io_o : out std_logic;
        pin_qfl_io_oe : out std_logic;
        pin_qfl_sck : out std_logic;
        pin_reset : in std_logic;
        pin_sd_cmd : out std_logic;
        pin_sd_dq_i : in std_logic;
        pin_sd_dq_o : out std_logic;
        pin_sd_dq_oe : out std_logic;
        pin_spi2_clk : out std_logic;
        pin_spi2_cs : out std_logic;
        pin_spi2_miso : in std_logic;
        pin_spi2_mosi : out std_logic;
        pin_uart0_rx : in std_logic;
        pin_uart0_tx : out std_logic
    );
end;
architecture impl of pad_ring is
    signal clk_sys : std_logic;
    signal gpio_di : std_logic_vector(31 downto 0);
    signal gpio_do : std_logic_vector(31 downto 0);
    signal qfl_cs_n : std_logic;
    signal qfl_io_i : std_logic_vector(3 downto 0);
    signal qfl_io_o : std_logic_vector(3 downto 0);
    signal qfl_io_oe : std_logic_vector(3 downto 0);
    signal qfl_sck : std_logic;
    signal reset : std_logic;
    signal sd_cmd : sdram_cmd_t;
    signal sd_dq_i : std_logic_vector(15 downto 0);
    signal sd_dq_o : std_logic_vector(15 downto 0);
    signal sd_dq_oe : std_logic;
    signal spi2_clk : std_logic;
    signal spi2_cs : std_logic_vector(1 downto 0);
    signal spi2_miso : std_logic;
    signal spi2_mosi : std_logic;
    signal uart0_rx : std_logic;
    signal uart0_tx : std_logic;
begin
    soc : entity work.soc(impl)
        port map (
            clk_sys => clk_sys,
            gpio_di => gpio_di,
            gpio_do => gpio_do,
            qfl_cs_n => qfl_cs_n,
            qfl_io_i => qfl_io_i,
            qfl_io_o => qfl_io_o,
            qfl_io_oe => qfl_io_oe,
            qfl_sck => qfl_sck,
            reset => reset,
            sd_cmd => sd_cmd,
            sd_dq_i => sd_dq_i,
            sd_dq_o => sd_dq_o,
            sd_dq_oe => sd_dq_oe,
            spi2_clk => spi2_clk,
            spi2_cs => spi2_cs,
            spi2_miso => spi2_miso,
            spi2_mosi => spi2_mosi,
            uart0_rx => uart0_rx,
            uart0_tx => uart0_tx
        );
    clk_sys <= pin_clk_sys;
    gpio_di <= pin_gpio_di;
    pin_gpio_do <= gpio_do;
    pin_qfl_cs_n <= qfl_cs_n;
    qfl_io_i <= pin_qfl_io_i;
    pin_qfl_io_o <= qfl_io_o;
    pin_qfl_io_oe <= qfl_io_oe;
    pin_qfl_sck <= qfl_sck;
    reset <= pin_reset;
    pin_sd_cmd <= sd_cmd;
    sd_dq_i <= pin_sd_dq_i;
    pin_sd_dq_o <= sd_dq_o;
    pin_sd_dq_oe <= sd_dq_oe;
    pin_spi2_clk <= spi2_clk;
    pin_spi2_cs <= spi2_cs;
    spi2_miso <= pin_spi2_miso;
    pin_spi2_mosi <= spi2_mosi;
    uart0_rx <= pin_uart0_rx;
    pin_uart0_tx <= uart0_tx;
end;
