/* Generated by Yosys 0.44 (git sha1 80ba43d26, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module soc(clk_sys, gpio_di, qfl_io_i, reset, sd_dq_i, spi2_miso, uart0_rx, gpio_do, qfl_cs_n, qfl_io_o, qfl_io_oe, qfl_sck, sd_cmd_cke , sd_cmd_cs_n , sd_cmd_ras_n , sd_cmd_cas_n , sd_cmd_we_n , sd_cmd_ba , sd_cmd_a , sd_cmd_dqm , sd_dq_o
, sd_dq_oe, spi2_clk, spi2_cs, spi2_mosi, uart0_tx);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire [31:0] _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire [3:0] _421_;
  wire _422_;
  wire _423_;
  wire [31:0] _424_;
  wire [3:0] _425_;
  wire [3:0] _426_;
  wire [4:0] _427_;
  wire _428_;
  wire _429_;
  wire [31:0] _430_;
  wire [3:0] _431_;
  wire [3:0] _432_;
  wire [4:0] _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire [22:0] _439_;
  wire _440_;
  wire _441_;
  wire aic_irq;
  wire \aic_irq_gen.clk ;
  wire [7:0] \aic_irq_gen.irq ;
  wire [31:0] \aic_irq_gen.pi_in ;
  reg [1:0] \aic_irq_gen.sync  = 2'h0;
  wire cache01sel_ctrl_temp;
  input clk_sys;
  wire clk_sys;
  wire [32:0] cpu0_ddr_dbus_i;
  wire [70:0] cpu0_ddr_dbus_o;
  wire [16:0] cpu0_ddr_ibus_i;
  wire [32:0] cpu0_ddr_ibus_o;
  wire [15:0] cpu0_event_i;
  wire [6:0] cpu0_event_o;
  wire cpu0_mem_lock;
  wire [32:0] cpu0_periph_dbus_i;
  wire [70:0] cpu0_periph_dbus_o;
  wire [32:0] cpu1_ddr_dbus_i;
  wire [70:0] cpu1_ddr_dbus_o;
  wire [16:0] cpu1_ddr_ibus_i;
  wire [32:0] cpu1_ddr_ibus_o;
  wire [15:0] cpu1_event_i;
  wire cpu1_mem_lock;
  wire [32:0] cpu1_periph_dbus_i;
  wire [70:0] cpu1_periph_dbus_o;
  wire ddr_burst;
  wire ddr_bus_ack_r;
  wire [32:0] ddr_bus_i;
  wire [70:0] ddr_bus_o;
  wire \ddr_ram_mux.cache01sel_ctrl_temp ;
  wire \ddr_ram_mux.clk ;
  wire \ddr_ram_mux.clk_ddr ;
  wire \ddr_ram_mux.cpu0_dbus_i[ack] ;
  wire [31:0] \ddr_ram_mux.cpu0_dbus_i[d] ;
  wire [31:0] \ddr_ram_mux.cpu0_dbus_o[a] ;
  wire [31:0] \ddr_ram_mux.cpu0_dbus_o[d] ;
  wire \ddr_ram_mux.cpu0_dbus_o[en] ;
  wire \ddr_ram_mux.cpu0_dbus_o[rd] ;
  wire [3:0] \ddr_ram_mux.cpu0_dbus_o[we] ;
  wire \ddr_ram_mux.cpu0_dbus_o[wr] ;
  wire \ddr_ram_mux.cpu0_ibus_i[ack] ;
  wire [15:0] \ddr_ram_mux.cpu0_ibus_i[d] ;
  wire [30:0] \ddr_ram_mux.cpu0_ibus_o[a] ;
  wire \ddr_ram_mux.cpu0_ibus_o[en] ;
  wire \ddr_ram_mux.cpu0_ibus_o[jp] ;
  wire \ddr_ram_mux.cpu0_mem_lock ;
  wire \ddr_ram_mux.cpu1_dbus_i[ack] ;
  wire [31:0] \ddr_ram_mux.cpu1_dbus_i[d] ;
  wire [31:0] \ddr_ram_mux.cpu1_dbus_o[a] ;
  wire [31:0] \ddr_ram_mux.cpu1_dbus_o[d] ;
  wire \ddr_ram_mux.cpu1_dbus_o[en] ;
  wire \ddr_ram_mux.cpu1_dbus_o[rd] ;
  wire [3:0] \ddr_ram_mux.cpu1_dbus_o[we] ;
  wire \ddr_ram_mux.cpu1_dbus_o[wr] ;
  wire \ddr_ram_mux.cpu1_ibus_i[ack] ;
  wire [15:0] \ddr_ram_mux.cpu1_ibus_i[d] ;
  wire [30:0] \ddr_ram_mux.cpu1_ibus_o[a] ;
  wire \ddr_ram_mux.cpu1_ibus_o[en] ;
  wire \ddr_ram_mux.cpu1_ibus_o[jp] ;
  wire \ddr_ram_mux.cpu1_mem_lock ;
  wire \ddr_ram_mux.data_dbus_ack_r ;
  wire [32:0] \ddr_ram_mux.data_dbus_i ;
  wire [70:0] \ddr_ram_mux.data_dbus_o ;
  wire \ddr_ram_mux.data_ddrburst ;
  wire \ddr_ram_mux.dcache0_ctrl[en] ;
  wire \ddr_ram_mux.dcache0_ctrl[inv] ;
  wire \ddr_ram_mux.dcache1_ctrl[en] ;
  wire \ddr_ram_mux.dcache1_ctrl[inv] ;
  wire \ddr_ram_mux.ddr_burst ;
  wire \ddr_ram_mux.ddr_bus_ack_r ;
  wire \ddr_ram_mux.ddr_bus_i[ack] ;
  wire [31:0] \ddr_ram_mux.ddr_bus_i[d] ;
  wire [31:0] \ddr_ram_mux.ddr_bus_o[a] ;
  wire [31:0] \ddr_ram_mux.ddr_bus_o[d] ;
  wire \ddr_ram_mux.ddr_bus_o[en] ;
  wire \ddr_ram_mux.ddr_bus_o[rd] ;
  wire [3:0] \ddr_ram_mux.ddr_bus_o[we] ;
  wire \ddr_ram_mux.ddr_bus_o[wr] ;
  wire [31:0] \ddr_ram_mux.dma_dbus_i[d] ;
  wire [31:0] \ddr_ram_mux.dma_dbus_o[a] ;
  wire \ddr_ram_mux.dma_dbus_o[bgrp] ;
  wire \ddr_ram_mux.dma_dbus_o[burst16] ;
  wire \ddr_ram_mux.dma_dbus_o[burst32] ;
  wire [31:0] \ddr_ram_mux.dma_dbus_o[d] ;
  wire \ddr_ram_mux.dma_dbus_o[en] ;
  wire [3:0] \ddr_ram_mux.dma_dbus_o[we] ;
  wire \ddr_ram_mux.dma_dbus_o[wr] ;
  wire \ddr_ram_mux.icache0_ctrl[en] ;
  wire \ddr_ram_mux.icache0_ctrl[inv] ;
  wire \ddr_ram_mux.icache1_ctrl[en] ;
  wire \ddr_ram_mux.icache1_ctrl[inv] ;
  wire \ddr_ram_mux.instr_dbus_ack_r ;
  wire [32:0] \ddr_ram_mux.instr_dbus_i ;
  wire [70:0] \ddr_ram_mux.instr_dbus_o ;
  wire \ddr_ram_mux.instr_ddrburst ;
  wire \ddr_ram_mux.rst ;
  wire [78:0] \ddr_ram_mux.u_bmuxc.bus_mux_typec.nx ;
  wire \ddr_ram_mux.u_bmuxc.clk ;
  wire \ddr_ram_mux.u_bmuxc.m1_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.m1_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m1_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m1_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m1_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.m1_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m1_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m1_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.m1_lock ;
  wire \ddr_ram_mux.u_bmuxc.m1_o[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m1_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.m2_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.m2_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m2_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m2_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m2_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.m2_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m2_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m2_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.m2_o[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m2_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.m3_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m3_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m3_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m3_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.m3_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m3_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m3_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.m3_lock ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m3_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.m4_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m4_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m4_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m4_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.m4_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m4_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m4_i[wr] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m4_o[d] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m5_i[a] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[bgrp] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[burst16] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[burst32] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m5_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[en] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m5_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[wr] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m5_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.m6_ddrburst ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.m6_i ;
  wire [70:0] \ddr_ram_mux.u_bmuxc.m6_o ;
  wire \ddr_ram_mux.u_bmuxc.mem_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.mem_ddrburst ;
  wire \ddr_ram_mux.u_bmuxc.mem_i[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mem_i[d] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mem_o[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mem_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mem_o[en] ;
  wire \ddr_ram_mux.u_bmuxc.mem_o[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mem_o[we] ;
  wire \ddr_ram_mux.u_bmuxc.mem_o[wr] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.A ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[0].B_AND_BITS ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[1].B_AND_BITS ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[2].B_AND_BITS ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[3].B_AND_BITS ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.S ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6974.Y ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.:7075.A ;
  wire [1:0] \ddr_ram_mux.u_bmuxc.mux_m6.:7075.B ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y ;
  wire [70:0] \ddr_ram_mux.u_bmuxc.mux_m6.:7078.A ;
  wire [141:0] \ddr_ram_mux.u_bmuxc.mux_m6.:7078.B ;
  wire [70:0] \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y ;
  wire [90:0] \ddr_ram_mux.u_bmuxc.mux_m6.bus_mux_typecsub.nx ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.clk ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_lock ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_o[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m1_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_o[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m2_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_lock ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m3_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m4_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[wr] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m4_o[d] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[a] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[bgrp] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[burst16] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[burst32] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[en] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[wr] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m5_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_ddrburst ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[d] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[wr] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.rst ;
  wire [90:0] \ddr_ram_mux.u_bmuxc.mux_m6.this_c ;
  wire [90:0] \ddr_ram_mux.u_bmuxc.mux_m6.this_r ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.mux_m6:3014 ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6:3015 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.mux_m6:3016 ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6:3017 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.mux_m6:3018 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.mux_m6:3020 ;
  wire [70:0] \ddr_ram_mux.u_bmuxc.mux_m6:3024 ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6:3025 ;
  wire \ddr_ram_mux.u_bmuxc.rst ;
  wire [78:0] \ddr_ram_mux.u_bmuxc.this_c ;
  wire [78:0] \ddr_ram_mux.u_bmuxc.this_r ;
  wire [32:0] \ddr_ram_mux.u_bmuxc:484 ;
  wire \ddr_ram_mux.u_bmuxc:485 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc:487 ;
  wire \ddr_ram_mux.u_bmuxc:488 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc:497 ;
  wire [70:0] \ddr_ram_mux.u_bmuxc:498 ;
  wire \ddr_ram_mux.u_bmuxc:499 ;
  wire [32:0] \ddr_ram_mux.u_dcache:452 ;
  wire [70:0] \ddr_ram_mux.u_dcache:455 ;
  wire \ddr_ram_mux.u_dcache:457 ;
  wire [16:0] \ddr_ram_mux.u_icache:430 ;
  wire [70:0] \ddr_ram_mux.u_icache:431 ;
  wire \ddr_ram_mux.u_icache:432 ;
  wire [51:0] debug_i;
  wire [72:0] dma_dbus_o;
  wire fl_miso;
  wire flash_ack_r;
  wire flash_bst;
  wire [70:0] flash_req;
  wire [32:0] flash_resp;
  input [31:0] gpio_di;
  wire [31:0] gpio_di;
  output [31:0] gpio_do;
  wire [31:0] gpio_do;
  output qfl_cs_n;
  wire qfl_cs_n;
  input [3:0] qfl_io_i;
  wire [3:0] qfl_io_i;
  output [3:0] qfl_io_o;
  wire [3:0] qfl_io_o;
  output [3:0] qfl_io_oe;
  wire [3:0] qfl_io_oe;
  output qfl_sck;
  wire qfl_sck;
  input reset;
  wire reset;
  output [12:0] sd_cmd_a ;
  wire [12:0] sd_cmd_a ;
  output [1:0] sd_cmd_ba ;
  wire [1:0] sd_cmd_ba ;
  output sd_cmd_cas_n ;
  wire sd_cmd_cas_n ;
  output sd_cmd_cke ;
  wire sd_cmd_cke ;
  output sd_cmd_cs_n ;
  wire sd_cmd_cs_n ;
  output [1:0] sd_cmd_dqm ;
  wire [1:0] sd_cmd_dqm ;
  output sd_cmd_ras_n ;
  wire sd_cmd_ras_n ;
  output sd_cmd_we_n ;
  wire sd_cmd_we_n ;
  input [15:0] sd_dq_i;
  wire [15:0] sd_dq_i;
  output [15:0] sd_dq_o;
  wire [15:0] sd_dq_o;
  output sd_dq_oe;
  wire sd_dq_oe;
  wire sdram_ack_r;
  wire sdram_bst;
  wire [70:0] sdram_req;
  wire [32:0] sdram_resp;
  output spi2_clk;
  wire spi2_clk;
  output [1:0] spi2_cs;
  wire [1:0] spi2_cs;
  input spi2_miso;
  wire spi2_miso;
  output spi2_mosi;
  wire spi2_mosi;
  input uart0_rx;
  wire uart0_rx;
  output uart0_tx;
  wire uart0_tx;
  assign _006_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.this_r [0];
  assign _007_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] & ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [1]);
  assign _008_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [2] | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3];
  assign _009_ = _007_ & ~(_008_);
  assign _010_ = ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [2] | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3]);
  assign _011_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] | ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [1]);
  assign _012_ = _010_ & ~(_011_);
  assign _013_ = ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] & \ddr_ram_mux.u_bmuxc.mux_m6.this_r [1]);
  assign _014_ = _010_ & ~(_013_);
  assign _015_ = _014_ | _012_;
  assign _016_ = _015_ & ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] );
  assign _017_ = ~(_016_ | _009_);
  assign _018_ = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  | \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] ;
  assign _019_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3] | ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [2]);
  assign _020_ = _019_ | ~(_007_);
  assign _021_ = _020_ | _018_;
  assign _022_ = _019_ | _013_;
  assign _023_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [1];
  assign _024_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [2] | ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [3]);
  assign _025_ = ~(_024_ | _023_);
  assign _026_ = _025_ | ~(_022_);
  assign _027_ = _007_ & ~(_024_);
  assign _028_ = _027_ & ~(_018_);
  assign _029_ = ~(_028_ | _026_);
  assign _030_ = ~(_029_ & _021_);
  assign _031_ = _017_ & ~(_030_);
  assign _032_ = _023_ | _008_;
  assign _033_ = _032_ & ~(_009_);
  assign _034_ = _023_ | _019_;
  assign _035_ = _015_ | ~(_034_);
  assign _036_ = _033_ & ~(_035_);
  assign _037_ = ~(_019_ | _011_);
  assign _038_ = _037_ | ~(_020_);
  assign _039_ = _027_ | _026_;
  assign _040_ = _039_ | _038_;
  assign _041_ = _036_ & ~(_040_);
  assign _042_ = _041_ | _031_;
  assign _043_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [89] | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [88];
  assign _044_ = _043_ | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [90];
  assign _045_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [87] | ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [16]);
  assign _046_ = _045_ | _009_;
  assign _047_ = _046_ | _012_;
  assign _048_ = _047_ | _037_;
  assign _049_ = _022_ & ~(_048_);
  assign _050_ = _049_ | _044_;
  assign _051_ = _050_ ? _006_ : _042_;
  assign _052_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.this_r [1];
  assign _053_ = _037_ | _026_;
  assign _054_ = ~(_053_ | _016_);
  assign _055_ = _054_ | _041_;
  assign _056_ = _050_ ? _052_ : _055_;
  assign _057_ = ~(_056_ & _051_);
  assign _058_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.this_r [2];
  assign _059_ = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] );
  assign _060_ = _032_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] );
  assign _061_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] ;
  assign _062_ = _061_ & ~(_034_);
  assign _063_ = _060_ & ~(_062_);
  assign _064_ = _061_ & ~(_020_);
  assign _065_ = _064_ | _037_;
  assign _066_ = _027_ & ~(_059_);
  assign _067_ = _066_ | _065_;
  assign _068_ = _063_ & ~(_067_);
  assign _069_ = _041_ ? _059_ : _068_;
  assign _070_ = _050_ ? _058_ : _069_;
  assign _071_ = _015_ & ~(_018_);
  assign _072_ = _029_ & ~(_071_);
  assign _073_ = ~(_072_ | _041_);
  assign _074_ = _050_ ? \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3] : _073_;
  assign _075_ = _070_ & ~(_074_);
  assign _076_ = _057_ | ~(_075_);
  assign _077_ = ~(_054_ | _041_);
  assign _078_ = _050_ ? \ddr_ram_mux.u_bmuxc.mux_m6.this_r [1] : _077_;
  assign _079_ = _078_ | _051_;
  assign _080_ = _075_ & ~(_079_);
  assign _081_ = _076_ & ~(_080_);
  assign _082_ = ~(_078_ & _051_);
  assign _083_ = _075_ & ~(_082_);
  assign _084_ = _081_ & ~(_083_);
  assign _085_ = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  & ~(_084_);
  assign _086_ = _074_ | _070_;
  assign _087_ = _086_ | _057_;
  assign _088_ = _056_ | _051_;
  assign _089_ = _075_ & ~(_088_);
  assign _090_ = _087_ & ~(_089_);
  assign _091_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en]  & ~(_090_);
  assign _092_ = _091_ | _085_;
  assign _093_ = _090_ & _084_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en]  = _092_ & ~(_093_);
  assign _094_ = \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en]  | \ddr_ram_mux.u_bmuxc.this_r [0];
  assign _095_ = \ddr_ram_mux.u_bmuxc.this_r [77] | \ddr_ram_mux.u_bmuxc.this_r [76];
  assign _096_ = _095_ | \ddr_ram_mux.u_bmuxc.this_r [78];
  assign _097_ = \ddr_ram_mux.u_bmuxc.this_r [4] & ~(\ddr_ram_mux.u_bmuxc.this_r [75]);
  assign _098_ = _097_ | _096_;
  assign \ddr_ram_mux.u_bmuxc.this_c [0] = _098_ ? \ddr_ram_mux.u_bmuxc.this_r [0] : _094_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  = \ddr_ram_mux.u_bmuxc.this_c [0] & \ddr_ram_mux.u_bmuxc.mem_i[ack] ;
  assign _099_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.this_r [88];
  assign _100_ = \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst  & ~(_084_);
  assign _101_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst  & ~(_087_);
  assign _102_ = ~(_101_ | _100_);
  assign _103_ = _087_ & _084_;
  assign _104_ = ~(_103_ | _102_);
  assign _003_ = _044_ ? _099_ : _104_;
  assign _004_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [89] ^ \ddr_ram_mux.u_bmuxc.mux_m6.this_r [88];
  assign _105_ = ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [89] & \ddr_ram_mux.u_bmuxc.mux_m6.this_r [88]);
  assign _106_ = _105_ ^ \ddr_ram_mux.u_bmuxc.mux_m6.this_r [90];
  assign _005_ = _044_ & ~(_106_);
  assign ddr_burst = _104_ & \ddr_ram_mux.u_bmuxc.this_c [0];
  assign _107_ = ~\ddr_ram_mux.u_bmuxc.this_r [76];
  assign _000_ = _096_ ? _107_ : ddr_burst;
  assign _001_ = \ddr_ram_mux.u_bmuxc.this_r [77] ^ \ddr_ram_mux.u_bmuxc.this_r [76];
  assign _108_ = ~(\ddr_ram_mux.u_bmuxc.this_r [77] & \ddr_ram_mux.u_bmuxc.this_r [76]);
  assign _109_ = _108_ ^ \ddr_ram_mux.u_bmuxc.this_r [78];
  assign _002_ = _096_ & ~(_109_);
  assign \ddr_ram_mux.ddr_bus_o[en]  = \ddr_ram_mux.u_bmuxc.this_c [0] & \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] ;
  assign _110_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [0]);
  assign _111_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [0] & ~(_090_);
  assign _112_ = _110_ & ~(_111_);
  assign _113_ = _112_ | _093_;
  assign ddr_bus_o[1] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_113_);
  assign _114_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [1]);
  assign _115_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [1] & ~(_090_);
  assign _116_ = _114_ & ~(_115_);
  assign _117_ = _116_ | _093_;
  assign ddr_bus_o[2] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_117_);
  assign _118_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [2]);
  assign _119_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [2] & ~(_090_);
  assign _120_ = _118_ & ~(_119_);
  assign _121_ = _120_ | _093_;
  assign ddr_bus_o[3] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_121_);
  assign _122_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [3]);
  assign _123_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [3] & ~(_090_);
  assign _124_ = _122_ & ~(_123_);
  assign _125_ = _124_ | _093_;
  assign ddr_bus_o[4] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_125_);
  assign _126_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [4]);
  assign _127_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [4] & ~(_090_);
  assign _128_ = _126_ & ~(_127_);
  assign _129_ = _128_ | _093_;
  assign ddr_bus_o[5] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_129_);
  assign _130_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [5]);
  assign _131_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [5] & ~(_090_);
  assign _132_ = _130_ & ~(_131_);
  assign _133_ = _132_ | _093_;
  assign ddr_bus_o[6] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_133_);
  assign _134_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [6]);
  assign _135_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [6] & ~(_090_);
  assign _136_ = _134_ & ~(_135_);
  assign _137_ = _136_ | _093_;
  assign ddr_bus_o[7] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_137_);
  assign _138_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [7]);
  assign _139_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [7] & ~(_090_);
  assign _140_ = _138_ & ~(_139_);
  assign _141_ = _140_ | _093_;
  assign ddr_bus_o[8] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_141_);
  assign _142_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [8]);
  assign _143_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [8] & ~(_090_);
  assign _144_ = _142_ & ~(_143_);
  assign _145_ = _144_ | _093_;
  assign ddr_bus_o[9] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_145_);
  assign _146_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [9]);
  assign _147_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [9] & ~(_090_);
  assign _148_ = _146_ & ~(_147_);
  assign _149_ = _148_ | _093_;
  assign ddr_bus_o[10] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_149_);
  assign _150_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [10]);
  assign _151_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [10] & ~(_090_);
  assign _152_ = _150_ & ~(_151_);
  assign _153_ = _152_ | _093_;
  assign ddr_bus_o[11] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_153_);
  assign _154_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [11]);
  assign _155_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [11] & ~(_090_);
  assign _156_ = _154_ & ~(_155_);
  assign _157_ = _156_ | _093_;
  assign ddr_bus_o[12] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_157_);
  assign _158_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [12]);
  assign _159_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [12] & ~(_090_);
  assign _160_ = _158_ & ~(_159_);
  assign _161_ = _160_ | _093_;
  assign ddr_bus_o[13] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_161_);
  assign _162_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [13]);
  assign _163_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [13] & ~(_090_);
  assign _164_ = _162_ & ~(_163_);
  assign _165_ = _164_ | _093_;
  assign ddr_bus_o[14] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_165_);
  assign _166_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [14]);
  assign _167_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [14] & ~(_090_);
  assign _168_ = _166_ & ~(_167_);
  assign _169_ = _168_ | _093_;
  assign ddr_bus_o[15] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_169_);
  assign _170_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [15]);
  assign _171_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [15] & ~(_090_);
  assign _172_ = _170_ & ~(_171_);
  assign _173_ = _172_ | _093_;
  assign ddr_bus_o[16] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_173_);
  assign _174_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [16]);
  assign _175_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [16] & ~(_090_);
  assign _176_ = _174_ & ~(_175_);
  assign _177_ = _176_ | _093_;
  assign ddr_bus_o[17] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_177_);
  assign _178_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [17]);
  assign _179_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [17] & ~(_090_);
  assign _180_ = _178_ & ~(_179_);
  assign _181_ = _180_ | _093_;
  assign ddr_bus_o[18] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_181_);
  assign _182_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [18]);
  assign _183_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [18] & ~(_090_);
  assign _184_ = _182_ & ~(_183_);
  assign _185_ = _184_ | _093_;
  assign ddr_bus_o[19] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_185_);
  assign _186_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [19]);
  assign _187_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [19] & ~(_090_);
  assign _188_ = _186_ & ~(_187_);
  assign _189_ = _188_ | _093_;
  assign ddr_bus_o[20] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_189_);
  assign _190_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [20]);
  assign _191_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [20] & ~(_090_);
  assign _192_ = _190_ & ~(_191_);
  assign _193_ = _192_ | _093_;
  assign ddr_bus_o[21] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_193_);
  assign _194_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [21]);
  assign _195_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [21] & ~(_090_);
  assign _196_ = _194_ & ~(_195_);
  assign _197_ = _196_ | _093_;
  assign ddr_bus_o[22] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_197_);
  assign _198_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [22]);
  assign _199_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [22] & ~(_090_);
  assign _200_ = _198_ & ~(_199_);
  assign _201_ = _200_ | _093_;
  assign ddr_bus_o[23] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_201_);
  assign _202_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [23]);
  assign _203_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [23] & ~(_090_);
  assign _204_ = _202_ & ~(_203_);
  assign _205_ = _204_ | _093_;
  assign ddr_bus_o[24] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_205_);
  assign _206_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [24]);
  assign _207_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [24] & ~(_090_);
  assign _208_ = _206_ & ~(_207_);
  assign _209_ = _208_ | _093_;
  assign ddr_bus_o[25] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_209_);
  assign _210_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [25]);
  assign _211_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [25] & ~(_090_);
  assign _212_ = _210_ & ~(_211_);
  assign _213_ = _212_ | _093_;
  assign ddr_bus_o[26] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_213_);
  assign _214_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [26]);
  assign _215_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [26] & ~(_090_);
  assign _216_ = _214_ & ~(_215_);
  assign _217_ = _216_ | _093_;
  assign ddr_bus_o[27] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_217_);
  assign _218_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [27]);
  assign _219_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [27] & ~(_090_);
  assign _220_ = _218_ & ~(_219_);
  assign _221_ = _220_ | _093_;
  assign ddr_bus_o[28] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_221_);
  assign _222_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [28]);
  assign _223_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [28] & ~(_090_);
  assign _224_ = _222_ & ~(_223_);
  assign _225_ = _224_ | _093_;
  assign ddr_bus_o[29] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_225_);
  assign _226_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [29]);
  assign _227_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [29] & ~(_090_);
  assign _228_ = _226_ & ~(_227_);
  assign _229_ = _228_ | _093_;
  assign ddr_bus_o[30] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_229_);
  assign _230_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [30]);
  assign _231_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [30] & ~(_090_);
  assign _232_ = _230_ & ~(_231_);
  assign _233_ = _232_ | _093_;
  assign ddr_bus_o[31] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_233_);
  assign _234_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [31]);
  assign _235_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [31] & ~(_090_);
  assign _236_ = _234_ & ~(_235_);
  assign _237_ = _236_ | _093_;
  assign ddr_bus_o[32] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_237_);
  assign _238_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] );
  assign _239_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd]  & ~(_090_);
  assign _240_ = _238_ & ~(_239_);
  assign _241_ = _240_ | _093_;
  assign \ddr_ram_mux.ddr_bus_o[rd]  = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_241_);
  assign _242_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] );
  assign _243_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr]  & ~(_090_);
  assign _244_ = _242_ & ~(_243_);
  assign _245_ = _244_ | _093_;
  assign \ddr_ram_mux.ddr_bus_o[wr]  = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_245_);
  assign _246_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] [0]);
  assign _247_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] [0] & ~(_090_);
  assign _248_ = _246_ & ~(_247_);
  assign _249_ = _248_ | _093_;
  assign ddr_bus_o[35] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_249_);
  assign _250_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] [1]);
  assign _251_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] [1] & ~(_090_);
  assign _252_ = _250_ & ~(_251_);
  assign _253_ = _252_ | _093_;
  assign ddr_bus_o[36] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_253_);
  assign _254_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] [2]);
  assign _255_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] [2] & ~(_090_);
  assign _256_ = _254_ & ~(_255_);
  assign _257_ = _256_ | _093_;
  assign ddr_bus_o[37] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_257_);
  assign _258_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] [3]);
  assign _259_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] [3] & ~(_090_);
  assign _260_ = _258_ & ~(_259_);
  assign _261_ = _260_ | _093_;
  assign ddr_bus_o[38] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_261_);
  assign _262_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [0]);
  assign _263_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [0] & ~(_090_);
  assign _264_ = _262_ & ~(_263_);
  assign _265_ = _264_ | _093_;
  assign ddr_bus_o[39] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_265_);
  assign _266_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [1]);
  assign _267_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [1] & ~(_090_);
  assign _268_ = _266_ & ~(_267_);
  assign _269_ = _268_ | _093_;
  assign ddr_bus_o[40] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_269_);
  assign _270_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [2]);
  assign _271_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [2] & ~(_090_);
  assign _272_ = _270_ & ~(_271_);
  assign _273_ = _272_ | _093_;
  assign ddr_bus_o[41] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_273_);
  assign _274_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [3]);
  assign _275_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [3] & ~(_090_);
  assign _276_ = _274_ & ~(_275_);
  assign _277_ = _276_ | _093_;
  assign ddr_bus_o[42] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_277_);
  assign _278_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [4]);
  assign _279_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [4] & ~(_090_);
  assign _280_ = _278_ & ~(_279_);
  assign _281_ = _280_ | _093_;
  assign ddr_bus_o[43] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_281_);
  assign _282_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [5]);
  assign _283_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [5] & ~(_090_);
  assign _284_ = _282_ & ~(_283_);
  assign _285_ = _284_ | _093_;
  assign ddr_bus_o[44] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_285_);
  assign _286_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [6]);
  assign _287_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [6] & ~(_090_);
  assign _288_ = _286_ & ~(_287_);
  assign _289_ = _288_ | _093_;
  assign ddr_bus_o[45] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_289_);
  assign _290_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [7]);
  assign _291_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [7] & ~(_090_);
  assign _292_ = _290_ & ~(_291_);
  assign _293_ = _292_ | _093_;
  assign ddr_bus_o[46] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_293_);
  assign _294_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [8]);
  assign _295_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [8] & ~(_090_);
  assign _296_ = _294_ & ~(_295_);
  assign _297_ = _296_ | _093_;
  assign ddr_bus_o[47] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_297_);
  assign _298_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [9]);
  assign _299_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [9] & ~(_090_);
  assign _300_ = _298_ & ~(_299_);
  assign _301_ = _300_ | _093_;
  assign ddr_bus_o[48] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_301_);
  assign _302_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [10]);
  assign _303_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [10] & ~(_090_);
  assign _304_ = _302_ & ~(_303_);
  assign _305_ = _304_ | _093_;
  assign ddr_bus_o[49] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_305_);
  assign _306_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [11]);
  assign _307_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [11] & ~(_090_);
  assign _308_ = _306_ & ~(_307_);
  assign _309_ = _308_ | _093_;
  assign ddr_bus_o[50] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_309_);
  assign _310_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [12]);
  assign _311_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [12] & ~(_090_);
  assign _312_ = _310_ & ~(_311_);
  assign _313_ = _312_ | _093_;
  assign ddr_bus_o[51] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_313_);
  assign _314_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [13]);
  assign _315_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [13] & ~(_090_);
  assign _316_ = _314_ & ~(_315_);
  assign _317_ = _316_ | _093_;
  assign ddr_bus_o[52] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_317_);
  assign _318_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [14]);
  assign _319_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [14] & ~(_090_);
  assign _320_ = _318_ & ~(_319_);
  assign _321_ = _320_ | _093_;
  assign ddr_bus_o[53] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_321_);
  assign _322_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [15]);
  assign _323_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [15] & ~(_090_);
  assign _324_ = _322_ & ~(_323_);
  assign _325_ = _324_ | _093_;
  assign ddr_bus_o[54] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_325_);
  assign _326_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [16]);
  assign _327_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [16] & ~(_090_);
  assign _328_ = _326_ & ~(_327_);
  assign _329_ = _328_ | _093_;
  assign ddr_bus_o[55] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_329_);
  assign _330_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [17]);
  assign _331_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [17] & ~(_090_);
  assign _332_ = _330_ & ~(_331_);
  assign _333_ = _332_ | _093_;
  assign ddr_bus_o[56] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_333_);
  assign _334_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [18]);
  assign _335_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [18] & ~(_090_);
  assign _336_ = _334_ & ~(_335_);
  assign _337_ = _336_ | _093_;
  assign ddr_bus_o[57] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_337_);
  assign _338_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [19]);
  assign _339_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [19] & ~(_090_);
  assign _340_ = _338_ & ~(_339_);
  assign _341_ = _340_ | _093_;
  assign ddr_bus_o[58] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_341_);
  assign _342_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [20]);
  assign _343_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [20] & ~(_090_);
  assign _344_ = _342_ & ~(_343_);
  assign _345_ = _344_ | _093_;
  assign ddr_bus_o[59] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_345_);
  assign _346_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [21]);
  assign _347_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [21] & ~(_090_);
  assign _348_ = _346_ & ~(_347_);
  assign _349_ = _348_ | _093_;
  assign ddr_bus_o[60] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_349_);
  assign _350_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [22]);
  assign _351_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [22] & ~(_090_);
  assign _352_ = _350_ & ~(_351_);
  assign _353_ = _352_ | _093_;
  assign ddr_bus_o[61] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_353_);
  assign _354_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [23]);
  assign _355_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [23] & ~(_090_);
  assign _356_ = _354_ & ~(_355_);
  assign _357_ = _356_ | _093_;
  assign ddr_bus_o[62] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_357_);
  assign _358_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [24]);
  assign _359_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [24] & ~(_090_);
  assign _360_ = _358_ & ~(_359_);
  assign _361_ = _360_ | _093_;
  assign ddr_bus_o[63] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_361_);
  assign _362_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [25]);
  assign _363_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [25] & ~(_090_);
  assign _364_ = _362_ & ~(_363_);
  assign _365_ = _364_ | _093_;
  assign ddr_bus_o[64] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_365_);
  assign _366_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [26]);
  assign _367_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [26] & ~(_090_);
  assign _368_ = _366_ & ~(_367_);
  assign _369_ = _368_ | _093_;
  assign ddr_bus_o[65] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_369_);
  assign _370_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [27]);
  assign _371_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [27] & ~(_090_);
  assign _372_ = _370_ & ~(_371_);
  assign _373_ = _372_ | _093_;
  assign ddr_bus_o[66] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_373_);
  assign _374_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [28]);
  assign _375_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [28] & ~(_090_);
  assign _376_ = _374_ & ~(_375_);
  assign _377_ = _376_ | _093_;
  assign ddr_bus_o[67] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_377_);
  assign _378_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [29]);
  assign _379_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [29] & ~(_090_);
  assign _380_ = _378_ & ~(_379_);
  assign _381_ = _380_ | _093_;
  assign ddr_bus_o[68] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_381_);
  assign _382_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [30]);
  assign _383_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [30] & ~(_090_);
  assign _384_ = _382_ & ~(_383_);
  assign _385_ = _384_ | _093_;
  assign ddr_bus_o[69] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_385_);
  assign _386_ = _084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [31]);
  assign _387_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [31] & ~(_090_);
  assign _388_ = _386_ & ~(_387_);
  assign _389_ = _388_ | _093_;
  assign ddr_bus_o[70] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_389_);
  assign _390_ = ~_051_;
  assign _391_ = ~(_086_ | _082_);
  assign _392_ = ~(_391_ | _080_);
  assign _393_ = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  | _051_;
  assign _394_ = _080_ & ~(_393_);
  assign _395_ = _051_ & ~(\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] );
  assign _396_ = _391_ & ~(_395_);
  assign _397_ = _396_ | _394_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [0] = _392_ ? _390_ : _397_;
  assign _398_ = _056_ & ~(\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] );
  assign _399_ = _080_ & ~(_398_);
  assign _400_ = _391_ & ~(_398_);
  assign _401_ = _400_ | _399_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [1] = _392_ ? _078_ : _401_;
  assign _402_ = ~_070_;
  assign _403_ = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  | _070_;
  assign _404_ = _080_ & ~(_403_);
  assign _405_ = _070_ & ~(\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] );
  assign _406_ = _391_ & ~(_405_);
  assign _407_ = _406_ | _404_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [2] = _392_ ? _402_ : _407_;
  assign _408_ = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  | ~(_074_);
  assign _409_ = _080_ & ~(_408_);
  assign _410_ = _391_ & ~(_408_);
  assign _411_ = _410_ | _409_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [3] = _392_ ? _074_ : _411_;
  assign \ddr_ram_mux.u_bmuxc.m1_o[ack]  = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  & ~(_084_);
  assign _412_ = ~(\ddr_ram_mux.u_bmuxc.this_c [0] & \ddr_ram_mux.u_bmuxc.mem_ack_r );
  assign \ddr_ram_mux.data_dbus_ack_r  = ~(_412_ | _084_);
  assign \ddr_ram_mux.u_bmuxc.m2_o[ack]  = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  & ~(_090_);
  assign \ddr_ram_mux.instr_dbus_ack_r  = ~(_412_ | _090_);
  always @(posedge clk_sys)
    \aic_irq_gen.sync [0] <= gpio_di[1];
  always @(posedge clk_sys)
    \aic_irq_gen.sync [1] <= \aic_irq_gen.sync [0];
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[0]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[0]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[0]  <= \ddr_ram_mux.u_bmuxc.mux_m6.this_c [0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[0] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[1]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[1]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[1]  <= \ddr_ram_mux.u_bmuxc.mux_m6.this_c [1];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [1] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[1] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[2]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[2]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[2]  <= \ddr_ram_mux.u_bmuxc.mux_m6.this_c [2];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [2] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[2] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[3]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[3]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[3]  <= \ddr_ram_mux.u_bmuxc.mux_m6.this_c [3];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[3] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[16]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[16]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[16]  <= \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [16] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[16] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[87]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[87]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[87]  <= \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [87] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[87] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[88]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[88]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[88]  <= _003_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [88] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[88] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[89]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[89]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[89]  <= _004_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [89] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[89] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[90]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[90]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[90]  <= _005_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [90] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[90] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[0]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[0]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.this_r_reg[0]  <= \ddr_ram_mux.u_bmuxc.this_c [0];
  assign \ddr_ram_mux.u_bmuxc.this_r [0] = \ddr_ram_mux.u_bmuxc.this_r_reg[0] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[4]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[4]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.this_r_reg[4]  <= \ddr_ram_mux.ddr_bus_o[en] ;
  assign \ddr_ram_mux.u_bmuxc.this_r [4] = \ddr_ram_mux.u_bmuxc.this_r_reg[4] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[75]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[75]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.this_r_reg[75]  <= \ddr_ram_mux.u_bmuxc.mem_i[ack] ;
  assign \ddr_ram_mux.u_bmuxc.this_r [75] = \ddr_ram_mux.u_bmuxc.this_r_reg[75] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[76]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[76]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.this_r_reg[76]  <= _000_;
  assign \ddr_ram_mux.u_bmuxc.this_r [76] = \ddr_ram_mux.u_bmuxc.this_r_reg[76] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[77]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[77]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.this_r_reg[77]  <= _001_;
  assign \ddr_ram_mux.u_bmuxc.this_r [77] = \ddr_ram_mux.u_bmuxc.this_r_reg[77] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[78]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[78]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.this_r_reg[78]  <= _002_;
  assign \ddr_ram_mux.u_bmuxc.this_r [78] = \ddr_ram_mux.u_bmuxc.this_r_reg[78] ;
  cpus cpus (
    .clk(clk_sys),
    .cpu0_copro_i_ack (1'h1),
    .cpu0_copro_i_d (32'd0),
    .cpu0_copro_i_exc (1'h0),
    .cpu0_copro_i_t (1'h0),
    .cpu0_copro_o_d (_424_),
    .cpu0_copro_o_en (_428_),
    .cpu0_copro_o_op (_427_),
    .cpu0_copro_o_rna (_425_),
    .cpu0_copro_o_rnb (_426_),
    .cpu0_copro_o_stallcp (_429_),
    .cpu0_data_master_ack(_418_),
    .cpu0_data_master_en(_416_),
    .cpu0_ddr_dbus_i_ack (\ddr_ram_mux.cpu0_dbus_i[ack] ),
    .cpu0_ddr_dbus_i_d (\ddr_ram_mux.cpu0_dbus_i[d] ),
    .cpu0_ddr_dbus_o_a (\ddr_ram_mux.cpu0_dbus_o[a] ),
    .cpu0_ddr_dbus_o_d (\ddr_ram_mux.cpu0_dbus_o[d] ),
    .cpu0_ddr_dbus_o_en (\ddr_ram_mux.cpu0_dbus_o[en] ),
    .cpu0_ddr_dbus_o_rd (\ddr_ram_mux.cpu0_dbus_o[rd] ),
    .cpu0_ddr_dbus_o_we (\ddr_ram_mux.cpu0_dbus_o[we] ),
    .cpu0_ddr_dbus_o_wr (\ddr_ram_mux.cpu0_dbus_o[wr] ),
    .cpu0_ddr_ibus_i_ack (\ddr_ram_mux.cpu0_ibus_i[ack] ),
    .cpu0_ddr_ibus_i_d (\ddr_ram_mux.cpu0_ibus_i[d] ),
    .cpu0_ddr_ibus_o_a (\ddr_ram_mux.cpu0_ibus_o[a] ),
    .cpu0_ddr_ibus_o_en (\ddr_ram_mux.cpu0_ibus_o[en] ),
    .cpu0_ddr_ibus_o_jp (\ddr_ram_mux.cpu0_ibus_o[jp] ),
    .cpu0_event_i_cmd (cpu0_event_i[2:1]),
    .cpu0_event_i_en (cpu0_event_i[0]),
    .cpu0_event_i_lvl (cpu0_event_i[15:12]),
    .cpu0_event_i_msk (cpu0_event_i[11]),
    .cpu0_event_i_vec (cpu0_event_i[10:3]),
    .cpu0_event_o_ack (cpu0_event_o[0]),
    .cpu0_event_o_dbg (cpu0_event_o[6]),
    .cpu0_event_o_lvl (cpu0_event_o[4:1]),
    .cpu0_event_o_slp (cpu0_event_o[5]),
    .cpu0_mem_lock(\ddr_ram_mux.cpu0_mem_lock ),
    .cpu0_periph_dbus_i_ack (cpu0_periph_dbus_i[32]),
    .cpu0_periph_dbus_i_d (cpu0_periph_dbus_i[31:0]),
    .cpu0_periph_dbus_o_a (cpu0_periph_dbus_o[32:1]),
    .cpu0_periph_dbus_o_d (cpu0_periph_dbus_o[70:39]),
    .cpu0_periph_dbus_o_en (cpu0_periph_dbus_o[0]),
    .cpu0_periph_dbus_o_rd (cpu0_periph_dbus_o[33]),
    .cpu0_periph_dbus_o_we (cpu0_periph_dbus_o[38:35]),
    .cpu0_periph_dbus_o_wr (cpu0_periph_dbus_o[34]),
    .cpu1_copro_i_ack (1'h1),
    .cpu1_copro_i_d (32'd0),
    .cpu1_copro_i_exc (1'h0),
    .cpu1_copro_i_t (1'h0),
    .cpu1_copro_o_d (_430_),
    .cpu1_copro_o_en (_434_),
    .cpu1_copro_o_op (_433_),
    .cpu1_copro_o_rna (_431_),
    .cpu1_copro_o_rnb (_432_),
    .cpu1_copro_o_stallcp (_435_),
    .cpu1_data_master_ack(_419_),
    .cpu1_data_master_en(_417_),
    .cpu1_ddr_dbus_i_ack (\ddr_ram_mux.cpu1_dbus_i[ack] ),
    .cpu1_ddr_dbus_i_d (32'd0),
    .cpu1_ddr_dbus_o_a (\ddr_ram_mux.cpu1_dbus_o[a] ),
    .cpu1_ddr_dbus_o_d (\ddr_ram_mux.cpu1_dbus_o[d] ),
    .cpu1_ddr_dbus_o_en (\ddr_ram_mux.cpu1_dbus_i[ack] ),
    .cpu1_ddr_dbus_o_rd (\ddr_ram_mux.cpu1_dbus_o[rd] ),
    .cpu1_ddr_dbus_o_we (\ddr_ram_mux.cpu1_dbus_o[we] ),
    .cpu1_ddr_dbus_o_wr (\ddr_ram_mux.cpu1_dbus_o[wr] ),
    .cpu1_ddr_ibus_i_ack (\ddr_ram_mux.cpu1_ibus_i[ack] ),
    .cpu1_ddr_ibus_i_d (16'h0000),
    .cpu1_ddr_ibus_o_a (\ddr_ram_mux.cpu1_ibus_o[a] ),
    .cpu1_ddr_ibus_o_en (\ddr_ram_mux.cpu1_ibus_i[ack] ),
    .cpu1_ddr_ibus_o_jp (\ddr_ram_mux.cpu1_ibus_o[jp] ),
    .cpu1_event_i_cmd (2'h0),
    .cpu1_event_i_en (1'h0),
    .cpu1_event_i_lvl (4'h0),
    .cpu1_event_i_msk (1'h0),
    .cpu1_event_i_vec (8'h00),
    .cpu1_event_o_ack (_420_),
    .cpu1_event_o_dbg (_423_),
    .cpu1_event_o_lvl (_421_),
    .cpu1_event_o_slp (_422_),
    .cpu1_mem_lock(cpu1_mem_lock),
    .cpu1_periph_dbus_i_ack (cpu1_periph_dbus_i[32]),
    .cpu1_periph_dbus_i_d (cpu1_periph_dbus_i[31:0]),
    .cpu1_periph_dbus_o_a (cpu1_periph_dbus_o[32:1]),
    .cpu1_periph_dbus_o_d (cpu1_periph_dbus_o[70:39]),
    .cpu1_periph_dbus_o_en (cpu1_periph_dbus_o[0]),
    .cpu1_periph_dbus_o_rd (cpu1_periph_dbus_o[33]),
    .cpu1_periph_dbus_o_we (cpu1_periph_dbus_o[38:35]),
    .cpu1_periph_dbus_o_wr (cpu1_periph_dbus_o[34]),
    .cpu1eni(1'h0),
    .debug_i_cmd (2'h0),
    .debug_i_d (32'd0),
    .debug_i_d_en (1'h0),
    .debug_i_en (1'h0),
    .debug_i_ir (16'h0000),
    .debug_o_ack (_413_),
    .debug_o_d (_414_),
    .debug_o_rdy (_415_),
    .fl_cs_n(_436_),
    .fl_miso(1'hx),
    .fl_mosi(_438_),
    .fl_sck(_437_),
    .rst(reset)
  );
  dcache_adapter \ddr_ram_mux.u_dcache  (
    .a_mmu_at (1'h0),
    .a_mmu_c (1'h0),
    .a_mmu_pa_tag (15'h0000),
    .clk125(clk_sys),
    .clk200(clk_sys),
    .ctrl_en (1'h1),
    .ctrl_inv (1'h0),
    .dbus_ack_r(\ddr_ram_mux.data_dbus_ack_r ),
    .dbus_ddrburst(\ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ),
    .dbus_i_ack (\ddr_ram_mux.u_bmuxc.m1_o[ack] ),
    .dbus_i_d (\ddr_ram_mux.ddr_bus_i[d] ),
    .dbus_lock(_441_),
    .dbus_o_a (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] ),
    .dbus_o_d (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] ),
    .dbus_o_en (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] ),
    .dbus_o_rd (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] ),
    .dbus_o_we (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] ),
    .dbus_o_wr (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] ),
    .ibus_i_ack (\ddr_ram_mux.cpu0_dbus_i[ack] ),
    .ibus_i_d (\ddr_ram_mux.cpu0_dbus_i[d] ),
    .ibus_o_a (\ddr_ram_mux.cpu0_dbus_o[a] ),
    .ibus_o_d (\ddr_ram_mux.cpu0_dbus_o[d] ),
    .ibus_o_en (\ddr_ram_mux.cpu0_dbus_o[en] ),
    .ibus_o_rd (\ddr_ram_mux.cpu0_dbus_o[rd] ),
    .ibus_o_we (\ddr_ram_mux.cpu0_dbus_o[we] ),
    .ibus_o_wr (\ddr_ram_mux.cpu0_dbus_o[wr] ),
    .lock(\ddr_ram_mux.cpu0_mem_lock ),
    .rst(reset),
    .snpc_i_al (23'h000000),
    .snpc_i_en (1'h0),
    .snpc_o_al (_439_),
    .snpc_o_en (_440_)
  );
  icache_adapter \ddr_ram_mux.u_icache  (
    .a_mmu_at (1'h0),
    .a_mmu_c (1'h0),
    .a_mmu_pa_tag (15'h0000),
    .clk125(clk_sys),
    .clk200(clk_sys),
    .ctrl_en (1'h1),
    .ctrl_inv (1'h0),
    .dbus_ack_r(\ddr_ram_mux.instr_dbus_ack_r ),
    .dbus_ddrburst(\ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ),
    .dbus_i_ack (\ddr_ram_mux.u_bmuxc.m2_o[ack] ),
    .dbus_i_d (\ddr_ram_mux.ddr_bus_i[d] ),
    .dbus_o_a (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] ),
    .dbus_o_d (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] ),
    .dbus_o_en (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] ),
    .dbus_o_rd (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] ),
    .dbus_o_we (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] ),
    .dbus_o_wr (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] ),
    .ibus_i_ack (\ddr_ram_mux.cpu0_ibus_i[ack] ),
    .ibus_i_d (\ddr_ram_mux.cpu0_ibus_i[d] ),
    .ibus_o_a (\ddr_ram_mux.cpu0_ibus_o[a] ),
    .ibus_o_en (\ddr_ram_mux.cpu0_ibus_o[en] ),
    .ibus_o_jp (\ddr_ram_mux.cpu0_ibus_o[jp] ),
    .rst(reset)
  );
  devices devices (
    .aic_irq({ 7'h00, \aic_irq_gen.sync [1] }),
    .clk_sys(clk_sys),
    .cpu0_event_i_cmd (cpu0_event_i[2:1]),
    .cpu0_event_i_en (cpu0_event_i[0]),
    .cpu0_event_i_lvl (cpu0_event_i[15:12]),
    .cpu0_event_i_msk (cpu0_event_i[11]),
    .cpu0_event_i_vec (cpu0_event_i[10:3]),
    .cpu0_event_o_ack (cpu0_event_o[0]),
    .cpu0_event_o_dbg (cpu0_event_o[6]),
    .cpu0_event_o_lvl (cpu0_event_o[4:1]),
    .cpu0_event_o_slp (cpu0_event_o[5]),
    .cpu0_periph_dbus_i_ack (cpu0_periph_dbus_i[32]),
    .cpu0_periph_dbus_i_d (cpu0_periph_dbus_i[31:0]),
    .cpu0_periph_dbus_o_a (cpu0_periph_dbus_o[32:1]),
    .cpu0_periph_dbus_o_d (cpu0_periph_dbus_o[70:39]),
    .cpu0_periph_dbus_o_en (cpu0_periph_dbus_o[0]),
    .cpu0_periph_dbus_o_rd (cpu0_periph_dbus_o[33]),
    .cpu0_periph_dbus_o_we (cpu0_periph_dbus_o[38:35]),
    .cpu0_periph_dbus_o_wr (cpu0_periph_dbus_o[34]),
    .cpu1_periph_dbus_i_ack (cpu1_periph_dbus_i[32]),
    .cpu1_periph_dbus_i_d (cpu1_periph_dbus_i[31:0]),
    .cpu1_periph_dbus_o_a (cpu1_periph_dbus_o[32:1]),
    .cpu1_periph_dbus_o_d (cpu1_periph_dbus_o[70:39]),
    .cpu1_periph_dbus_o_en (cpu1_periph_dbus_o[0]),
    .cpu1_periph_dbus_o_rd (cpu1_periph_dbus_o[33]),
    .cpu1_periph_dbus_o_we (cpu1_periph_dbus_o[38:35]),
    .cpu1_periph_dbus_o_wr (cpu1_periph_dbus_o[34]),
    .gpio_di(gpio_di),
    .gpio_do(gpio_do),
    .reset(reset),
    .spi2_clk(spi2_clk),
    .spi2_cs(spi2_cs),
    .spi2_miso(spi2_miso),
    .spi2_mosi(spi2_mosi),
    .uart0_rx(uart0_rx),
    .uart0_tx(uart0_tx)
  );
  mem_region_mux mem_region_mux (
    .ack_r(\ddr_ram_mux.u_bmuxc.mem_ack_r ),
    .bst(ddr_burst),
    .flash_ack_r(flash_ack_r),
    .flash_bst(flash_bst),
    .flash_req_a (flash_req[32:1]),
    .flash_req_d (flash_req[70:39]),
    .flash_req_en (flash_req[0]),
    .flash_req_rd (flash_req[33]),
    .flash_req_we (flash_req[38:35]),
    .flash_req_wr (flash_req[34]),
    .flash_resp_ack (flash_resp[32]),
    .flash_resp_d (flash_resp[31:0]),
    .req_a (ddr_bus_o[32:1]),
    .req_d (ddr_bus_o[70:39]),
    .req_en (\ddr_ram_mux.ddr_bus_o[en] ),
    .req_rd (\ddr_ram_mux.ddr_bus_o[rd] ),
    .req_we (ddr_bus_o[38:35]),
    .req_wr (\ddr_ram_mux.ddr_bus_o[wr] ),
    .resp_ack (\ddr_ram_mux.u_bmuxc.mem_i[ack] ),
    .resp_d (\ddr_ram_mux.ddr_bus_i[d] ),
    .sdram_ack_r(sdram_ack_r),
    .sdram_bst(sdram_bst),
    .sdram_req_a (sdram_req[32:1]),
    .sdram_req_d (sdram_req[70:39]),
    .sdram_req_en (sdram_req[0]),
    .sdram_req_rd (sdram_req[33]),
    .sdram_req_we (sdram_req[38:35]),
    .sdram_req_wr (sdram_req[34]),
    .sdram_resp_ack (sdram_resp[32]),
    .sdram_resp_d (sdram_resp[31:0])
  );
  qspi_flash_ctrl qspi_flash_ctrl (
    .ack_r(flash_ack_r),
    .bst(flash_bst),
    .clk(clk_sys),
    .db_i_a (flash_req[32:1]),
    .db_i_d (flash_req[70:39]),
    .db_i_en (flash_req[0]),
    .db_i_rd (flash_req[33]),
    .db_i_we (flash_req[38:35]),
    .db_i_wr (flash_req[34]),
    .db_o_ack (flash_resp[32]),
    .db_o_d (flash_resp[31:0]),
    .fl_cs_n(qfl_cs_n),
    .fl_io_i(qfl_io_i),
    .fl_io_o(qfl_io_o),
    .fl_io_oe(qfl_io_oe),
    .fl_sck(qfl_sck),
    .rst(reset)
  );
  sdram_ctrl sdram_ctrl (
    .ack_r(sdram_ack_r),
    .bst(sdram_bst),
    .clk(clk_sys),
    .cmd_a (sd_cmd_a ),
    .cmd_ba (sd_cmd_ba ),
    .cmd_cas_n (sd_cmd_cas_n ),
    .cmd_cke (sd_cmd_cke ),
    .cmd_cs_n (sd_cmd_cs_n ),
    .cmd_dqm (sd_cmd_dqm ),
    .cmd_ras_n (sd_cmd_ras_n ),
    .cmd_we_n (sd_cmd_we_n ),
    .dq_i(sd_dq_i),
    .dq_o(sd_dq_o),
    .dq_oe(sd_dq_oe),
    .req_a (sdram_req[32:1]),
    .req_d (sdram_req[70:39]),
    .req_en (sdram_req[0]),
    .req_rd (sdram_req[33]),
    .req_we (sdram_req[38:35]),
    .req_wr (sdram_req[34]),
    .resp_ack (sdram_resp[32]),
    .resp_d (sdram_resp[31:0]),
    .rst(reset)
  );
  assign aic_irq = \aic_irq_gen.sync [1];
  assign \aic_irq_gen.clk  = clk_sys;
  assign \aic_irq_gen.irq  = { 7'h00, \aic_irq_gen.sync [1] };
  assign \aic_irq_gen.pi_in  = gpio_di;
  assign cache01sel_ctrl_temp = 1'h0;
  assign cpu0_ddr_dbus_i = { \ddr_ram_mux.cpu0_dbus_i[ack] , \ddr_ram_mux.cpu0_dbus_i[d]  };
  assign cpu0_ddr_dbus_o = { \ddr_ram_mux.cpu0_dbus_o[d] , \ddr_ram_mux.cpu0_dbus_o[we] , \ddr_ram_mux.cpu0_dbus_o[wr] , \ddr_ram_mux.cpu0_dbus_o[rd] , \ddr_ram_mux.cpu0_dbus_o[a] , \ddr_ram_mux.cpu0_dbus_o[en]  };
  assign cpu0_ddr_ibus_i = { \ddr_ram_mux.cpu0_ibus_i[ack] , \ddr_ram_mux.cpu0_ibus_i[d]  };
  assign cpu0_ddr_ibus_o = { \ddr_ram_mux.cpu0_ibus_o[jp] , \ddr_ram_mux.cpu0_ibus_o[a] , \ddr_ram_mux.cpu0_ibus_o[en]  };
  assign cpu0_mem_lock = \ddr_ram_mux.cpu0_mem_lock ;
  assign cpu1_ddr_dbus_i = { \ddr_ram_mux.cpu1_dbus_i[ack] , 32'h00000000 };
  assign cpu1_ddr_dbus_o = { \ddr_ram_mux.cpu1_dbus_o[d] , \ddr_ram_mux.cpu1_dbus_o[we] , \ddr_ram_mux.cpu1_dbus_o[wr] , \ddr_ram_mux.cpu1_dbus_o[rd] , \ddr_ram_mux.cpu1_dbus_o[a] , \ddr_ram_mux.cpu1_dbus_i[ack]  };
  assign cpu1_ddr_ibus_i = { \ddr_ram_mux.cpu1_ibus_i[ack] , 16'h0000 };
  assign cpu1_ddr_ibus_o = { \ddr_ram_mux.cpu1_ibus_o[jp] , \ddr_ram_mux.cpu1_ibus_o[a] , \ddr_ram_mux.cpu1_ibus_i[ack]  };
  assign cpu1_event_i = 16'h0000;
  assign ddr_bus_ack_r = \ddr_ram_mux.u_bmuxc.mem_ack_r ;
  assign ddr_bus_i = { \ddr_ram_mux.u_bmuxc.mem_i[ack] , \ddr_ram_mux.ddr_bus_i[d]  };
  assign { ddr_bus_o[34:33], ddr_bus_o[0] } = { \ddr_ram_mux.ddr_bus_o[wr] , \ddr_ram_mux.ddr_bus_o[rd] , \ddr_ram_mux.ddr_bus_o[en]  };
  assign \ddr_ram_mux.cache01sel_ctrl_temp  = 1'h0;
  assign \ddr_ram_mux.clk  = clk_sys;
  assign \ddr_ram_mux.clk_ddr  = clk_sys;
  assign \ddr_ram_mux.cpu1_dbus_i[d]  = 32'd0;
  assign \ddr_ram_mux.cpu1_dbus_o[en]  = \ddr_ram_mux.cpu1_dbus_i[ack] ;
  assign \ddr_ram_mux.cpu1_ibus_i[d]  = 16'h0000;
  assign \ddr_ram_mux.cpu1_ibus_o[en]  = \ddr_ram_mux.cpu1_ibus_i[ack] ;
  assign \ddr_ram_mux.cpu1_mem_lock  = cpu1_mem_lock;
  assign \ddr_ram_mux.data_dbus_i  = { \ddr_ram_mux.u_bmuxc.m1_o[ack] , \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.data_dbus_o  = { \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  };
  assign \ddr_ram_mux.data_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ;
  assign \ddr_ram_mux.dcache0_ctrl[en]  = 1'h1;
  assign \ddr_ram_mux.dcache0_ctrl[inv]  = 1'h0;
  assign \ddr_ram_mux.dcache1_ctrl[en]  = 1'h1;
  assign \ddr_ram_mux.dcache1_ctrl[inv]  = 1'h0;
  assign \ddr_ram_mux.ddr_burst  = ddr_burst;
  assign \ddr_ram_mux.ddr_bus_ack_r  = \ddr_ram_mux.u_bmuxc.mem_ack_r ;
  assign \ddr_ram_mux.ddr_bus_i[ack]  = \ddr_ram_mux.u_bmuxc.mem_i[ack] ;
  assign \ddr_ram_mux.ddr_bus_o[a]  = ddr_bus_o[32:1];
  assign \ddr_ram_mux.ddr_bus_o[d]  = ddr_bus_o[70:39];
  assign \ddr_ram_mux.ddr_bus_o[we]  = ddr_bus_o[38:35];
  assign \ddr_ram_mux.dma_dbus_i[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.dma_dbus_o[a]  = 32'd0;
  assign \ddr_ram_mux.dma_dbus_o[bgrp]  = 1'h0;
  assign \ddr_ram_mux.dma_dbus_o[burst16]  = 1'h0;
  assign \ddr_ram_mux.dma_dbus_o[burst32]  = 1'h0;
  assign \ddr_ram_mux.dma_dbus_o[d]  = 32'd0;
  assign \ddr_ram_mux.dma_dbus_o[en]  = 1'h0;
  assign \ddr_ram_mux.dma_dbus_o[we]  = 4'h0;
  assign \ddr_ram_mux.dma_dbus_o[wr]  = 1'h0;
  assign \ddr_ram_mux.icache0_ctrl[en]  = 1'h1;
  assign \ddr_ram_mux.icache0_ctrl[inv]  = 1'h0;
  assign \ddr_ram_mux.icache1_ctrl[en]  = 1'h1;
  assign \ddr_ram_mux.icache1_ctrl[inv]  = 1'h0;
  assign \ddr_ram_mux.instr_dbus_i  = { \ddr_ram_mux.u_bmuxc.m2_o[ack] , \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.instr_dbus_o  = { \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en]  };
  assign \ddr_ram_mux.instr_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ;
  assign \ddr_ram_mux.rst  = reset;
  assign \ddr_ram_mux.u_bmuxc.bus_mux_typec.nx  = { 4'hx, ddr_bus_o[70:35], \ddr_ram_mux.ddr_bus_o[wr] , \ddr_ram_mux.ddr_bus_o[rd] , ddr_bus_o[32:1], \ddr_ram_mux.ddr_bus_o[en] , 2'h0, ddr_burst, \ddr_ram_mux.u_bmuxc.this_c [0] };
  assign \ddr_ram_mux.u_bmuxc.clk  = clk_sys;
  assign \ddr_ram_mux.u_bmuxc.m1_ack_r  = \ddr_ram_mux.data_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.m1_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[a]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[d]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[en]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[rd]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[we]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[wr]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] ;
  assign \ddr_ram_mux.u_bmuxc.m1_lock  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m1_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m2_ack_r  = \ddr_ram_mux.instr_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.m2_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[a]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[d]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[en]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[rd]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[we]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[wr]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] ;
  assign \ddr_ram_mux.u_bmuxc.m2_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m3_ddrburst  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[rd]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_lock  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m4_ddrburst  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[rd]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m5_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[bgrp]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[burst16]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[burst32]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m6_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y ;
  assign \ddr_ram_mux.u_bmuxc.m6_i  = { \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] , \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.u_bmuxc.m6_o  = { \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:1], \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en]  };
  assign \ddr_ram_mux.u_bmuxc.mem_ddrburst  = ddr_burst;
  assign \ddr_ram_mux.u_bmuxc.mem_i[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.mem_o[a]  = ddr_bus_o[32:1];
  assign \ddr_ram_mux.u_bmuxc.mem_o[d]  = ddr_bus_o[70:39];
  assign \ddr_ram_mux.u_bmuxc.mem_o[en]  = \ddr_ram_mux.ddr_bus_o[en] ;
  assign \ddr_ram_mux.u_bmuxc.mem_o[rd]  = \ddr_ram_mux.ddr_bus_o[rd] ;
  assign \ddr_ram_mux.u_bmuxc.mem_o[we]  = ddr_bus_o[38:35];
  assign \ddr_ram_mux.u_bmuxc.mem_o[wr]  = \ddr_ram_mux.ddr_bus_o[wr] ;
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.A [3], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.A [1:0] } = 3'h0;
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [30:19], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [17:0] } = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.A [2], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [31], 10'h2d8, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [31], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [18], 2'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [31], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [18], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [18], 5'h02, \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] , 2'h0 };
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [29:28], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [26:23], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [21:19], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [17], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [15], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [13:12], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [10], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [8:5], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [3], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [1:0] } = { 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [31], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [22], 7'h00, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [9], 6'h00 };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[0].B_AND_BITS  = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [31], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [16], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [9], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [4], 1'h0 };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[1].B_AND_BITS  = { 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [22], 2'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [9], 2'h0 };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[2].B_AND_BITS  = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [30], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [22], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [18], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [14], 2'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [2] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[3].B_AND_BITS  = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [31], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], 3'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [11], 2'h0 };
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.S [6:5], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.S [1] } = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [22], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [4] };
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B [3], \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B [1] } = { \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B [7], \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B [5] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6974.Y  = \ddr_ram_mux.u_bmuxc.mux_m6.this_c [3:0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7075.A  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7075.B  = { \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst , \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7078.A  = 71'h000000000000000000;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7078.B  = { \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [0] = \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] ;
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.bus_mux_typecsub.nx [90:8], \ddr_ram_mux.u_bmuxc.mux_m6.bus_mux_typecsub.nx [3:0] } = { 4'hx, \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:1], \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] , 3'bx00, \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y , 4'h0, \ddr_ram_mux.u_bmuxc.mux_m6.this_c [3:0] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.clk  = clk_sys;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m1_ack_r  = \ddr_ram_mux.data_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m1_lock  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m1_o[ack]  = \ddr_ram_mux.u_bmuxc.m1_o[ack] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m1_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m2_ack_r  = \ddr_ram_mux.instr_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m2_o[ack]  = \ddr_ram_mux.u_bmuxc.m2_o[ack] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m2_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_ddrburst  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[rd]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_lock  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_ddrburst  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[rd]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[bgrp]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[burst16]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[burst32]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_o[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[d]  = \ddr_ram_mux.ddr_bus_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[a]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [32:1];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[d]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:39];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[rd]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [33];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[we]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [38:35];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[wr]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [34];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.rst  = reset;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [90:8] = { 3'hx, \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] , \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:1], \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] , 3'bx00, \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y , 4'h0 };
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.this_r [15:13], \ddr_ram_mux.u_bmuxc.mux_m6.this_r [11:8] } = 7'h00;
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3014  = { \ddr_ram_mux.u_bmuxc.m1_o[ack] , \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3015  = \ddr_ram_mux.data_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3016  = { \ddr_ram_mux.u_bmuxc.m2_o[ack] , \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3017  = \ddr_ram_mux.instr_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3018  = { 1'hx, \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3020  = { 1'hx, \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3024  = { \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:1], \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en]  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3025  = \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y ;
  assign \ddr_ram_mux.u_bmuxc.rst  = reset;
  assign \ddr_ram_mux.u_bmuxc.this_c [78:1] = { 3'hx, \ddr_ram_mux.u_bmuxc.mem_i[ack] , ddr_bus_o[70:35], \ddr_ram_mux.ddr_bus_o[wr] , \ddr_ram_mux.ddr_bus_o[rd] , ddr_bus_o[32:1], \ddr_ram_mux.ddr_bus_o[en] , 2'h0, ddr_burst };
  assign \ddr_ram_mux.u_bmuxc.this_r [3:2] = 2'h0;
  assign \ddr_ram_mux.u_bmuxc:484  = { \ddr_ram_mux.u_bmuxc.m1_o[ack] , \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.u_bmuxc:485  = \ddr_ram_mux.data_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc:487  = { \ddr_ram_mux.u_bmuxc.m2_o[ack] , \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.u_bmuxc:488  = \ddr_ram_mux.instr_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc:497  = { 1'hx, \ddr_ram_mux.ddr_bus_i[d]  };
  assign \ddr_ram_mux.u_bmuxc:498  = { ddr_bus_o[70:35], \ddr_ram_mux.ddr_bus_o[wr] , \ddr_ram_mux.ddr_bus_o[rd] , ddr_bus_o[32:1], \ddr_ram_mux.ddr_bus_o[en]  };
  assign \ddr_ram_mux.u_bmuxc:499  = ddr_burst;
  assign \ddr_ram_mux.u_dcache:452  = { \ddr_ram_mux.cpu0_dbus_i[ack] , \ddr_ram_mux.cpu0_dbus_i[d]  };
  assign \ddr_ram_mux.u_dcache:455  = { \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  };
  assign \ddr_ram_mux.u_dcache:457  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ;
  assign \ddr_ram_mux.u_icache:430  = { \ddr_ram_mux.cpu0_ibus_i[ack] , \ddr_ram_mux.cpu0_ibus_i[d]  };
  assign \ddr_ram_mux.u_icache:431  = { \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en]  };
  assign \ddr_ram_mux.u_icache:432  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ;
  assign debug_i = 52'h0000000000000;
  assign dma_dbus_o = 73'h0000000000000000000;
  assign fl_miso = 1'hx;
endmodule
