/* Generated by Yosys 0.44 (git sha1 80ba43d26, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module soc(clk_sys, gpio_di, qfl_io_i, reset, sd_dq_i, spi2_miso, uart0_rx, gpio_do, qfl_cs_n, qfl_io_o, qfl_io_oe, qfl_sck, sd_cmd_cke , sd_cmd_cs_n , sd_cmd_ras_n , sd_cmd_cas_n , sd_cmd_we_n , sd_cmd_ba , sd_cmd_a , sd_cmd_dqm , sd_dq_o
, sd_dq_oe, spi2_clk, spi2_cs, spi2_mosi, uart0_tx);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire [31:0] _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire [3:0] _0443_;
  wire _0444_;
  wire _0445_;
  wire [31:0] _0446_;
  wire [3:0] _0447_;
  wire [3:0] _0448_;
  wire [4:0] _0449_;
  wire _0450_;
  wire _0451_;
  wire [31:0] _0452_;
  wire [3:0] _0453_;
  wire [3:0] _0454_;
  wire [4:0] _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire [22:0] _0461_;
  wire _0462_;
  wire _0463_;
  wire aic_irq;
  wire \aic_irq_gen.clk ;
  wire [7:0] \aic_irq_gen.irq ;
  wire [31:0] \aic_irq_gen.pi_in ;
  reg [1:0] \aic_irq_gen.sync  = 2'h0;
  wire cache01sel_ctrl_temp;
  input clk_sys;
  wire clk_sys;
  wire [32:0] cpu0_ddr_dbus_i;
  wire [70:0] cpu0_ddr_dbus_o;
  wire [16:0] cpu0_ddr_ibus_i;
  wire [32:0] cpu0_ddr_ibus_o;
  wire [15:0] cpu0_event_i;
  wire [6:0] cpu0_event_o;
  wire cpu0_mem_lock;
  wire [32:0] cpu0_periph_dbus_i;
  wire [70:0] cpu0_periph_dbus_o;
  wire [32:0] cpu1_ddr_dbus_i;
  wire [70:0] cpu1_ddr_dbus_o;
  wire [16:0] cpu1_ddr_ibus_i;
  wire [32:0] cpu1_ddr_ibus_o;
  wire [15:0] cpu1_event_i;
  wire cpu1_mem_lock;
  wire [32:0] cpu1_periph_dbus_i;
  wire [70:0] cpu1_periph_dbus_o;
  wire [32:0] ddr_bus_i;
  wire [70:0] ddr_bus_o;
  wire \ddr_ram_mux.cache01sel_ctrl_temp ;
  wire \ddr_ram_mux.clk ;
  wire \ddr_ram_mux.clk_ddr ;
  wire \ddr_ram_mux.cpu0_dbus_i[ack] ;
  wire [31:0] \ddr_ram_mux.cpu0_dbus_i[d] ;
  wire [31:0] \ddr_ram_mux.cpu0_dbus_o[a] ;
  wire [31:0] \ddr_ram_mux.cpu0_dbus_o[d] ;
  wire \ddr_ram_mux.cpu0_dbus_o[en] ;
  wire \ddr_ram_mux.cpu0_dbus_o[rd] ;
  wire [3:0] \ddr_ram_mux.cpu0_dbus_o[we] ;
  wire \ddr_ram_mux.cpu0_dbus_o[wr] ;
  wire \ddr_ram_mux.cpu0_ibus_i[ack] ;
  wire [15:0] \ddr_ram_mux.cpu0_ibus_i[d] ;
  wire [30:0] \ddr_ram_mux.cpu0_ibus_o[a] ;
  wire \ddr_ram_mux.cpu0_ibus_o[en] ;
  wire \ddr_ram_mux.cpu0_ibus_o[jp] ;
  wire \ddr_ram_mux.cpu0_mem_lock ;
  wire \ddr_ram_mux.cpu1_dbus_i[ack] ;
  wire [31:0] \ddr_ram_mux.cpu1_dbus_i[d] ;
  wire [31:0] \ddr_ram_mux.cpu1_dbus_o[a] ;
  wire [31:0] \ddr_ram_mux.cpu1_dbus_o[d] ;
  wire \ddr_ram_mux.cpu1_dbus_o[en] ;
  wire \ddr_ram_mux.cpu1_dbus_o[rd] ;
  wire [3:0] \ddr_ram_mux.cpu1_dbus_o[we] ;
  wire \ddr_ram_mux.cpu1_dbus_o[wr] ;
  wire \ddr_ram_mux.cpu1_ibus_i[ack] ;
  wire [15:0] \ddr_ram_mux.cpu1_ibus_i[d] ;
  wire [30:0] \ddr_ram_mux.cpu1_ibus_o[a] ;
  wire \ddr_ram_mux.cpu1_ibus_o[en] ;
  wire \ddr_ram_mux.cpu1_ibus_o[jp] ;
  wire \ddr_ram_mux.cpu1_mem_lock ;
  wire \ddr_ram_mux.data_dbus_ack_r ;
  wire [32:0] \ddr_ram_mux.data_dbus_i ;
  wire [70:0] \ddr_ram_mux.data_dbus_o ;
  wire \ddr_ram_mux.data_ddrburst ;
  wire \ddr_ram_mux.dcache0_ctrl[en] ;
  wire \ddr_ram_mux.dcache0_ctrl[inv] ;
  wire \ddr_ram_mux.dcache1_ctrl[en] ;
  wire \ddr_ram_mux.dcache1_ctrl[inv] ;
  wire \ddr_ram_mux.ddr_bus_i[ack] ;
  wire [31:0] \ddr_ram_mux.ddr_bus_i[d] ;
  wire [31:0] \ddr_ram_mux.ddr_bus_o[a] ;
  wire [31:0] \ddr_ram_mux.ddr_bus_o[d] ;
  wire \ddr_ram_mux.ddr_bus_o[en] ;
  wire \ddr_ram_mux.ddr_bus_o[rd] ;
  wire [3:0] \ddr_ram_mux.ddr_bus_o[we] ;
  wire \ddr_ram_mux.ddr_bus_o[wr] ;
  wire [31:0] \ddr_ram_mux.dma_dbus_i[d] ;
  wire [31:0] \ddr_ram_mux.dma_dbus_o[a] ;
  wire \ddr_ram_mux.dma_dbus_o[bgrp] ;
  wire \ddr_ram_mux.dma_dbus_o[burst16] ;
  wire \ddr_ram_mux.dma_dbus_o[burst32] ;
  wire [31:0] \ddr_ram_mux.dma_dbus_o[d] ;
  wire \ddr_ram_mux.dma_dbus_o[en] ;
  wire [3:0] \ddr_ram_mux.dma_dbus_o[we] ;
  wire \ddr_ram_mux.dma_dbus_o[wr] ;
  wire \ddr_ram_mux.icache0_ctrl[en] ;
  wire \ddr_ram_mux.icache0_ctrl[inv] ;
  wire \ddr_ram_mux.icache1_ctrl[en] ;
  wire \ddr_ram_mux.icache1_ctrl[inv] ;
  wire \ddr_ram_mux.instr_dbus_ack_r ;
  wire [32:0] \ddr_ram_mux.instr_dbus_i ;
  wire [70:0] \ddr_ram_mux.instr_dbus_o ;
  wire \ddr_ram_mux.instr_ddrburst ;
  wire \ddr_ram_mux.rst ;
  wire [78:0] \ddr_ram_mux.u_bmuxc.bus_mux_typec.nx ;
  wire \ddr_ram_mux.u_bmuxc.clk ;
  wire \ddr_ram_mux.u_bmuxc.m1_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.m1_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m1_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m1_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m1_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.m1_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m1_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m1_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.m1_lock ;
  wire \ddr_ram_mux.u_bmuxc.m1_o[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m1_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.m2_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.m2_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m2_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m2_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m2_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.m2_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m2_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m2_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.m2_o[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m2_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.m3_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m3_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m3_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m3_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.m3_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m3_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m3_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.m3_lock ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m3_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.m4_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m4_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m4_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m4_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.m4_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m4_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m4_i[wr] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m4_o[d] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m5_i[a] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[bgrp] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[burst16] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[burst32] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m5_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[en] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.m5_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.m5_i[wr] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.m5_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.m6_ddrburst ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.m6_i ;
  wire [70:0] \ddr_ram_mux.u_bmuxc.m6_o ;
  wire \ddr_ram_mux.u_bmuxc.mem_i[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mem_i[d] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mem_o[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mem_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mem_o[en] ;
  wire \ddr_ram_mux.u_bmuxc.mem_o[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mem_o[we] ;
  wire \ddr_ram_mux.u_bmuxc.mem_o[wr] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.A ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[0].B_AND_BITS ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[1].B_AND_BITS ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[2].B_AND_BITS ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[3].B_AND_BITS ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6954.S ;
  wire [7:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.:6974.Y ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.:7075.A ;
  wire [1:0] \ddr_ram_mux.u_bmuxc.mux_m6.:7075.B ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y ;
  wire [70:0] \ddr_ram_mux.u_bmuxc.mux_m6.:7078.A ;
  wire [141:0] \ddr_ram_mux.u_bmuxc.mux_m6.:7078.B ;
  wire [70:0] \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y ;
  wire [90:0] \ddr_ram_mux.u_bmuxc.mux_m6.bus_mux_typecsub.nx ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.clk ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_lock ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m1_o[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m1_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_ack_r ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m2_o[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m2_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[wr] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m3_lock ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m3_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m4_ddrburst ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[wr] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m4_o[d] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[a] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[bgrp] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[burst16] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[burst32] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[en] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[wr] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.m5_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_ddrburst ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[d] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[a] ;
  wire [31:0] \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[d] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[rd] ;
  wire [3:0] \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[we] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[wr] ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6.rst ;
  wire [90:0] \ddr_ram_mux.u_bmuxc.mux_m6.this_c ;
  wire [90:0] \ddr_ram_mux.u_bmuxc.mux_m6.this_r ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.mux_m6:3014 ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6:3015 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.mux_m6:3016 ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6:3017 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.mux_m6:3018 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc.mux_m6:3020 ;
  wire [70:0] \ddr_ram_mux.u_bmuxc.mux_m6:3024 ;
  wire \ddr_ram_mux.u_bmuxc.mux_m6:3025 ;
  wire \ddr_ram_mux.u_bmuxc.rst ;
  wire [78:0] \ddr_ram_mux.u_bmuxc.this_c ;
  wire [78:0] \ddr_ram_mux.u_bmuxc.this_r ;
  wire [32:0] \ddr_ram_mux.u_bmuxc:484 ;
  wire \ddr_ram_mux.u_bmuxc:485 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc:487 ;
  wire \ddr_ram_mux.u_bmuxc:488 ;
  wire [32:0] \ddr_ram_mux.u_bmuxc:497 ;
  wire [70:0] \ddr_ram_mux.u_bmuxc:498 ;
  wire [32:0] \ddr_ram_mux.u_dcache:452 ;
  wire [70:0] \ddr_ram_mux.u_dcache:455 ;
  wire \ddr_ram_mux.u_dcache:457 ;
  wire [16:0] \ddr_ram_mux.u_icache:430 ;
  wire [70:0] \ddr_ram_mux.u_icache:431 ;
  wire \ddr_ram_mux.u_icache:432 ;
  wire [51:0] debug_i;
  wire [72:0] dma_dbus_o;
  wire fl_miso;
  wire flash_ack_r;
  wire flash_bst;
  wire [70:0] flash_req;
  wire [32:0] flash_resp;
  input [31:0] gpio_di;
  wire [31:0] gpio_di;
  output [31:0] gpio_do;
  wire [31:0] gpio_do;
  wire \mem_region_mux.flash_ack_r ;
  wire \mem_region_mux.flash_bst ;
  wire [31:0] \mem_region_mux.flash_req[a] ;
  wire [31:0] \mem_region_mux.flash_req[d] ;
  wire \mem_region_mux.flash_req[en] ;
  wire \mem_region_mux.flash_req[rd] ;
  wire [3:0] \mem_region_mux.flash_req[we] ;
  wire \mem_region_mux.flash_req[wr] ;
  wire \mem_region_mux.flash_resp[ack] ;
  wire [31:0] \mem_region_mux.flash_resp[d] ;
  wire [31:0] \mem_region_mux.req[a] ;
  wire [31:0] \mem_region_mux.req[d] ;
  wire \mem_region_mux.req[en] ;
  wire \mem_region_mux.req[rd] ;
  wire [3:0] \mem_region_mux.req[we] ;
  wire \mem_region_mux.req[wr] ;
  wire \mem_region_mux.resp[ack] ;
  wire [31:0] \mem_region_mux.resp[d] ;
  wire \mem_region_mux.sdram_ack_r ;
  wire \mem_region_mux.sdram_bst ;
  wire [31:0] \mem_region_mux.sdram_req[a] ;
  wire [31:0] \mem_region_mux.sdram_req[d] ;
  wire \mem_region_mux.sdram_req[en] ;
  wire \mem_region_mux.sdram_req[rd] ;
  wire [3:0] \mem_region_mux.sdram_req[we] ;
  wire \mem_region_mux.sdram_req[wr] ;
  wire \mem_region_mux.sdram_resp[ack] ;
  wire [31:0] \mem_region_mux.sdram_resp[d] ;
  output qfl_cs_n;
  wire qfl_cs_n;
  input [3:0] qfl_io_i;
  wire [3:0] qfl_io_i;
  output [3:0] qfl_io_o;
  wire [3:0] qfl_io_o;
  output [3:0] qfl_io_oe;
  wire [3:0] qfl_io_oe;
  output qfl_sck;
  wire qfl_sck;
  input reset;
  wire reset;
  output [12:0] sd_cmd_a ;
  wire [12:0] sd_cmd_a ;
  output [1:0] sd_cmd_ba ;
  wire [1:0] sd_cmd_ba ;
  output sd_cmd_cas_n ;
  wire sd_cmd_cas_n ;
  output sd_cmd_cke ;
  wire sd_cmd_cke ;
  output sd_cmd_cs_n ;
  wire sd_cmd_cs_n ;
  output [1:0] sd_cmd_dqm ;
  wire [1:0] sd_cmd_dqm ;
  output sd_cmd_ras_n ;
  wire sd_cmd_ras_n ;
  output sd_cmd_we_n ;
  wire sd_cmd_we_n ;
  input [15:0] sd_dq_i;
  wire [15:0] sd_dq_i;
  output [15:0] sd_dq_o;
  wire [15:0] sd_dq_o;
  output sd_dq_oe;
  wire sd_dq_oe;
  wire sdram_ack_r;
  wire sdram_bst;
  wire [70:0] sdram_req;
  wire [32:0] sdram_resp;
  output spi2_clk;
  wire spi2_clk;
  output [1:0] spi2_cs;
  wire [1:0] spi2_cs;
  input spi2_miso;
  wire spi2_miso;
  output spi2_mosi;
  wire spi2_mosi;
  input uart0_rx;
  wire uart0_rx;
  output uart0_tx;
  wire uart0_tx;
  assign _0006_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.this_r [0];
  assign _0007_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] & ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [1]);
  assign _0008_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [2] | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3];
  assign _0009_ = _0007_ & ~(_0008_);
  assign _0010_ = ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [2] | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3]);
  assign _0011_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] | ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [1]);
  assign _0012_ = _0010_ & ~(_0011_);
  assign _0013_ = ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] & \ddr_ram_mux.u_bmuxc.mux_m6.this_r [1]);
  assign _0014_ = _0010_ & ~(_0013_);
  assign _0015_ = _0014_ | _0012_;
  assign _0016_ = _0015_ & ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] );
  assign _0017_ = ~(_0016_ | _0009_);
  assign _0018_ = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  | \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] ;
  assign _0019_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3] | ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [2]);
  assign _0020_ = _0019_ | ~(_0007_);
  assign _0021_ = _0020_ | _0018_;
  assign _0022_ = _0019_ | _0013_;
  assign _0023_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [1];
  assign _0024_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [2] | ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [3]);
  assign _0025_ = ~(_0024_ | _0023_);
  assign _0026_ = _0025_ | ~(_0022_);
  assign _0027_ = _0007_ & ~(_0024_);
  assign _0028_ = _0027_ & ~(_0018_);
  assign _0029_ = ~(_0028_ | _0026_);
  assign _0030_ = ~(_0029_ & _0021_);
  assign _0031_ = _0017_ & ~(_0030_);
  assign _0032_ = _0023_ | _0008_;
  assign _0033_ = _0032_ & ~(_0009_);
  assign _0034_ = _0023_ | _0019_;
  assign _0035_ = _0015_ | ~(_0034_);
  assign _0036_ = _0033_ & ~(_0035_);
  assign _0037_ = ~(_0019_ | _0011_);
  assign _0038_ = _0037_ | ~(_0020_);
  assign _0039_ = _0027_ | _0026_;
  assign _0040_ = _0039_ | _0038_;
  assign _0041_ = _0036_ & ~(_0040_);
  assign _0042_ = _0041_ | _0031_;
  assign _0043_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [89] | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [88];
  assign _0044_ = _0043_ | \ddr_ram_mux.u_bmuxc.mux_m6.this_r [90];
  assign _0045_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [87] | ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [16]);
  assign _0046_ = _0045_ | _0009_;
  assign _0047_ = _0046_ | _0012_;
  assign _0048_ = _0047_ | _0037_;
  assign _0049_ = _0022_ & ~(_0048_);
  assign _0050_ = _0049_ | _0044_;
  assign _0051_ = _0050_ ? _0006_ : _0042_;
  assign _0052_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.this_r [1];
  assign _0053_ = _0037_ | _0026_;
  assign _0054_ = ~(_0053_ | _0016_);
  assign _0055_ = _0054_ | _0041_;
  assign _0056_ = _0050_ ? _0052_ : _0055_;
  assign _0057_ = ~(_0056_ & _0051_);
  assign _0058_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.this_r [2];
  assign _0059_ = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] );
  assign _0060_ = _0032_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] );
  assign _0061_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] ;
  assign _0062_ = _0061_ & ~(_0034_);
  assign _0063_ = _0060_ & ~(_0062_);
  assign _0064_ = _0061_ & ~(_0020_);
  assign _0065_ = _0064_ | _0037_;
  assign _0066_ = _0027_ & ~(_0059_);
  assign _0067_ = _0066_ | _0065_;
  assign _0068_ = _0063_ & ~(_0067_);
  assign _0069_ = _0041_ ? _0059_ : _0068_;
  assign _0070_ = _0050_ ? _0058_ : _0069_;
  assign _0071_ = _0015_ & ~(_0018_);
  assign _0072_ = _0029_ & ~(_0071_);
  assign _0073_ = ~(_0072_ | _0041_);
  assign _0074_ = _0050_ ? \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3] : _0073_;
  assign _0075_ = _0070_ & ~(_0074_);
  assign _0076_ = _0057_ | ~(_0075_);
  assign _0077_ = ~(_0054_ | _0041_);
  assign _0078_ = _0050_ ? \ddr_ram_mux.u_bmuxc.mux_m6.this_r [1] : _0077_;
  assign _0079_ = _0078_ | _0051_;
  assign _0080_ = _0075_ & ~(_0079_);
  assign _0081_ = _0076_ & ~(_0080_);
  assign _0082_ = ~(_0078_ & _0051_);
  assign _0083_ = _0075_ & ~(_0082_);
  assign _0084_ = _0081_ & ~(_0083_);
  assign _0085_ = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [26] & ~(_0084_);
  assign _0086_ = _0074_ | _0070_;
  assign _0087_ = _0086_ | _0057_;
  assign _0088_ = _0056_ | _0051_;
  assign _0089_ = _0075_ & ~(_0088_);
  assign _0090_ = _0087_ & ~(_0089_);
  assign _0091_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [26] & ~(_0090_);
  assign _0092_ = _0091_ | _0085_;
  assign _0093_ = _0090_ & _0084_;
  assign _0094_ = _0092_ & ~(_0093_);
  assign _0095_ = _0084_ | _0061_;
  assign _0096_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en]  & ~(_0090_);
  assign _0097_ = _0095_ & ~(_0096_);
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en]  = ~(_0097_ | _0093_);
  assign _0098_ = \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en]  | \ddr_ram_mux.u_bmuxc.this_r [0];
  assign _0099_ = \ddr_ram_mux.u_bmuxc.this_r [77] | \ddr_ram_mux.u_bmuxc.this_r [76];
  assign _0100_ = _0099_ | \ddr_ram_mux.u_bmuxc.this_r [78];
  assign _0101_ = \ddr_ram_mux.u_bmuxc.this_r [4] & ~(\ddr_ram_mux.u_bmuxc.this_r [75]);
  assign _0102_ = _0101_ | _0100_;
  assign \ddr_ram_mux.u_bmuxc.this_c [0] = _0102_ ? \ddr_ram_mux.u_bmuxc.this_r [0] : _0098_;
  assign _0103_ = ~(\ddr_ram_mux.u_bmuxc.this_c [0] & _0094_);
  assign ddr_bus_o[27] = ~_0103_;
  assign _0104_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [24]);
  assign _0105_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [24] & ~(_0090_);
  assign _0106_ = _0104_ & ~(_0105_);
  assign _0107_ = _0106_ | _0093_;
  assign ddr_bus_o[25] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0107_);
  assign _0108_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [25]);
  assign _0109_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [25] & ~(_0090_);
  assign _0110_ = _0108_ & ~(_0109_);
  assign _0111_ = _0110_ | _0093_;
  assign ddr_bus_o[26] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0111_);
  assign _0112_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [27]);
  assign _0113_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [27] & ~(_0090_);
  assign _0114_ = _0112_ & ~(_0113_);
  assign _0115_ = _0114_ | _0093_;
  assign ddr_bus_o[28] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0115_);
  assign _0116_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [28]);
  assign _0117_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [28] & ~(_0090_);
  assign _0118_ = _0116_ & ~(_0117_);
  assign _0119_ = _0118_ | _0093_;
  assign ddr_bus_o[29] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0119_);
  assign _0120_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [29]);
  assign _0121_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [29] & ~(_0090_);
  assign _0122_ = _0120_ & ~(_0121_);
  assign _0123_ = _0122_ | _0093_;
  assign ddr_bus_o[30] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0123_);
  assign _0124_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [30]);
  assign _0125_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [30] & ~(_0090_);
  assign _0126_ = _0124_ & ~(_0125_);
  assign _0127_ = _0126_ | _0093_;
  assign ddr_bus_o[31] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0127_);
  assign _0128_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [31]);
  assign _0129_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [31] & ~(_0090_);
  assign _0130_ = _0128_ & ~(_0129_);
  assign _0131_ = _0130_ | _0093_;
  assign ddr_bus_o[32] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0131_);
  assign _0132_ = ~\mem_region_mux.flash_resp[ack] ;
  assign _0133_ = ~\mem_region_mux.sdram_resp[ack] ;
  assign _0134_ = ~(ddr_bus_o[26] | ddr_bus_o[25]);
  assign _0135_ = ddr_bus_o[28] | _0103_;
  assign _0136_ = _0134_ & ~(_0135_);
  assign _0137_ = ddr_bus_o[30] | ddr_bus_o[29];
  assign _0138_ = ddr_bus_o[32] | ddr_bus_o[31];
  assign _0139_ = _0138_ | _0137_;
  assign _0140_ = _0136_ & ~(_0139_);
  assign _0141_ = _0140_ ? _0132_ : _0133_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0141_);
  assign _0142_ = ~\ddr_ram_mux.u_bmuxc.mux_m6.this_r [88];
  assign _0143_ = \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst  & ~(_0084_);
  assign _0144_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst  & ~(_0087_);
  assign _0145_ = ~(_0144_ | _0143_);
  assign _0146_ = _0087_ & _0084_;
  assign _0147_ = ~(_0146_ | _0145_);
  assign _0003_ = _0044_ ? _0142_ : _0147_;
  assign _0004_ = \ddr_ram_mux.u_bmuxc.mux_m6.this_r [89] ^ \ddr_ram_mux.u_bmuxc.mux_m6.this_r [88];
  assign _0148_ = ~(\ddr_ram_mux.u_bmuxc.mux_m6.this_r [89] & \ddr_ram_mux.u_bmuxc.mux_m6.this_r [88]);
  assign _0149_ = _0148_ ^ \ddr_ram_mux.u_bmuxc.mux_m6.this_r [90];
  assign _0005_ = _0044_ & ~(_0149_);
  assign _0150_ = ~\ddr_ram_mux.u_bmuxc.this_r [76];
  assign _0151_ = ~_0147_;
  assign _0152_ = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0151_);
  assign _0000_ = _0100_ ? _0150_ : _0152_;
  assign _0001_ = \ddr_ram_mux.u_bmuxc.this_r [77] ^ \ddr_ram_mux.u_bmuxc.this_r [76];
  assign _0153_ = ~(\ddr_ram_mux.u_bmuxc.this_r [77] & \ddr_ram_mux.u_bmuxc.this_r [76]);
  assign _0154_ = _0153_ ^ \ddr_ram_mux.u_bmuxc.this_r [78];
  assign _0002_ = _0100_ & ~(_0154_);
  assign \ddr_ram_mux.ddr_bus_o[en]  = \ddr_ram_mux.u_bmuxc.this_c [0] & \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] ;
  assign _0155_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [0]);
  assign _0156_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [0] & ~(_0090_);
  assign _0157_ = _0155_ & ~(_0156_);
  assign _0158_ = _0157_ | _0093_;
  assign ddr_bus_o[1] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0158_);
  assign _0159_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [1]);
  assign _0160_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [1] & ~(_0090_);
  assign _0161_ = _0159_ & ~(_0160_);
  assign _0162_ = _0161_ | _0093_;
  assign ddr_bus_o[2] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0162_);
  assign _0163_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [2]);
  assign _0164_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [2] & ~(_0090_);
  assign _0165_ = _0163_ & ~(_0164_);
  assign _0166_ = _0165_ | _0093_;
  assign ddr_bus_o[3] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0166_);
  assign _0167_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [3]);
  assign _0168_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [3] & ~(_0090_);
  assign _0169_ = _0167_ & ~(_0168_);
  assign _0170_ = _0169_ | _0093_;
  assign ddr_bus_o[4] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0170_);
  assign _0171_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [4]);
  assign _0172_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [4] & ~(_0090_);
  assign _0173_ = _0171_ & ~(_0172_);
  assign _0174_ = _0173_ | _0093_;
  assign ddr_bus_o[5] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0174_);
  assign _0175_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [5]);
  assign _0176_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [5] & ~(_0090_);
  assign _0177_ = _0175_ & ~(_0176_);
  assign _0178_ = _0177_ | _0093_;
  assign ddr_bus_o[6] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0178_);
  assign _0179_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [6]);
  assign _0180_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [6] & ~(_0090_);
  assign _0181_ = _0179_ & ~(_0180_);
  assign _0182_ = _0181_ | _0093_;
  assign ddr_bus_o[7] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0182_);
  assign _0183_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [7]);
  assign _0184_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [7] & ~(_0090_);
  assign _0185_ = _0183_ & ~(_0184_);
  assign _0186_ = _0185_ | _0093_;
  assign ddr_bus_o[8] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0186_);
  assign _0187_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [8]);
  assign _0188_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [8] & ~(_0090_);
  assign _0189_ = _0187_ & ~(_0188_);
  assign _0190_ = _0189_ | _0093_;
  assign ddr_bus_o[9] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0190_);
  assign _0191_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [9]);
  assign _0192_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [9] & ~(_0090_);
  assign _0193_ = _0191_ & ~(_0192_);
  assign _0194_ = _0193_ | _0093_;
  assign ddr_bus_o[10] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0194_);
  assign _0195_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [10]);
  assign _0196_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [10] & ~(_0090_);
  assign _0197_ = _0195_ & ~(_0196_);
  assign _0198_ = _0197_ | _0093_;
  assign ddr_bus_o[11] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0198_);
  assign _0199_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [11]);
  assign _0200_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [11] & ~(_0090_);
  assign _0201_ = _0199_ & ~(_0200_);
  assign _0202_ = _0201_ | _0093_;
  assign ddr_bus_o[12] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0202_);
  assign _0203_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [12]);
  assign _0204_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [12] & ~(_0090_);
  assign _0205_ = _0203_ & ~(_0204_);
  assign _0206_ = _0205_ | _0093_;
  assign ddr_bus_o[13] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0206_);
  assign _0207_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [13]);
  assign _0208_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [13] & ~(_0090_);
  assign _0209_ = _0207_ & ~(_0208_);
  assign _0210_ = _0209_ | _0093_;
  assign ddr_bus_o[14] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0210_);
  assign _0211_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [14]);
  assign _0212_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [14] & ~(_0090_);
  assign _0213_ = _0211_ & ~(_0212_);
  assign _0214_ = _0213_ | _0093_;
  assign ddr_bus_o[15] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0214_);
  assign _0215_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [15]);
  assign _0216_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [15] & ~(_0090_);
  assign _0217_ = _0215_ & ~(_0216_);
  assign _0218_ = _0217_ | _0093_;
  assign ddr_bus_o[16] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0218_);
  assign _0219_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [16]);
  assign _0220_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [16] & ~(_0090_);
  assign _0221_ = _0219_ & ~(_0220_);
  assign _0222_ = _0221_ | _0093_;
  assign ddr_bus_o[17] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0222_);
  assign _0223_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [17]);
  assign _0224_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [17] & ~(_0090_);
  assign _0225_ = _0223_ & ~(_0224_);
  assign _0226_ = _0225_ | _0093_;
  assign ddr_bus_o[18] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0226_);
  assign _0227_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [18]);
  assign _0228_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [18] & ~(_0090_);
  assign _0229_ = _0227_ & ~(_0228_);
  assign _0230_ = _0229_ | _0093_;
  assign ddr_bus_o[19] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0230_);
  assign _0231_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [19]);
  assign _0232_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [19] & ~(_0090_);
  assign _0233_ = _0231_ & ~(_0232_);
  assign _0234_ = _0233_ | _0093_;
  assign ddr_bus_o[20] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0234_);
  assign _0235_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [20]);
  assign _0236_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [20] & ~(_0090_);
  assign _0237_ = _0235_ & ~(_0236_);
  assign _0238_ = _0237_ | _0093_;
  assign ddr_bus_o[21] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0238_);
  assign _0239_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [21]);
  assign _0240_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [21] & ~(_0090_);
  assign _0241_ = _0239_ & ~(_0240_);
  assign _0242_ = _0241_ | _0093_;
  assign ddr_bus_o[22] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0242_);
  assign _0243_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [22]);
  assign _0244_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [22] & ~(_0090_);
  assign _0245_ = _0243_ & ~(_0244_);
  assign _0246_ = _0245_ | _0093_;
  assign ddr_bus_o[23] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0246_);
  assign _0247_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] [23]);
  assign _0248_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] [23] & ~(_0090_);
  assign _0249_ = _0247_ & ~(_0248_);
  assign _0250_ = _0249_ | _0093_;
  assign ddr_bus_o[24] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0250_);
  assign _0251_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [0]);
  assign _0252_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [0] & ~(_0090_);
  assign _0253_ = _0251_ & ~(_0252_);
  assign _0254_ = _0253_ | _0093_;
  assign ddr_bus_o[39] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0254_);
  assign _0255_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [1]);
  assign _0256_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [1] & ~(_0090_);
  assign _0257_ = _0255_ & ~(_0256_);
  assign _0258_ = _0257_ | _0093_;
  assign ddr_bus_o[40] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0258_);
  assign _0259_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [2]);
  assign _0260_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [2] & ~(_0090_);
  assign _0261_ = _0259_ & ~(_0260_);
  assign _0262_ = _0261_ | _0093_;
  assign ddr_bus_o[41] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0262_);
  assign _0263_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [3]);
  assign _0264_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [3] & ~(_0090_);
  assign _0265_ = _0263_ & ~(_0264_);
  assign _0266_ = _0265_ | _0093_;
  assign ddr_bus_o[42] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0266_);
  assign _0267_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [4]);
  assign _0268_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [4] & ~(_0090_);
  assign _0269_ = _0267_ & ~(_0268_);
  assign _0270_ = _0269_ | _0093_;
  assign ddr_bus_o[43] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0270_);
  assign _0271_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [5]);
  assign _0272_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [5] & ~(_0090_);
  assign _0273_ = _0271_ & ~(_0272_);
  assign _0274_ = _0273_ | _0093_;
  assign ddr_bus_o[44] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0274_);
  assign _0275_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [6]);
  assign _0276_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [6] & ~(_0090_);
  assign _0277_ = _0275_ & ~(_0276_);
  assign _0278_ = _0277_ | _0093_;
  assign ddr_bus_o[45] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0278_);
  assign _0279_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [7]);
  assign _0280_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [7] & ~(_0090_);
  assign _0281_ = _0279_ & ~(_0280_);
  assign _0282_ = _0281_ | _0093_;
  assign ddr_bus_o[46] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0282_);
  assign _0283_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [8]);
  assign _0284_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [8] & ~(_0090_);
  assign _0285_ = _0283_ & ~(_0284_);
  assign _0286_ = _0285_ | _0093_;
  assign ddr_bus_o[47] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0286_);
  assign _0287_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [9]);
  assign _0288_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [9] & ~(_0090_);
  assign _0289_ = _0287_ & ~(_0288_);
  assign _0290_ = _0289_ | _0093_;
  assign ddr_bus_o[48] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0290_);
  assign _0291_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [10]);
  assign _0292_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [10] & ~(_0090_);
  assign _0293_ = _0291_ & ~(_0292_);
  assign _0294_ = _0293_ | _0093_;
  assign ddr_bus_o[49] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0294_);
  assign _0295_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [11]);
  assign _0296_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [11] & ~(_0090_);
  assign _0297_ = _0295_ & ~(_0296_);
  assign _0298_ = _0297_ | _0093_;
  assign ddr_bus_o[50] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0298_);
  assign _0299_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [12]);
  assign _0300_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [12] & ~(_0090_);
  assign _0301_ = _0299_ & ~(_0300_);
  assign _0302_ = _0301_ | _0093_;
  assign ddr_bus_o[51] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0302_);
  assign _0303_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [13]);
  assign _0304_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [13] & ~(_0090_);
  assign _0305_ = _0303_ & ~(_0304_);
  assign _0306_ = _0305_ | _0093_;
  assign ddr_bus_o[52] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0306_);
  assign _0307_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [14]);
  assign _0308_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [14] & ~(_0090_);
  assign _0309_ = _0307_ & ~(_0308_);
  assign _0310_ = _0309_ | _0093_;
  assign ddr_bus_o[53] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0310_);
  assign _0311_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [15]);
  assign _0312_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [15] & ~(_0090_);
  assign _0313_ = _0311_ & ~(_0312_);
  assign _0314_ = _0313_ | _0093_;
  assign ddr_bus_o[54] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0314_);
  assign _0315_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [16]);
  assign _0316_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [16] & ~(_0090_);
  assign _0317_ = _0315_ & ~(_0316_);
  assign _0318_ = _0317_ | _0093_;
  assign ddr_bus_o[55] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0318_);
  assign _0319_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [17]);
  assign _0320_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [17] & ~(_0090_);
  assign _0321_ = _0319_ & ~(_0320_);
  assign _0322_ = _0321_ | _0093_;
  assign ddr_bus_o[56] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0322_);
  assign _0323_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [18]);
  assign _0324_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [18] & ~(_0090_);
  assign _0325_ = _0323_ & ~(_0324_);
  assign _0326_ = _0325_ | _0093_;
  assign ddr_bus_o[57] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0326_);
  assign _0327_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [19]);
  assign _0328_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [19] & ~(_0090_);
  assign _0329_ = _0327_ & ~(_0328_);
  assign _0330_ = _0329_ | _0093_;
  assign ddr_bus_o[58] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0330_);
  assign _0331_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [20]);
  assign _0332_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [20] & ~(_0090_);
  assign _0333_ = _0331_ & ~(_0332_);
  assign _0334_ = _0333_ | _0093_;
  assign ddr_bus_o[59] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0334_);
  assign _0335_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [21]);
  assign _0336_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [21] & ~(_0090_);
  assign _0337_ = _0335_ & ~(_0336_);
  assign _0338_ = _0337_ | _0093_;
  assign ddr_bus_o[60] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0338_);
  assign _0339_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [22]);
  assign _0340_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [22] & ~(_0090_);
  assign _0341_ = _0339_ & ~(_0340_);
  assign _0342_ = _0341_ | _0093_;
  assign ddr_bus_o[61] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0342_);
  assign _0343_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [23]);
  assign _0344_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [23] & ~(_0090_);
  assign _0345_ = _0343_ & ~(_0344_);
  assign _0346_ = _0345_ | _0093_;
  assign ddr_bus_o[62] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0346_);
  assign _0347_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [24]);
  assign _0348_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [24] & ~(_0090_);
  assign _0349_ = _0347_ & ~(_0348_);
  assign _0350_ = _0349_ | _0093_;
  assign ddr_bus_o[63] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0350_);
  assign _0351_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [25]);
  assign _0352_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [25] & ~(_0090_);
  assign _0353_ = _0351_ & ~(_0352_);
  assign _0354_ = _0353_ | _0093_;
  assign ddr_bus_o[64] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0354_);
  assign _0355_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [26]);
  assign _0356_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [26] & ~(_0090_);
  assign _0357_ = _0355_ & ~(_0356_);
  assign _0358_ = _0357_ | _0093_;
  assign ddr_bus_o[65] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0358_);
  assign _0359_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [27]);
  assign _0360_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [27] & ~(_0090_);
  assign _0361_ = _0359_ & ~(_0360_);
  assign _0362_ = _0361_ | _0093_;
  assign ddr_bus_o[66] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0362_);
  assign _0363_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [28]);
  assign _0364_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [28] & ~(_0090_);
  assign _0365_ = _0363_ & ~(_0364_);
  assign _0366_ = _0365_ | _0093_;
  assign ddr_bus_o[67] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0366_);
  assign _0367_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [29]);
  assign _0368_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [29] & ~(_0090_);
  assign _0369_ = _0367_ & ~(_0368_);
  assign _0370_ = _0369_ | _0093_;
  assign ddr_bus_o[68] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0370_);
  assign _0371_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [30]);
  assign _0372_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [30] & ~(_0090_);
  assign _0373_ = _0371_ & ~(_0372_);
  assign _0374_ = _0373_ | _0093_;
  assign ddr_bus_o[69] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0374_);
  assign _0375_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] [31]);
  assign _0376_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] [31] & ~(_0090_);
  assign _0377_ = _0375_ & ~(_0376_);
  assign _0378_ = _0377_ | _0093_;
  assign ddr_bus_o[70] = \ddr_ram_mux.u_bmuxc.this_c [0] & ~(_0378_);
  assign _0379_ = ~\ddr_ram_mux.ddr_bus_o[en] ;
  assign \mem_region_mux.sdram_req[en]  = ~(_0379_ | _0140_);
  assign _0380_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] );
  assign _0381_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd]  & ~(_0090_);
  assign _0382_ = _0380_ & ~(_0381_);
  assign _0383_ = _0382_ | _0093_;
  assign _0384_ = _0383_ | ~(\ddr_ram_mux.u_bmuxc.this_c [0]);
  assign \mem_region_mux.sdram_req[rd]  = ~(_0384_ | _0140_);
  assign _0385_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] );
  assign _0386_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr]  & ~(_0090_);
  assign _0387_ = _0385_ & ~(_0386_);
  assign _0388_ = _0387_ | _0093_;
  assign _0389_ = _0388_ | ~(\ddr_ram_mux.u_bmuxc.this_c [0]);
  assign \mem_region_mux.sdram_req[wr]  = ~(_0389_ | _0140_);
  assign _0390_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] [0]);
  assign _0391_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] [0] & ~(_0090_);
  assign _0392_ = _0390_ & ~(_0391_);
  assign _0393_ = _0392_ | _0093_;
  assign _0394_ = _0393_ | ~(\ddr_ram_mux.u_bmuxc.this_c [0]);
  assign sdram_req[35] = ~(_0394_ | _0140_);
  assign _0395_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] [1]);
  assign _0396_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] [1] & ~(_0090_);
  assign _0397_ = _0395_ & ~(_0396_);
  assign _0398_ = _0397_ | _0093_;
  assign _0399_ = _0398_ | ~(\ddr_ram_mux.u_bmuxc.this_c [0]);
  assign sdram_req[36] = ~(_0399_ | _0140_);
  assign _0400_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] [2]);
  assign _0401_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] [2] & ~(_0090_);
  assign _0402_ = _0400_ & ~(_0401_);
  assign _0403_ = _0402_ | _0093_;
  assign _0404_ = _0403_ | ~(\ddr_ram_mux.u_bmuxc.this_c [0]);
  assign sdram_req[37] = ~(_0404_ | _0140_);
  assign _0405_ = _0084_ | ~(\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] [3]);
  assign _0406_ = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] [3] & ~(_0090_);
  assign _0407_ = _0405_ & ~(_0406_);
  assign _0408_ = _0407_ | _0093_;
  assign _0409_ = _0408_ | ~(\ddr_ram_mux.u_bmuxc.this_c [0]);
  assign sdram_req[38] = ~(_0409_ | _0140_);
  assign \mem_region_mux.flash_req[en]  = _0140_ & ~(_0379_);
  assign \mem_region_mux.flash_req[rd]  = _0140_ & ~(_0384_);
  assign \mem_region_mux.flash_req[wr]  = _0140_ & ~(_0389_);
  assign flash_req[35] = _0140_ & ~(_0394_);
  assign flash_req[36] = _0140_ & ~(_0399_);
  assign flash_req[37] = _0140_ & ~(_0404_);
  assign flash_req[38] = _0140_ & ~(_0409_);
  assign _0410_ = ~_0152_;
  assign sdram_bst = ~(_0410_ | _0140_);
  assign ddr_bus_i[0] = _0140_ ? \mem_region_mux.flash_resp[d] [0] : \mem_region_mux.sdram_resp[d] [0];
  assign ddr_bus_i[1] = _0140_ ? \mem_region_mux.flash_resp[d] [1] : \mem_region_mux.sdram_resp[d] [1];
  assign ddr_bus_i[2] = _0140_ ? \mem_region_mux.flash_resp[d] [2] : \mem_region_mux.sdram_resp[d] [2];
  assign ddr_bus_i[3] = _0140_ ? \mem_region_mux.flash_resp[d] [3] : \mem_region_mux.sdram_resp[d] [3];
  assign ddr_bus_i[4] = _0140_ ? \mem_region_mux.flash_resp[d] [4] : \mem_region_mux.sdram_resp[d] [4];
  assign ddr_bus_i[5] = _0140_ ? \mem_region_mux.flash_resp[d] [5] : \mem_region_mux.sdram_resp[d] [5];
  assign ddr_bus_i[6] = _0140_ ? \mem_region_mux.flash_resp[d] [6] : \mem_region_mux.sdram_resp[d] [6];
  assign ddr_bus_i[7] = _0140_ ? \mem_region_mux.flash_resp[d] [7] : \mem_region_mux.sdram_resp[d] [7];
  assign ddr_bus_i[8] = _0140_ ? \mem_region_mux.flash_resp[d] [8] : \mem_region_mux.sdram_resp[d] [8];
  assign ddr_bus_i[9] = _0140_ ? \mem_region_mux.flash_resp[d] [9] : \mem_region_mux.sdram_resp[d] [9];
  assign ddr_bus_i[10] = _0140_ ? \mem_region_mux.flash_resp[d] [10] : \mem_region_mux.sdram_resp[d] [10];
  assign ddr_bus_i[11] = _0140_ ? \mem_region_mux.flash_resp[d] [11] : \mem_region_mux.sdram_resp[d] [11];
  assign ddr_bus_i[12] = _0140_ ? \mem_region_mux.flash_resp[d] [12] : \mem_region_mux.sdram_resp[d] [12];
  assign ddr_bus_i[13] = _0140_ ? \mem_region_mux.flash_resp[d] [13] : \mem_region_mux.sdram_resp[d] [13];
  assign ddr_bus_i[14] = _0140_ ? \mem_region_mux.flash_resp[d] [14] : \mem_region_mux.sdram_resp[d] [14];
  assign ddr_bus_i[15] = _0140_ ? \mem_region_mux.flash_resp[d] [15] : \mem_region_mux.sdram_resp[d] [15];
  assign ddr_bus_i[16] = _0140_ ? \mem_region_mux.flash_resp[d] [16] : \mem_region_mux.sdram_resp[d] [16];
  assign ddr_bus_i[17] = _0140_ ? \mem_region_mux.flash_resp[d] [17] : \mem_region_mux.sdram_resp[d] [17];
  assign ddr_bus_i[18] = _0140_ ? \mem_region_mux.flash_resp[d] [18] : \mem_region_mux.sdram_resp[d] [18];
  assign ddr_bus_i[19] = _0140_ ? \mem_region_mux.flash_resp[d] [19] : \mem_region_mux.sdram_resp[d] [19];
  assign ddr_bus_i[20] = _0140_ ? \mem_region_mux.flash_resp[d] [20] : \mem_region_mux.sdram_resp[d] [20];
  assign ddr_bus_i[21] = _0140_ ? \mem_region_mux.flash_resp[d] [21] : \mem_region_mux.sdram_resp[d] [21];
  assign ddr_bus_i[22] = _0140_ ? \mem_region_mux.flash_resp[d] [22] : \mem_region_mux.sdram_resp[d] [22];
  assign ddr_bus_i[23] = _0140_ ? \mem_region_mux.flash_resp[d] [23] : \mem_region_mux.sdram_resp[d] [23];
  assign ddr_bus_i[24] = _0140_ ? \mem_region_mux.flash_resp[d] [24] : \mem_region_mux.sdram_resp[d] [24];
  assign ddr_bus_i[25] = _0140_ ? \mem_region_mux.flash_resp[d] [25] : \mem_region_mux.sdram_resp[d] [25];
  assign ddr_bus_i[26] = _0140_ ? \mem_region_mux.flash_resp[d] [26] : \mem_region_mux.sdram_resp[d] [26];
  assign ddr_bus_i[27] = _0140_ ? \mem_region_mux.flash_resp[d] [27] : \mem_region_mux.sdram_resp[d] [27];
  assign ddr_bus_i[28] = _0140_ ? \mem_region_mux.flash_resp[d] [28] : \mem_region_mux.sdram_resp[d] [28];
  assign ddr_bus_i[29] = _0140_ ? \mem_region_mux.flash_resp[d] [29] : \mem_region_mux.sdram_resp[d] [29];
  assign ddr_bus_i[30] = _0140_ ? \mem_region_mux.flash_resp[d] [30] : \mem_region_mux.sdram_resp[d] [30];
  assign ddr_bus_i[31] = _0140_ ? \mem_region_mux.flash_resp[d] [31] : \mem_region_mux.sdram_resp[d] [31];
  assign \ddr_ram_mux.ddr_bus_i[ack]  = ~_0141_;
  assign _0411_ = ~_0051_;
  assign _0412_ = ~(_0086_ | _0082_);
  assign _0413_ = ~(_0412_ | _0080_);
  assign _0414_ = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  | _0051_;
  assign _0415_ = _0080_ & ~(_0414_);
  assign _0416_ = _0051_ & ~(\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] );
  assign _0417_ = _0412_ & ~(_0416_);
  assign _0418_ = _0417_ | _0415_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [0] = _0413_ ? _0411_ : _0418_;
  assign _0419_ = _0056_ & ~(\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] );
  assign _0420_ = _0080_ & ~(_0419_);
  assign _0421_ = _0412_ & ~(_0419_);
  assign _0422_ = _0421_ | _0420_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [1] = _0413_ ? _0078_ : _0422_;
  assign _0423_ = ~_0070_;
  assign _0424_ = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  | _0070_;
  assign _0425_ = _0080_ & ~(_0424_);
  assign _0426_ = _0070_ & ~(\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] );
  assign _0427_ = _0412_ & ~(_0426_);
  assign _0428_ = _0427_ | _0425_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [2] = _0413_ ? _0423_ : _0428_;
  assign _0429_ = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  | ~(_0074_);
  assign _0430_ = _0080_ & ~(_0429_);
  assign _0431_ = _0412_ & ~(_0429_);
  assign _0432_ = _0431_ | _0430_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [3] = _0413_ ? _0074_ : _0432_;
  assign \ddr_ram_mux.u_bmuxc.m1_o[ack]  = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  & ~(_0084_);
  assign _0433_ = _0140_ ? \mem_region_mux.flash_ack_r  : \mem_region_mux.sdram_ack_r ;
  assign _0434_ = ~(_0433_ & \ddr_ram_mux.u_bmuxc.this_c [0]);
  assign \ddr_ram_mux.data_dbus_ack_r  = ~(_0434_ | _0084_);
  assign \ddr_ram_mux.u_bmuxc.m2_o[ack]  = \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack]  & ~(_0090_);
  assign \ddr_ram_mux.instr_dbus_ack_r  = ~(_0434_ | _0090_);
  assign flash_bst = _0140_ & ~(_0410_);
  always @(posedge clk_sys)
    \aic_irq_gen.sync [0] <= gpio_di[1];
  always @(posedge clk_sys)
    \aic_irq_gen.sync [1] <= \aic_irq_gen.sync [0];
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[0]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[0]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[0]  <= \ddr_ram_mux.u_bmuxc.mux_m6.this_c [0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [0] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[0] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[1]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[1]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[1]  <= \ddr_ram_mux.u_bmuxc.mux_m6.this_c [1];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [1] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[1] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[2]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[2]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[2]  <= \ddr_ram_mux.u_bmuxc.mux_m6.this_c [2];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [2] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[2] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[3]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[3]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[3]  <= \ddr_ram_mux.u_bmuxc.mux_m6.this_c [3];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [3] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[3] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[16]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[16]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[16]  <= \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [16] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[16] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[87]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[87]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[87]  <= \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [87] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[87] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[88]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[88]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[88]  <= _0003_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [88] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[88] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[89]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[89]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[89]  <= _0004_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [89] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[89] ;
  reg \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[90]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[90]  <= 1'h0;
    else if (\ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] ) \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[90]  <= _0005_;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_r [90] = \ddr_ram_mux.u_bmuxc.mux_m6.this_r_reg[90] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[0]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[0]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.this_r_reg[0]  <= \ddr_ram_mux.u_bmuxc.this_c [0];
  assign \ddr_ram_mux.u_bmuxc.this_r [0] = \ddr_ram_mux.u_bmuxc.this_r_reg[0] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[4]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[4]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.this_r_reg[4]  <= \ddr_ram_mux.ddr_bus_o[en] ;
  assign \ddr_ram_mux.u_bmuxc.this_r [4] = \ddr_ram_mux.u_bmuxc.this_r_reg[4] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[75]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[75]  <= 1'h0;
    else \ddr_ram_mux.u_bmuxc.this_r_reg[75]  <= \ddr_ram_mux.ddr_bus_i[ack] ;
  assign \ddr_ram_mux.u_bmuxc.this_r [75] = \ddr_ram_mux.u_bmuxc.this_r_reg[75] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[76]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[76]  <= 1'h0;
    else if (!_0141_) \ddr_ram_mux.u_bmuxc.this_r_reg[76]  <= _0000_;
  assign \ddr_ram_mux.u_bmuxc.this_r [76] = \ddr_ram_mux.u_bmuxc.this_r_reg[76] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[77]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[77]  <= 1'h0;
    else if (!_0141_) \ddr_ram_mux.u_bmuxc.this_r_reg[77]  <= _0001_;
  assign \ddr_ram_mux.u_bmuxc.this_r [77] = \ddr_ram_mux.u_bmuxc.this_r_reg[77] ;
  reg \ddr_ram_mux.u_bmuxc.this_r_reg[78]  = 1'h0;
  always @(posedge clk_sys, posedge reset)
    if (reset) \ddr_ram_mux.u_bmuxc.this_r_reg[78]  <= 1'h0;
    else if (!_0141_) \ddr_ram_mux.u_bmuxc.this_r_reg[78]  <= _0002_;
  assign \ddr_ram_mux.u_bmuxc.this_r [78] = \ddr_ram_mux.u_bmuxc.this_r_reg[78] ;
  cpus cpus (
    .clk(clk_sys),
    .cpu0_copro_i_ack (1'h1),
    .cpu0_copro_i_d (32'd0),
    .cpu0_copro_i_exc (1'h0),
    .cpu0_copro_i_t (1'h0),
    .cpu0_copro_o_d (_0446_),
    .cpu0_copro_o_en (_0450_),
    .cpu0_copro_o_op (_0449_),
    .cpu0_copro_o_rna (_0447_),
    .cpu0_copro_o_rnb (_0448_),
    .cpu0_copro_o_stallcp (_0451_),
    .cpu0_data_master_ack(_0440_),
    .cpu0_data_master_en(_0438_),
    .cpu0_ddr_dbus_i_ack (\ddr_ram_mux.cpu0_dbus_i[ack] ),
    .cpu0_ddr_dbus_i_d (\ddr_ram_mux.cpu0_dbus_i[d] ),
    .cpu0_ddr_dbus_o_a (\ddr_ram_mux.cpu0_dbus_o[a] ),
    .cpu0_ddr_dbus_o_d (\ddr_ram_mux.cpu0_dbus_o[d] ),
    .cpu0_ddr_dbus_o_en (\ddr_ram_mux.cpu0_dbus_o[en] ),
    .cpu0_ddr_dbus_o_rd (\ddr_ram_mux.cpu0_dbus_o[rd] ),
    .cpu0_ddr_dbus_o_we (\ddr_ram_mux.cpu0_dbus_o[we] ),
    .cpu0_ddr_dbus_o_wr (\ddr_ram_mux.cpu0_dbus_o[wr] ),
    .cpu0_ddr_ibus_i_ack (\ddr_ram_mux.cpu0_ibus_i[ack] ),
    .cpu0_ddr_ibus_i_d (\ddr_ram_mux.cpu0_ibus_i[d] ),
    .cpu0_ddr_ibus_o_a (\ddr_ram_mux.cpu0_ibus_o[a] ),
    .cpu0_ddr_ibus_o_en (\ddr_ram_mux.cpu0_ibus_o[en] ),
    .cpu0_ddr_ibus_o_jp (\ddr_ram_mux.cpu0_ibus_o[jp] ),
    .cpu0_event_i_cmd (cpu0_event_i[2:1]),
    .cpu0_event_i_en (cpu0_event_i[0]),
    .cpu0_event_i_lvl (cpu0_event_i[15:12]),
    .cpu0_event_i_msk (cpu0_event_i[11]),
    .cpu0_event_i_vec (cpu0_event_i[10:3]),
    .cpu0_event_o_ack (cpu0_event_o[0]),
    .cpu0_event_o_dbg (cpu0_event_o[6]),
    .cpu0_event_o_lvl (cpu0_event_o[4:1]),
    .cpu0_event_o_slp (cpu0_event_o[5]),
    .cpu0_mem_lock(\ddr_ram_mux.cpu0_mem_lock ),
    .cpu0_periph_dbus_i_ack (cpu0_periph_dbus_i[32]),
    .cpu0_periph_dbus_i_d (cpu0_periph_dbus_i[31:0]),
    .cpu0_periph_dbus_o_a (cpu0_periph_dbus_o[32:1]),
    .cpu0_periph_dbus_o_d (cpu0_periph_dbus_o[70:39]),
    .cpu0_periph_dbus_o_en (cpu0_periph_dbus_o[0]),
    .cpu0_periph_dbus_o_rd (cpu0_periph_dbus_o[33]),
    .cpu0_periph_dbus_o_we (cpu0_periph_dbus_o[38:35]),
    .cpu0_periph_dbus_o_wr (cpu0_periph_dbus_o[34]),
    .cpu1_copro_i_ack (1'h1),
    .cpu1_copro_i_d (32'd0),
    .cpu1_copro_i_exc (1'h0),
    .cpu1_copro_i_t (1'h0),
    .cpu1_copro_o_d (_0452_),
    .cpu1_copro_o_en (_0456_),
    .cpu1_copro_o_op (_0455_),
    .cpu1_copro_o_rna (_0453_),
    .cpu1_copro_o_rnb (_0454_),
    .cpu1_copro_o_stallcp (_0457_),
    .cpu1_data_master_ack(_0441_),
    .cpu1_data_master_en(_0439_),
    .cpu1_ddr_dbus_i_ack (\ddr_ram_mux.cpu1_dbus_i[ack] ),
    .cpu1_ddr_dbus_i_d (32'd0),
    .cpu1_ddr_dbus_o_a (\ddr_ram_mux.cpu1_dbus_o[a] ),
    .cpu1_ddr_dbus_o_d (\ddr_ram_mux.cpu1_dbus_o[d] ),
    .cpu1_ddr_dbus_o_en (\ddr_ram_mux.cpu1_dbus_i[ack] ),
    .cpu1_ddr_dbus_o_rd (\ddr_ram_mux.cpu1_dbus_o[rd] ),
    .cpu1_ddr_dbus_o_we (\ddr_ram_mux.cpu1_dbus_o[we] ),
    .cpu1_ddr_dbus_o_wr (\ddr_ram_mux.cpu1_dbus_o[wr] ),
    .cpu1_ddr_ibus_i_ack (\ddr_ram_mux.cpu1_ibus_i[ack] ),
    .cpu1_ddr_ibus_i_d (16'h0000),
    .cpu1_ddr_ibus_o_a (\ddr_ram_mux.cpu1_ibus_o[a] ),
    .cpu1_ddr_ibus_o_en (\ddr_ram_mux.cpu1_ibus_i[ack] ),
    .cpu1_ddr_ibus_o_jp (\ddr_ram_mux.cpu1_ibus_o[jp] ),
    .cpu1_event_i_cmd (2'h0),
    .cpu1_event_i_en (1'h0),
    .cpu1_event_i_lvl (4'h0),
    .cpu1_event_i_msk (1'h0),
    .cpu1_event_i_vec (8'h00),
    .cpu1_event_o_ack (_0442_),
    .cpu1_event_o_dbg (_0445_),
    .cpu1_event_o_lvl (_0443_),
    .cpu1_event_o_slp (_0444_),
    .cpu1_mem_lock(cpu1_mem_lock),
    .cpu1_periph_dbus_i_ack (cpu1_periph_dbus_i[32]),
    .cpu1_periph_dbus_i_d (cpu1_periph_dbus_i[31:0]),
    .cpu1_periph_dbus_o_a (cpu1_periph_dbus_o[32:1]),
    .cpu1_periph_dbus_o_d (cpu1_periph_dbus_o[70:39]),
    .cpu1_periph_dbus_o_en (cpu1_periph_dbus_o[0]),
    .cpu1_periph_dbus_o_rd (cpu1_periph_dbus_o[33]),
    .cpu1_periph_dbus_o_we (cpu1_periph_dbus_o[38:35]),
    .cpu1_periph_dbus_o_wr (cpu1_periph_dbus_o[34]),
    .cpu1eni(1'h0),
    .debug_i_cmd (2'h0),
    .debug_i_d (32'd0),
    .debug_i_d_en (1'h0),
    .debug_i_en (1'h0),
    .debug_i_ir (16'h0000),
    .debug_o_ack (_0435_),
    .debug_o_d (_0436_),
    .debug_o_rdy (_0437_),
    .fl_cs_n(_0458_),
    .fl_miso(1'hx),
    .fl_mosi(_0460_),
    .fl_sck(_0459_),
    .rst(reset)
  );
  dcache_adapter \ddr_ram_mux.u_dcache  (
    .a_mmu_at (1'h0),
    .a_mmu_c (1'h0),
    .a_mmu_pa_tag (15'h0000),
    .clk125(clk_sys),
    .clk200(clk_sys),
    .ctrl_en (1'h1),
    .ctrl_inv (1'h0),
    .dbus_ack_r(\ddr_ram_mux.data_dbus_ack_r ),
    .dbus_ddrburst(\ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ),
    .dbus_i_ack (\ddr_ram_mux.u_bmuxc.m1_o[ack] ),
    .dbus_i_d (ddr_bus_i[31:0]),
    .dbus_lock(_0463_),
    .dbus_o_a (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] ),
    .dbus_o_d (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] ),
    .dbus_o_en (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] ),
    .dbus_o_rd (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] ),
    .dbus_o_we (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] ),
    .dbus_o_wr (\ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] ),
    .ibus_i_ack (\ddr_ram_mux.cpu0_dbus_i[ack] ),
    .ibus_i_d (\ddr_ram_mux.cpu0_dbus_i[d] ),
    .ibus_o_a (\ddr_ram_mux.cpu0_dbus_o[a] ),
    .ibus_o_d (\ddr_ram_mux.cpu0_dbus_o[d] ),
    .ibus_o_en (\ddr_ram_mux.cpu0_dbus_o[en] ),
    .ibus_o_rd (\ddr_ram_mux.cpu0_dbus_o[rd] ),
    .ibus_o_we (\ddr_ram_mux.cpu0_dbus_o[we] ),
    .ibus_o_wr (\ddr_ram_mux.cpu0_dbus_o[wr] ),
    .lock(\ddr_ram_mux.cpu0_mem_lock ),
    .rst(reset),
    .snpc_i_al (23'h000000),
    .snpc_i_en (1'h0),
    .snpc_o_al (_0461_),
    .snpc_o_en (_0462_)
  );
  icache_adapter \ddr_ram_mux.u_icache  (
    .a_mmu_at (1'h0),
    .a_mmu_c (1'h0),
    .a_mmu_pa_tag (15'h0000),
    .clk125(clk_sys),
    .clk200(clk_sys),
    .ctrl_en (1'h1),
    .ctrl_inv (1'h0),
    .dbus_ack_r(\ddr_ram_mux.instr_dbus_ack_r ),
    .dbus_ddrburst(\ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ),
    .dbus_i_ack (\ddr_ram_mux.u_bmuxc.m2_o[ack] ),
    .dbus_i_d (ddr_bus_i[31:0]),
    .dbus_o_a (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] ),
    .dbus_o_d (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] ),
    .dbus_o_en (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] ),
    .dbus_o_rd (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] ),
    .dbus_o_we (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] ),
    .dbus_o_wr (\ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] ),
    .ibus_i_ack (\ddr_ram_mux.cpu0_ibus_i[ack] ),
    .ibus_i_d (\ddr_ram_mux.cpu0_ibus_i[d] ),
    .ibus_o_a (\ddr_ram_mux.cpu0_ibus_o[a] ),
    .ibus_o_en (\ddr_ram_mux.cpu0_ibus_o[en] ),
    .ibus_o_jp (\ddr_ram_mux.cpu0_ibus_o[jp] ),
    .rst(reset)
  );
  devices devices (
    .aic_irq({ 7'h00, \aic_irq_gen.sync [1] }),
    .clk_sys(clk_sys),
    .cpu0_event_i_cmd (cpu0_event_i[2:1]),
    .cpu0_event_i_en (cpu0_event_i[0]),
    .cpu0_event_i_lvl (cpu0_event_i[15:12]),
    .cpu0_event_i_msk (cpu0_event_i[11]),
    .cpu0_event_i_vec (cpu0_event_i[10:3]),
    .cpu0_event_o_ack (cpu0_event_o[0]),
    .cpu0_event_o_dbg (cpu0_event_o[6]),
    .cpu0_event_o_lvl (cpu0_event_o[4:1]),
    .cpu0_event_o_slp (cpu0_event_o[5]),
    .cpu0_periph_dbus_i_ack (cpu0_periph_dbus_i[32]),
    .cpu0_periph_dbus_i_d (cpu0_periph_dbus_i[31:0]),
    .cpu0_periph_dbus_o_a (cpu0_periph_dbus_o[32:1]),
    .cpu0_periph_dbus_o_d (cpu0_periph_dbus_o[70:39]),
    .cpu0_periph_dbus_o_en (cpu0_periph_dbus_o[0]),
    .cpu0_periph_dbus_o_rd (cpu0_periph_dbus_o[33]),
    .cpu0_periph_dbus_o_we (cpu0_periph_dbus_o[38:35]),
    .cpu0_periph_dbus_o_wr (cpu0_periph_dbus_o[34]),
    .cpu1_periph_dbus_i_ack (cpu1_periph_dbus_i[32]),
    .cpu1_periph_dbus_i_d (cpu1_periph_dbus_i[31:0]),
    .cpu1_periph_dbus_o_a (cpu1_periph_dbus_o[32:1]),
    .cpu1_periph_dbus_o_d (cpu1_periph_dbus_o[70:39]),
    .cpu1_periph_dbus_o_en (cpu1_periph_dbus_o[0]),
    .cpu1_periph_dbus_o_rd (cpu1_periph_dbus_o[33]),
    .cpu1_periph_dbus_o_we (cpu1_periph_dbus_o[38:35]),
    .cpu1_periph_dbus_o_wr (cpu1_periph_dbus_o[34]),
    .gpio_di(gpio_di),
    .gpio_do(gpio_do),
    .reset(reset),
    .spi2_clk(spi2_clk),
    .spi2_cs(spi2_cs),
    .spi2_miso(spi2_miso),
    .spi2_mosi(spi2_mosi),
    .uart0_rx(uart0_rx),
    .uart0_tx(uart0_tx)
  );
  qspi_flash_ctrl qspi_flash_ctrl (
    .ack_r(\mem_region_mux.flash_ack_r ),
    .bst(flash_bst),
    .clk(clk_sys),
    .db_i_a (ddr_bus_o[32:1]),
    .db_i_d (ddr_bus_o[70:39]),
    .db_i_en (\mem_region_mux.flash_req[en] ),
    .db_i_rd (\mem_region_mux.flash_req[rd] ),
    .db_i_we (flash_req[38:35]),
    .db_i_wr (\mem_region_mux.flash_req[wr] ),
    .db_o_ack (\mem_region_mux.flash_resp[ack] ),
    .db_o_d (\mem_region_mux.flash_resp[d] ),
    .fl_cs_n(qfl_cs_n),
    .fl_io_i(qfl_io_i),
    .fl_io_o(qfl_io_o),
    .fl_io_oe(qfl_io_oe),
    .fl_sck(qfl_sck),
    .rst(reset)
  );
  sdram_ctrl sdram_ctrl (
    .ack_r(\mem_region_mux.sdram_ack_r ),
    .bst(sdram_bst),
    .clk(clk_sys),
    .cmd_a (sd_cmd_a ),
    .cmd_ba (sd_cmd_ba ),
    .cmd_cas_n (sd_cmd_cas_n ),
    .cmd_cke (sd_cmd_cke ),
    .cmd_cs_n (sd_cmd_cs_n ),
    .cmd_dqm (sd_cmd_dqm ),
    .cmd_ras_n (sd_cmd_ras_n ),
    .cmd_we_n (sd_cmd_we_n ),
    .dq_i(sd_dq_i),
    .dq_o(sd_dq_o),
    .dq_oe(sd_dq_oe),
    .req_a (ddr_bus_o[32:1]),
    .req_d (ddr_bus_o[70:39]),
    .req_en (\mem_region_mux.sdram_req[en] ),
    .req_rd (\mem_region_mux.sdram_req[rd] ),
    .req_we (sdram_req[38:35]),
    .req_wr (\mem_region_mux.sdram_req[wr] ),
    .resp_ack (\mem_region_mux.sdram_resp[ack] ),
    .resp_d (\mem_region_mux.sdram_resp[d] ),
    .rst(reset)
  );
  assign aic_irq = \aic_irq_gen.sync [1];
  assign \aic_irq_gen.clk  = clk_sys;
  assign \aic_irq_gen.irq  = { 7'h00, \aic_irq_gen.sync [1] };
  assign \aic_irq_gen.pi_in  = gpio_di;
  assign cache01sel_ctrl_temp = 1'h0;
  assign cpu0_ddr_dbus_i = { \ddr_ram_mux.cpu0_dbus_i[ack] , \ddr_ram_mux.cpu0_dbus_i[d]  };
  assign cpu0_ddr_dbus_o = { \ddr_ram_mux.cpu0_dbus_o[d] , \ddr_ram_mux.cpu0_dbus_o[we] , \ddr_ram_mux.cpu0_dbus_o[wr] , \ddr_ram_mux.cpu0_dbus_o[rd] , \ddr_ram_mux.cpu0_dbus_o[a] , \ddr_ram_mux.cpu0_dbus_o[en]  };
  assign cpu0_ddr_ibus_i = { \ddr_ram_mux.cpu0_ibus_i[ack] , \ddr_ram_mux.cpu0_ibus_i[d]  };
  assign cpu0_ddr_ibus_o = { \ddr_ram_mux.cpu0_ibus_o[jp] , \ddr_ram_mux.cpu0_ibus_o[a] , \ddr_ram_mux.cpu0_ibus_o[en]  };
  assign cpu0_mem_lock = \ddr_ram_mux.cpu0_mem_lock ;
  assign cpu1_ddr_dbus_i = { \ddr_ram_mux.cpu1_dbus_i[ack] , 32'h00000000 };
  assign cpu1_ddr_dbus_o = { \ddr_ram_mux.cpu1_dbus_o[d] , \ddr_ram_mux.cpu1_dbus_o[we] , \ddr_ram_mux.cpu1_dbus_o[wr] , \ddr_ram_mux.cpu1_dbus_o[rd] , \ddr_ram_mux.cpu1_dbus_o[a] , \ddr_ram_mux.cpu1_dbus_i[ack]  };
  assign cpu1_ddr_ibus_i = { \ddr_ram_mux.cpu1_ibus_i[ack] , 16'h0000 };
  assign cpu1_ddr_ibus_o = { \ddr_ram_mux.cpu1_ibus_o[jp] , \ddr_ram_mux.cpu1_ibus_o[a] , \ddr_ram_mux.cpu1_ibus_i[ack]  };
  assign cpu1_event_i = 16'h0000;
  assign ddr_bus_i[32] = \ddr_ram_mux.ddr_bus_i[ack] ;
  assign ddr_bus_o[0] = \ddr_ram_mux.ddr_bus_o[en] ;
  assign \ddr_ram_mux.cache01sel_ctrl_temp  = 1'h0;
  assign \ddr_ram_mux.clk  = clk_sys;
  assign \ddr_ram_mux.clk_ddr  = clk_sys;
  assign \ddr_ram_mux.cpu1_dbus_i[d]  = 32'd0;
  assign \ddr_ram_mux.cpu1_dbus_o[en]  = \ddr_ram_mux.cpu1_dbus_i[ack] ;
  assign \ddr_ram_mux.cpu1_ibus_i[d]  = 16'h0000;
  assign \ddr_ram_mux.cpu1_ibus_o[en]  = \ddr_ram_mux.cpu1_ibus_i[ack] ;
  assign \ddr_ram_mux.cpu1_mem_lock  = cpu1_mem_lock;
  assign \ddr_ram_mux.data_dbus_i  = { \ddr_ram_mux.u_bmuxc.m1_o[ack] , ddr_bus_i[31:0] };
  assign \ddr_ram_mux.data_dbus_o  = { \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  };
  assign \ddr_ram_mux.data_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ;
  assign \ddr_ram_mux.dcache0_ctrl[en]  = 1'h1;
  assign \ddr_ram_mux.dcache0_ctrl[inv]  = 1'h0;
  assign \ddr_ram_mux.dcache1_ctrl[en]  = 1'h1;
  assign \ddr_ram_mux.dcache1_ctrl[inv]  = 1'h0;
  assign \ddr_ram_mux.ddr_bus_i[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.ddr_bus_o[a]  = ddr_bus_o[32:1];
  assign \ddr_ram_mux.ddr_bus_o[d]  = ddr_bus_o[70:39];
  assign \ddr_ram_mux.ddr_bus_o[rd]  = ddr_bus_o[33];
  assign \ddr_ram_mux.ddr_bus_o[we]  = ddr_bus_o[38:35];
  assign \ddr_ram_mux.ddr_bus_o[wr]  = ddr_bus_o[34];
  assign \ddr_ram_mux.dma_dbus_i[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.dma_dbus_o[a]  = 32'd0;
  assign \ddr_ram_mux.dma_dbus_o[bgrp]  = 1'h0;
  assign \ddr_ram_mux.dma_dbus_o[burst16]  = 1'h0;
  assign \ddr_ram_mux.dma_dbus_o[burst32]  = 1'h0;
  assign \ddr_ram_mux.dma_dbus_o[d]  = 32'd0;
  assign \ddr_ram_mux.dma_dbus_o[en]  = 1'h0;
  assign \ddr_ram_mux.dma_dbus_o[we]  = 4'h0;
  assign \ddr_ram_mux.dma_dbus_o[wr]  = 1'h0;
  assign \ddr_ram_mux.icache0_ctrl[en]  = 1'h1;
  assign \ddr_ram_mux.icache0_ctrl[inv]  = 1'h0;
  assign \ddr_ram_mux.icache1_ctrl[en]  = 1'h1;
  assign \ddr_ram_mux.icache1_ctrl[inv]  = 1'h0;
  assign \ddr_ram_mux.instr_dbus_i  = { \ddr_ram_mux.u_bmuxc.m2_o[ack] , ddr_bus_i[31:0] };
  assign \ddr_ram_mux.instr_dbus_o  = { \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en]  };
  assign \ddr_ram_mux.instr_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ;
  assign \ddr_ram_mux.rst  = reset;
  assign { \ddr_ram_mux.u_bmuxc.bus_mux_typec.nx [78:2], \ddr_ram_mux.u_bmuxc.bus_mux_typec.nx [0] } = { 4'hx, ddr_bus_o[70:1], \ddr_ram_mux.ddr_bus_o[en] , 2'h0, \ddr_ram_mux.u_bmuxc.this_c [0] };
  assign \ddr_ram_mux.u_bmuxc.clk  = clk_sys;
  assign \ddr_ram_mux.u_bmuxc.m1_ack_r  = \ddr_ram_mux.data_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.m1_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[a]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[d]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[en]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[rd]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[we]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] ;
  assign \ddr_ram_mux.u_bmuxc.m1_i[wr]  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] ;
  assign \ddr_ram_mux.u_bmuxc.m1_lock  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m1_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.m2_ack_r  = \ddr_ram_mux.instr_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.m2_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[a]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[d]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[en]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[rd]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[we]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] ;
  assign \ddr_ram_mux.u_bmuxc.m2_i[wr]  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] ;
  assign \ddr_ram_mux.u_bmuxc.m2_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.m3_ddrburst  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[rd]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_lock  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m3_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.m4_ddrburst  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[rd]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m4_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.m5_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[bgrp]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[burst16]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[burst32]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.m5_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.m6_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y ;
  assign \ddr_ram_mux.u_bmuxc.m6_i  = { \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] , ddr_bus_i[31:0] };
  assign \ddr_ram_mux.u_bmuxc.m6_o  = { \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:1], \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en]  };
  assign \ddr_ram_mux.u_bmuxc.mem_i[ack]  = \ddr_ram_mux.ddr_bus_i[ack] ;
  assign \ddr_ram_mux.u_bmuxc.mem_i[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.mem_o[a]  = ddr_bus_o[32:1];
  assign \ddr_ram_mux.u_bmuxc.mem_o[d]  = ddr_bus_o[70:39];
  assign \ddr_ram_mux.u_bmuxc.mem_o[en]  = \ddr_ram_mux.ddr_bus_o[en] ;
  assign \ddr_ram_mux.u_bmuxc.mem_o[rd]  = ddr_bus_o[33];
  assign \ddr_ram_mux.u_bmuxc.mem_o[we]  = ddr_bus_o[38:35];
  assign \ddr_ram_mux.u_bmuxc.mem_o[wr]  = ddr_bus_o[34];
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.A [3], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.A [1:0] } = 3'h0;
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [30:19], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [17:0] } = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.A [2], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [31], 10'h2d8, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [31], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [18], 2'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [31], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [18], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B [18], 5'h02, \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] , 2'h0 };
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [29:28], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [26:23], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [21:19], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [17], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [15], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [13:12], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [10], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [8:5], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [3], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [1:0] } = { 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [31], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [22], 7'h00, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [9], 6'h00 };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[0].B_AND_BITS  = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [31], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [16], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [9], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [4], 1'h0 };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[1].B_AND_BITS  = { 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [22], 2'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [9], 2'h0 };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[2].B_AND_BITS  = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [30], 1'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [22], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [18], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [14], 2'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [2] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_OR[3].B_AND_BITS  = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [31], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], 3'h0, \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [11], 2'h0 };
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.S [6:5], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.S [1] } = { \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [27], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [22], \ddr_ram_mux.u_bmuxc.mux_m6.:6954.B_AND_S [4] };
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B [3], \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B [1] } = { \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B [7], \ddr_ram_mux.u_bmuxc.mux_m6.:6974.B [5] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:6974.Y  = \ddr_ram_mux.u_bmuxc.mux_m6.this_c [3:0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7075.A  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7075.B  = { \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst , \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7078.A  = 71'h000000000000000000;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7078.B  = { \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [0] = \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] ;
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.bus_mux_typecsub.nx [90:8], \ddr_ram_mux.u_bmuxc.mux_m6.bus_mux_typecsub.nx [3:0] } = { 4'hx, \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:1], \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] , 3'bx00, \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y , 4'h0, \ddr_ram_mux.u_bmuxc.mux_m6.this_c [3:0] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6.clk  = clk_sys;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m1_ack_r  = \ddr_ram_mux.data_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m1_lock  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m1_o[ack]  = \ddr_ram_mux.u_bmuxc.m1_o[ack] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m1_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m2_ack_r  = \ddr_ram_mux.instr_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m2_o[ack]  = \ddr_ram_mux.u_bmuxc.m2_o[ack] ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m2_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_ddrburst  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[rd]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_lock  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m3_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_ddrburst  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[rd]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m4_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[a]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[bgrp]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[burst16]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[burst32]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[d]  = 32'd0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[en]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[we]  = 4'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_i[wr]  = 1'h0;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.m5_o[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_ddrburst  = \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[d]  = ddr_bus_i[31:0];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[a]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [32:1];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[d]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:39];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[rd]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [33];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[we]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [38:35];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[wr]  = \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [34];
  assign \ddr_ram_mux.u_bmuxc.mux_m6.rst  = reset;
  assign \ddr_ram_mux.u_bmuxc.mux_m6.this_c [90:8] = { 3'hx, \ddr_ram_mux.u_bmuxc.mux_m6.mem_i[ack] , \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:1], \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en] , 3'bx00, \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y , 4'h0 };
  assign { \ddr_ram_mux.u_bmuxc.mux_m6.this_r [15:13], \ddr_ram_mux.u_bmuxc.mux_m6.this_r [11:8] } = 7'h00;
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3014  = { \ddr_ram_mux.u_bmuxc.m1_o[ack] , ddr_bus_i[31:0] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3015  = \ddr_ram_mux.data_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3016  = { \ddr_ram_mux.u_bmuxc.m2_o[ack] , ddr_bus_i[31:0] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3017  = \ddr_ram_mux.instr_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3018  = { 1'hx, ddr_bus_i[31:0] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3020  = { 1'hx, ddr_bus_i[31:0] };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3024  = { \ddr_ram_mux.u_bmuxc.mux_m6.:7078.Y [70:1], \ddr_ram_mux.u_bmuxc.mux_m6.mem_o[en]  };
  assign \ddr_ram_mux.u_bmuxc.mux_m6:3025  = \ddr_ram_mux.u_bmuxc.mux_m6.:7075.Y ;
  assign \ddr_ram_mux.u_bmuxc.rst  = reset;
  assign \ddr_ram_mux.u_bmuxc.this_c [78:2] = { 3'hx, \ddr_ram_mux.ddr_bus_i[ack] , ddr_bus_o[70:1], \ddr_ram_mux.ddr_bus_o[en] , 2'h0 };
  assign \ddr_ram_mux.u_bmuxc.this_r [3:2] = 2'h0;
  assign \ddr_ram_mux.u_bmuxc:484  = { \ddr_ram_mux.u_bmuxc.m1_o[ack] , ddr_bus_i[31:0] };
  assign \ddr_ram_mux.u_bmuxc:485  = \ddr_ram_mux.data_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc:487  = { \ddr_ram_mux.u_bmuxc.m2_o[ack] , ddr_bus_i[31:0] };
  assign \ddr_ram_mux.u_bmuxc:488  = \ddr_ram_mux.instr_dbus_ack_r ;
  assign \ddr_ram_mux.u_bmuxc:497  = { 1'hx, ddr_bus_i[31:0] };
  assign \ddr_ram_mux.u_bmuxc:498  = { ddr_bus_o[70:1], \ddr_ram_mux.ddr_bus_o[en]  };
  assign \ddr_ram_mux.u_dcache:452  = { \ddr_ram_mux.cpu0_dbus_i[ack] , \ddr_ram_mux.cpu0_dbus_i[d]  };
  assign \ddr_ram_mux.u_dcache:455  = { \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m1_i[en]  };
  assign \ddr_ram_mux.u_dcache:457  = \ddr_ram_mux.u_bmuxc.mux_m6.m1_ddrburst ;
  assign \ddr_ram_mux.u_icache:430  = { \ddr_ram_mux.cpu0_ibus_i[ack] , \ddr_ram_mux.cpu0_ibus_i[d]  };
  assign \ddr_ram_mux.u_icache:431  = { \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[d] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[we] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[wr] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[rd] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[a] , \ddr_ram_mux.u_bmuxc.mux_m6.m2_i[en]  };
  assign \ddr_ram_mux.u_icache:432  = \ddr_ram_mux.u_bmuxc.mux_m6.m2_ddrburst ;
  assign debug_i = 52'h0000000000000;
  assign dma_dbus_o = 73'h0000000000000000000;
  assign fl_miso = 1'hx;
  assign flash_ack_r = \mem_region_mux.flash_ack_r ;
  assign { flash_req[70:39], flash_req[34:0] } = { ddr_bus_o[70:39], \mem_region_mux.flash_req[wr] , \mem_region_mux.flash_req[rd] , ddr_bus_o[32:1], \mem_region_mux.flash_req[en]  };
  assign flash_resp = { \mem_region_mux.flash_resp[ack] , \mem_region_mux.flash_resp[d]  };
  assign \mem_region_mux.flash_bst  = flash_bst;
  assign \mem_region_mux.flash_req[a]  = ddr_bus_o[32:1];
  assign \mem_region_mux.flash_req[d]  = ddr_bus_o[70:39];
  assign \mem_region_mux.flash_req[we]  = flash_req[38:35];
  assign \mem_region_mux.req[a]  = ddr_bus_o[32:1];
  assign \mem_region_mux.req[d]  = ddr_bus_o[70:39];
  assign \mem_region_mux.req[en]  = \ddr_ram_mux.ddr_bus_o[en] ;
  assign \mem_region_mux.req[rd]  = ddr_bus_o[33];
  assign \mem_region_mux.req[we]  = ddr_bus_o[38:35];
  assign \mem_region_mux.req[wr]  = ddr_bus_o[34];
  assign \mem_region_mux.resp[ack]  = \ddr_ram_mux.ddr_bus_i[ack] ;
  assign \mem_region_mux.resp[d]  = ddr_bus_i[31:0];
  assign \mem_region_mux.sdram_bst  = sdram_bst;
  assign \mem_region_mux.sdram_req[a]  = ddr_bus_o[32:1];
  assign \mem_region_mux.sdram_req[d]  = ddr_bus_o[70:39];
  assign \mem_region_mux.sdram_req[we]  = sdram_req[38:35];
  assign sdram_ack_r = \mem_region_mux.sdram_ack_r ;
  assign { sdram_req[70:39], sdram_req[34:0] } = { ddr_bus_o[70:39], \mem_region_mux.sdram_req[wr] , \mem_region_mux.sdram_req[rd] , ddr_bus_o[32:1], \mem_region_mux.sdram_req[en]  };
  assign sdram_resp = { \mem_region_mux.sdram_resp[ack] , \mem_region_mux.sdram_resp[d]  };
endmodule
