// AUTO-GENERATED by chip_top gen (see chip_top/README.md) -- do not hand-edit.
// J4+MMU soc (chip_core.v, module `soc`) in a gf180mcu IO pad ring, single VDD/VSS
// power domain (IO supply tied to core, KianV-style). Driven by LibreLane Chip flow.
`default_nettype none
module chip_top (
`ifdef USE_POWER_PINS
    inout wire VDD, inout wire VSS,
`endif
    inout wire clk_sys_PAD,
    inout wire reset_PAD,
    inout wire uart0_rx_PAD,
    inout wire spi2_miso_PAD,
    inout wire qfl_cs_n_PAD,
    inout wire qfl_sck_PAD,
    inout wire spi2_clk_PAD,
    inout wire spi2_mosi_PAD,
    inout wire uart0_tx_PAD,
    inout wire sd_cmd_cas_n_PAD,
    inout wire sd_cmd_cke_PAD,
    inout wire sd_cmd_cs_n_PAD,
    inout wire sd_cmd_ras_n_PAD,
    inout wire sd_cmd_we_n_PAD,
    inout wire [12:0] sd_cmd_a_PAD,
    inout wire [1:0] sd_cmd_ba_PAD,
    inout wire [1:0] sd_cmd_dqm_PAD,
    inout wire [1:0] spi2_cs_PAD,
    inout wire [31:0] gpio_PAD,
    inout wire [3:0] qfl_io_PAD,
    inout wire [15:0] sd_dq_PAD
);
`ifndef USE_POWER_PINS
    wire VDD, VSS;
`endif
    wire clk_sys;
    wire reset;
    wire uart0_rx;
    wire spi2_miso;
    wire qfl_cs_n;
    wire qfl_sck;
    wire spi2_clk;
    wire spi2_mosi;
    wire uart0_tx;
    wire sd_cmd_cas_n;
    wire sd_cmd_cke;
    wire sd_cmd_cs_n;
    wire sd_cmd_ras_n;
    wire sd_cmd_we_n;
    wire [12:0] sd_cmd_a;
    wire [1:0] sd_cmd_ba;
    wire [1:0] sd_cmd_dqm;
    wire [1:0] spi2_cs;
    wire [31:0] gpio_do;
    wire [31:0] gpio_di;
    wire [3:0] qfl_io_o;
    wire [3:0] qfl_io_i;
    wire [3:0] qfl_io_oe;
    wire [15:0] sd_dq_o;
    wire [15:0] sd_dq_i;
    wire sd_dq_oe;
    soc u_soc (
        .clk_sys(clk_sys),
        .reset(reset),
        .uart0_rx(uart0_rx),
        .spi2_miso(spi2_miso),
        .qfl_cs_n(qfl_cs_n),
        .qfl_sck(qfl_sck),
        .spi2_clk(spi2_clk),
        .spi2_mosi(spi2_mosi),
        .uart0_tx(uart0_tx),
        .sd_cmd_cas_n(sd_cmd_cas_n),
        .sd_cmd_cke(sd_cmd_cke),
        .sd_cmd_cs_n(sd_cmd_cs_n),
        .sd_cmd_ras_n(sd_cmd_ras_n),
        .sd_cmd_we_n(sd_cmd_we_n),
        .sd_cmd_a(sd_cmd_a),
        .sd_cmd_ba(sd_cmd_ba),
        .sd_cmd_dqm(sd_cmd_dqm),
        .spi2_cs(spi2_cs),
        .gpio_do(gpio_do),
        .gpio_di(gpio_di),
        .qfl_io_o(qfl_io_o),
        .qfl_io_i(qfl_io_i),
        .qfl_io_oe(qfl_io_oe),
        .sd_dq_o(sd_dq_o),
        .sd_dq_i(sd_dq_i),
        .sd_dq_oe(sd_dq_oe)
    );
    (* keep *) gf180mcu_fd_io__in_c pad_clk_sys (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .PU(1'b0), .PD(1'b0), .PAD(clk_sys_PAD), .Y(clk_sys) );
    (* keep *) gf180mcu_fd_io__in_c pad_reset (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .PU(1'b0), .PD(1'b0), .PAD(reset_PAD), .Y(reset) );
    (* keep *) gf180mcu_fd_io__in_c pad_uart0_rx (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .PU(1'b0), .PD(1'b0), .PAD(uart0_rx_PAD), .Y(uart0_rx) );
    (* keep *) gf180mcu_fd_io__in_c pad_spi2_miso (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .PU(1'b0), .PD(1'b0), .PAD(spi2_miso_PAD), .Y(spi2_miso) );
    (* keep *) gf180mcu_fd_io__bi_t pad_qfl_cs_n (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(qfl_cs_n), .Y(), .PAD(qfl_cs_n_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_qfl_sck (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(qfl_sck), .Y(), .PAD(qfl_sck_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_spi2_clk (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(spi2_clk), .Y(), .PAD(spi2_clk_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_spi2_mosi (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(spi2_mosi), .Y(), .PAD(spi2_mosi_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_uart0_tx (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(uart0_tx), .Y(), .PAD(uart0_tx_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_cas_n (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_cas_n), .Y(), .PAD(sd_cmd_cas_n_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_cke (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_cke), .Y(), .PAD(sd_cmd_cke_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_cs_n (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_cs_n), .Y(), .PAD(sd_cmd_cs_n_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_ras_n (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_ras_n), .Y(), .PAD(sd_cmd_ras_n_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_we_n (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_we_n), .Y(), .PAD(sd_cmd_we_n_PAD) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_0 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[0]), .Y(), .PAD(sd_cmd_a_PAD[0]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_1 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[1]), .Y(), .PAD(sd_cmd_a_PAD[1]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_2 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[2]), .Y(), .PAD(sd_cmd_a_PAD[2]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_3 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[3]), .Y(), .PAD(sd_cmd_a_PAD[3]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_4 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[4]), .Y(), .PAD(sd_cmd_a_PAD[4]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_5 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[5]), .Y(), .PAD(sd_cmd_a_PAD[5]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_6 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[6]), .Y(), .PAD(sd_cmd_a_PAD[6]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_7 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[7]), .Y(), .PAD(sd_cmd_a_PAD[7]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_8 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[8]), .Y(), .PAD(sd_cmd_a_PAD[8]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_9 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[9]), .Y(), .PAD(sd_cmd_a_PAD[9]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_10 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[10]), .Y(), .PAD(sd_cmd_a_PAD[10]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_11 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[11]), .Y(), .PAD(sd_cmd_a_PAD[11]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_a_12 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_a[12]), .Y(), .PAD(sd_cmd_a_PAD[12]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_ba_0 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_ba[0]), .Y(), .PAD(sd_cmd_ba_PAD[0]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_ba_1 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_ba[1]), .Y(), .PAD(sd_cmd_ba_PAD[1]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_dqm_0 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_dqm[0]), .Y(), .PAD(sd_cmd_dqm_PAD[0]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_cmd_dqm_1 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(sd_cmd_dqm[1]), .Y(), .PAD(sd_cmd_dqm_PAD[1]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_spi2_cs_0 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(spi2_cs[0]), .Y(), .PAD(spi2_cs_PAD[0]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_spi2_cs_1 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(spi2_cs[1]), .Y(), .PAD(spi2_cs_PAD[1]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_0 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[0]), .Y(gpio_di[0]), .PAD(gpio_PAD[0]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_1 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[1]), .Y(gpio_di[1]), .PAD(gpio_PAD[1]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_2 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[2]), .Y(gpio_di[2]), .PAD(gpio_PAD[2]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_3 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[3]), .Y(gpio_di[3]), .PAD(gpio_PAD[3]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_4 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[4]), .Y(gpio_di[4]), .PAD(gpio_PAD[4]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_5 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[5]), .Y(gpio_di[5]), .PAD(gpio_PAD[5]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_6 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[6]), .Y(gpio_di[6]), .PAD(gpio_PAD[6]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_7 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[7]), .Y(gpio_di[7]), .PAD(gpio_PAD[7]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_8 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[8]), .Y(gpio_di[8]), .PAD(gpio_PAD[8]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_9 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[9]), .Y(gpio_di[9]), .PAD(gpio_PAD[9]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_10 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[10]), .Y(gpio_di[10]), .PAD(gpio_PAD[10]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_11 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[11]), .Y(gpio_di[11]), .PAD(gpio_PAD[11]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_12 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[12]), .Y(gpio_di[12]), .PAD(gpio_PAD[12]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_13 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[13]), .Y(gpio_di[13]), .PAD(gpio_PAD[13]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_14 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[14]), .Y(gpio_di[14]), .PAD(gpio_PAD[14]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_15 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[15]), .Y(gpio_di[15]), .PAD(gpio_PAD[15]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_16 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[16]), .Y(gpio_di[16]), .PAD(gpio_PAD[16]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_17 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[17]), .Y(gpio_di[17]), .PAD(gpio_PAD[17]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_18 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[18]), .Y(gpio_di[18]), .PAD(gpio_PAD[18]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_19 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[19]), .Y(gpio_di[19]), .PAD(gpio_PAD[19]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_20 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[20]), .Y(gpio_di[20]), .PAD(gpio_PAD[20]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_21 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[21]), .Y(gpio_di[21]), .PAD(gpio_PAD[21]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_22 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[22]), .Y(gpio_di[22]), .PAD(gpio_PAD[22]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_23 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[23]), .Y(gpio_di[23]), .PAD(gpio_PAD[23]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_24 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[24]), .Y(gpio_di[24]), .PAD(gpio_PAD[24]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_25 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[25]), .Y(gpio_di[25]), .PAD(gpio_PAD[25]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_26 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[26]), .Y(gpio_di[26]), .PAD(gpio_PAD[26]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_27 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[27]), .Y(gpio_di[27]), .PAD(gpio_PAD[27]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_28 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[28]), .Y(gpio_di[28]), .PAD(gpio_PAD[28]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_29 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[29]), .Y(gpio_di[29]), .PAD(gpio_PAD[29]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_30 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[30]), .Y(gpio_di[30]), .PAD(gpio_PAD[30]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_gpio_31 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(1'b1), .A(gpio_do[31]), .Y(gpio_di[31]), .PAD(gpio_PAD[31]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_qfl_io_0 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(qfl_io_oe[0]), .A(qfl_io_o[0]), .Y(qfl_io_i[0]), .PAD(qfl_io_PAD[0]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_qfl_io_1 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(qfl_io_oe[1]), .A(qfl_io_o[1]), .Y(qfl_io_i[1]), .PAD(qfl_io_PAD[1]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_qfl_io_2 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(qfl_io_oe[2]), .A(qfl_io_o[2]), .Y(qfl_io_i[2]), .PAD(qfl_io_PAD[2]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_qfl_io_3 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(qfl_io_oe[3]), .A(qfl_io_o[3]), .Y(qfl_io_i[3]), .PAD(qfl_io_PAD[3]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_0 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[0]), .Y(sd_dq_i[0]), .PAD(sd_dq_PAD[0]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_1 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[1]), .Y(sd_dq_i[1]), .PAD(sd_dq_PAD[1]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_2 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[2]), .Y(sd_dq_i[2]), .PAD(sd_dq_PAD[2]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_3 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[3]), .Y(sd_dq_i[3]), .PAD(sd_dq_PAD[3]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_4 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[4]), .Y(sd_dq_i[4]), .PAD(sd_dq_PAD[4]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_5 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[5]), .Y(sd_dq_i[5]), .PAD(sd_dq_PAD[5]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_6 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[6]), .Y(sd_dq_i[6]), .PAD(sd_dq_PAD[6]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_7 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[7]), .Y(sd_dq_i[7]), .PAD(sd_dq_PAD[7]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_8 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[8]), .Y(sd_dq_i[8]), .PAD(sd_dq_PAD[8]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_9 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[9]), .Y(sd_dq_i[9]), .PAD(sd_dq_PAD[9]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_10 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[10]), .Y(sd_dq_i[10]), .PAD(sd_dq_PAD[10]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_11 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[11]), .Y(sd_dq_i[11]), .PAD(sd_dq_PAD[11]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_12 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[12]), .Y(sd_dq_i[12]), .PAD(sd_dq_PAD[12]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_13 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[13]), .Y(sd_dq_i[13]), .PAD(sd_dq_PAD[13]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_14 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[14]), .Y(sd_dq_i[14]), .PAD(sd_dq_PAD[14]) );
    (* keep *) gf180mcu_fd_io__bi_t pad_sd_dq_15 (
`ifdef USE_POWER_PINS
        .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS),
`endif
        .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0), .PDRV0(1'b1), .PDRV1(1'b1),
        .IE(1'b1), .OE(sd_dq_oe), .A(sd_dq_o[15]), .Y(sd_dq_i[15]), .PAD(sd_dq_PAD[15]) );
    (* keep *) gf180mcu_fd_io__dvdd pad_dvdd_0 ( .DVDD(VDD), .DVSS(VSS), .VSS(VSS) );
    (* keep *) gf180mcu_fd_io__dvdd pad_dvdd_1 ( .DVDD(VDD), .DVSS(VSS), .VSS(VSS) );
    (* keep *) gf180mcu_fd_io__dvdd pad_dvdd_2 ( .DVDD(VDD), .DVSS(VSS), .VSS(VSS) );
    (* keep *) gf180mcu_fd_io__dvdd pad_dvdd_3 ( .DVDD(VDD), .DVSS(VSS), .VSS(VSS) );
    (* keep *) gf180mcu_fd_io__dvdd pad_dvdd_4 ( .DVDD(VDD), .DVSS(VSS), .VSS(VSS) );
    (* keep *) gf180mcu_fd_io__dvdd pad_dvdd_5 ( .DVDD(VDD), .DVSS(VSS), .VSS(VSS) );
    (* keep *) gf180mcu_fd_io__dvdd pad_dvdd_6 ( .DVDD(VDD), .DVSS(VSS), .VSS(VSS) );
    (* keep *) gf180mcu_fd_io__dvdd pad_dvdd_7 ( .DVDD(VDD), .DVSS(VSS), .VSS(VSS) );
    (* keep *) gf180mcu_fd_io__dvss pad_dvss_0 ( .DVDD(VDD), .DVSS(VSS), .VDD(VDD) );
    (* keep *) gf180mcu_fd_io__dvss pad_dvss_1 ( .DVDD(VDD), .DVSS(VSS), .VDD(VDD) );
    (* keep *) gf180mcu_fd_io__dvss pad_dvss_2 ( .DVDD(VDD), .DVSS(VSS), .VDD(VDD) );
    (* keep *) gf180mcu_fd_io__dvss pad_dvss_3 ( .DVDD(VDD), .DVSS(VSS), .VDD(VDD) );
    (* keep *) gf180mcu_fd_io__dvss pad_dvss_4 ( .DVDD(VDD), .DVSS(VSS), .VDD(VDD) );
    (* keep *) gf180mcu_fd_io__dvss pad_dvss_5 ( .DVDD(VDD), .DVSS(VSS), .VDD(VDD) );
    (* keep *) gf180mcu_fd_io__dvss pad_dvss_6 ( .DVDD(VDD), .DVSS(VSS), .VDD(VDD) );
    (* keep *) gf180mcu_fd_io__dvss pad_dvss_7 ( .DVDD(VDD), .DVSS(VSS), .VDD(VDD) );
endmodule
`default_nettype wire
