package cheader

import (
	"fmt"
	"sort"
	"strings"

	"github.com/j-core/jcore-soc/tools/socgen/elaborate"
)

// classKey is the key under which a class is stored in res.Classes (faithful to
// elaborate's lc: lower-cased, trimmed). The device->class match in BoardH must
// use this same key.
func classKey(s string) string { return strings.ToLower(strings.TrimSpace(s)) }

// BoardH renders the bootloader C header (board.h), faithful to c_header.clj
// gen-bootloader-header.
func BoardH(res *elaborate.Resolution) (string, error) {
	if res == nil {
		return "", nil
	}
	var b strings.Builder
	b.WriteString("// This file is generated by soc_gen and will be overwritten next time\n")
	b.WriteString("// the tool is run. See soc_top/README for information on running soc_gen.\n\n")
	b.WriteString("#ifndef BOARD_H\n#define BOARD_H\n#include <inttypes.h>\n")
	b.WriteString("\n#define DRAM_BASE 0x10000000\n") // hardcoded in c_header.clj (TODO there)

	devs := dataBusDevices(res) // BaseAddr != nil, sorted by upper(Name)
	b.WriteString("\n// Memory mapped peripherals\n")
	maxLen := 0
	for _, d := range devs {
		if len(d.Name) > maxLen {
			maxLen = len(d.Name)
		}
	}
	for _, d := range devs {
		b.WriteString(fmt.Sprintf("#define DEVICE_%s_ADDR %s0x%08x\n",
			strings.ToUpper(d.Name), strings.Repeat(" ", maxLen-len(d.Name)), *d.BaseAddr))
	}
	b.WriteString("\n")

	var clsKeys []string
	for k, c := range res.Classes {
		if len(c.Regs) > 0 {
			clsKeys = append(clsKeys, k)
		}
	}
	sort.Strings(clsKeys) // sort by class key (lower-cased class name)
	for _, k := range clsKeys {
		c := res.Classes[k]
		s, ok := classRegStruct(c.Name, c.Regs)
		if !ok {
			b.WriteString(fmt.Sprintf("// %s contains unaligned registers\n\n", c.Name))
			continue
		}
		b.WriteString(s + "\n")
		for _, d := range devs {
			if classKey(d.Class) == k {
				b.WriteString(fmt.Sprintf("#define DEVICE_%s ((volatile struct %s_regs *) DEVICE_%s_ADDR)\n",
					strings.ToUpper(d.Name), c.Name, strings.ToUpper(d.Name)))
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("\n#endif\n")
	return b.String(), nil
}

// dataBusDevices returns res.Devices with a base-addr, sorted by upper(Name).
func dataBusDevices(res *elaborate.Resolution) []*elaborate.ResolvedDevice {
	var out []*elaborate.ResolvedDevice
	for _, d := range res.Devices {
		if d.BaseAddr != nil {
			out = append(out, d)
		}
	}
	sort.Slice(out, func(i, j int) bool { return strings.ToUpper(out[i].Name) < strings.ToUpper(out[j].Name) })
	return out
}
